services:
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:host=%db.host%;dbname=%db.name%"
            user: "%db.username%"
            password: "%db.password%"

    facebook_engagement.query.standard:
        class:     Outlandish\SocialMonitor\FacebookEngagement\Query\StandardFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.query.weighted:
        class:     Outlandish\SocialMonitor\FacebookEngagement\Query\WeightedFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.standard:
        class:     Outlandish\SocialMonitor\FacebookEngagement\FacebookEngagementMetric
        arguments: ["@facebook_engagement.query.standard"]

    facebook_engagement.weighted:
        class:     Outlandish\SocialMonitor\FacebookEngagement\FacebookEngagementMetric
        arguments: ["@facebook_engagement.query.weighted"]

    facebook.session_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\SessionFactory
        arguments: ["%facebook.app_id%", "%facebook.app_secret%"]

    facebook.request_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\RequestFactory
        arguments: ["@facebook.session_factory"]

    facebook.likes_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\LikesCountFetcher
        arguments: ["@facebook.request_factory"]

    facebook.comments_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\CommentsCountFetcher
        arguments: ["@facebook.request_factory"]

    facebook.feed_fetcher:
        class: Outlandish\SocialMonitor\FacebookFetcher\FeedFetcher
        arguments: ["@facebook.request_factory", "@facebook.post_parser"]

    facebook.post_parser:
        class: Outlandish\SocialMonitor\FacebookFetcher\PostParser
        arguments: ["@facebook.comments_counter", "@facebook.likes_counter"]

    facebook.app:
        class: Outlandish\SocialMonitor\FacebookApp
        arguments: ["@facebook.request_factory", "@facebook.likes_counter", "@facebook.comments_counter", "@facebook.feed_fetcher"]