# default values; should be overridden in parameters.yml to be non-empty
parameters:
    app.locale: en
    presence-type.twitter.metrics: []
    presence-type.facebook.metrics: []
    presence-type.instagram.metrics: []
    presence-type.youtube.metrics: []
    presence-type.linkedin.metrics: []
    presence-type.sina-weibo.metrics: []
    badge.engagement.metrics: []
    badge.quality.metrics: []
    badge.reach.metrics: []
    badge.total.badges: [@badge.reach, @badge.engagement, @badge.quality]
    table.regions.headers: []
    table.groups.headers: []
    table.countries.headers: []
    table.presences.headers: []
    joyride.home.steps: []
    joyride.presence.steps: []
    favicon.name: 'default.ico'
    map.cannot_see_colours: []
    colours.definitions:
        grey: '#d2d2d2'
        red: '#D06959'
        green: '#84af5b'
        orange: '#F1DC63'
        yellow: '#FFFF50'
        white: '#fff'
    table.rules: []
    rank.rules: []
    csrf.exceptions: []

services:
    db:
        class: Outlandish\SocialMonitor\Database\Database
        arguments:
            dsn: "mysql:host=%db.host%;dbname=%db.name%"
            user: %db.username%
            password: %db.password%

    translation.message-selector:
        class: Symfony\Component\Translation\MessageSelector

    translation.csv-loader:
        class: Symfony\Component\Translation\Loader\CsvFileLoader

    translation.json-loader:
        class: Symfony\Component\Translation\Loader\JsonFileLoader

    translation.translator:
        class: Outlandish\SocialMonitor\Translation\Translator
        arguments: [%app.locale%, @translation.message-selector]
        calls:
            - [addLoader, ["json", @translation.json-loader]]
            - [loadFromDirectory, ['json', 'assets/build/lang']]
            - [setFallbackLocale, ['en']]

    guzzle.client:
        class: GuzzleHttp\Client

    ###################################
    # report services
    ###################################
    report.downloader:
        class: Outlandish\SocialMonitor\Report\ReportDownloader
        arguments: [%pdf.base_url%, %report.base_url%]

    ###################################
    # adapters
    ###################################
    adapter.facebook:
        class: Outlandish\SocialMonitor\Adapter\FacebookAdapter
        arguments: [@facebook.app]

    adapter.instagram:
        class: Outlandish\SocialMonitor\Adapter\InstagramAdapter
        arguments: [@instagram.app]

    adapter.youtube:
        class: Outlandish\SocialMonitor\Adapter\YoutubeAdapter
        arguments: [@google.youtube]

    adapter.linkedin:
        class: Outlandish\SocialMonitor\Adapter\LinkedinAdapter
        arguments: [@linkedin.client]

    adapter.twitter:
        class: Outlandish\SocialMonitor\Adapter\TwitterAdapter
        arguments: [%twitter.fetch_per_page%]

    ###################################
    # providers
    ###################################
    provider.twitter:
        class: Provider_Twitter
        arguments: [@db, @adapter.twitter, @presence-type.twitter]

    provider.facebook:
        class: Provider_Facebook
        arguments: [@db, @adapter.facebook, @facebook_engagement.weighted, @presence-type.facebook]

    provider.instagram:
        class: Provider_Instagram
        arguments: [@db, @adapter.instagram, @presence-type.instagram]

    provider.youtube:
        class: Provider_Youtube
        arguments: [@db, @adapter.youtube, @youtube_engagement.weighted, @presence-type.youtube]

    provider.linkedin:
        class: Provider_Linkedin
        arguments: [@db, @adapter.linkedin, @presence-type.linkedin]

    provider.sinaweibo:
        class: Provider_SinaWeibo
        arguments: [@db, @presence-type.sina-weibo]

    ###################################
    # instagram engagement services
    ###################################
    instagram.app:
        class: Outlandish\SocialMonitor\InstagramApp
        arguments: [%instagram.app_token%]


    ###################################
    # youtube engagement services
    ###################################
    youtube_engagement.weighted:
        class: Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: [@engagement-query.youtube]


    ###################################
    # linked in api services
    ###################################

    linkedin.client:
        class: LinkedIn\LinkedIn
        arguments:
            -
                api_key: %linkedin.client_id%
                api_secret: %linkedin.client_secret%
                callback_url: %linkedin.redirect_url%

    ###################################
    # google api services
    ###################################

    google.client:
        class: Google_Client
        calls:
            - [setApplicationName, ["Social_Monitor"]]
            - [setDeveloperKey, [%youtube.api_key%]]

    google.youtube:
        class: Google_Service_YouTube
        arguments: [@google.client]

    ###################################
    # sina weibo engagement services
    ###################################
    sina_weibo.engagement.query.weighted:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedSinaWeiboEngagementQuery
        arguments: [@db]

    sina_weibo.engagement.weighted:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: [@sina_weibo.engagement.query.weighted]

    ###################################
    # facebook engagement services
    ###################################
    facebook_engagement.query.standard:
        class:     Outlandish\SocialMonitor\Engagement\Query\StandardFacebookEngagementQuery
        arguments: [@db]

    facebook_engagement.standard:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: [@facebook_engagement.query.standard]

    facebook_engagement.weighted:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: [@engagement-query.facebook]

    facebook.session_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\SessionFactory
        arguments: [%facebook.app_id%, %facebook.app_secret%]

    facebook.request_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\RequestFactory
        arguments: [@facebook.session_factory]

    facebook.likes_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\LikesCountFetcher
        arguments: [@facebook.request_factory]

    facebook.comments_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\CommentsCountFetcher
        arguments: [@facebook.request_factory]

    facebook.feed_fetcher:
        class: Outlandish\SocialMonitor\FacebookFetcher\FeedFetcher
        arguments: [@facebook.request_factory, @facebook.post_parser]

    facebook.post_parser:
        class: Outlandish\SocialMonitor\FacebookFetcher\PostParser
        arguments: [@facebook.comments_counter, @facebook.likes_counter]

    facebook.app:
        class: Outlandish\SocialMonitor\FacebookApp
        arguments: [@facebook.request_factory, @facebook.likes_counter, @facebook.comments_counter, @facebook.feed_fetcher, @facebook_engagement.weighted]

    # Headers

    table.header.handle:
        class: Outlandish\SocialMonitor\TableIndex\Header\Handle
        arguments: [@translation.translator]

    table.header.branding:
        class: Outlandish\SocialMonitor\TableIndex\Header\Branding
        arguments: [@translation.translator]

    table.header.sign_off:
        class: Outlandish\SocialMonitor\TableIndex\Header\SignOff
        arguments: [@translation.translator]

    table.header.total_rank:
        class: Outlandish\SocialMonitor\TableIndex\Header\TotalRank
        arguments: [@translation.translator]

    table.header.total_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\TotalScore
        arguments: [@translation.translator]

    table.header.reach_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\ReachScore
        arguments: [@translation.translator]

    table.header.engagement_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\EngagementScore
        arguments: [@translation.translator]

    table.header.quality_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\QualityScore
        arguments: [@translation.translator]

    table.header.current_audience:
        class: Outlandish\SocialMonitor\TableIndex\Header\CurrentAudience
        arguments: [@translation.translator]

    table.header.target_audience:
        class: Outlandish\SocialMonitor\TableIndex\Header\TargetAudience
        arguments: [@translation.translator]

    table.header.actions_per_day:
        class: Outlandish\SocialMonitor\TableIndex\Header\ActionsPerDay
        arguments: [@translation.translator]

    table.header.response_time:
        class: Outlandish\SocialMonitor\TableIndex\Header\ResponseTime
        arguments: [@translation.translator]

    table.header.options:
        class: Outlandish\SocialMonitor\TableIndex\Header\Options
        arguments: [@translation.translator]

    table.header.name:
        class: Outlandish\SocialMonitor\TableIndex\Header\Name
        arguments: [@translation.translator]

    table.header.digital_population:
        class: Outlandish\SocialMonitor\TableIndex\Header\DigitalPopulation
        arguments: [@translation.translator]

    table.header.digital_population_health:
        class: Outlandish\SocialMonitor\TableIndex\Header\DigitalPopulationHealth
        arguments: [@translation.translator]

    table.header.presences:
        class: Outlandish\SocialMonitor\TableIndex\Header\Presences
        arguments: [@translation.translator]

    table.header.presence_count:
        class: Outlandish\SocialMonitor\TableIndex\Header\PresenceCount
        arguments: [@translation.translator]

    table.header.countries:
        class: Outlandish\SocialMonitor\TableIndex\Header\Countries
        arguments: [@translation.translator]

    table.header.country_count:
        class: Outlandish\SocialMonitor\TableIndex\Header\CountryCount
        arguments: [@translation.translator]

    table.header.parent:
        class: Outlandish\SocialMonitor\TableIndex\Header\ParentName
        arguments: [@translation.translator]

    table.header.region_parent:
        class: Outlandish\SocialMonitor\TableIndex\Header\Region
        arguments: [@translation.translator]

    table.header.presence_type:
        class: Outlandish\SocialMonitor\TableIndex\Header\PresenceType
        arguments: [@translation.translator]

    table.header.group:
        class: Outlandish\SocialMonitor\TableIndex\Header\Group
        arguments: [@translation.translator]

    # Index table data sources
    table.source.region:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\RegionSource
    table.source.group:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\GroupSource
    table.source.country:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\CountrySource
    table.source.presence:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\PresenceSource

    # Index Tables
    table.region-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['region-index', @table.source.region, %table.regions.headers%]

    table.group-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['group-index', @table.source.group, %table.groups.headers%]

    table.country-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['country-index', @table.source.country, %table.countries.headers%]

    table.presence-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['presence-index', @table.source.presence, %table.presences.headers%]

    history-query.total-population:
        class: Outlandish\SocialMonitor\Query\TotalPopularityHistoryDataQuery
        arguments: [@db]

    object-cache-manager:
        class: Outlandish\SocialMonitor\Cache\ObjectCacheManager
        arguments: [@db, @history-query.total-population]
        calls:
            - [setPresencesTable, [@table.presence-index]]
            - [setCountriesTable, [@table.country-index]]
            - [setGroupsTable, [@table.group-index]]
            - [setRegionsTable, [@table.region-index]]

    # engagement metric query classes
    engagement-query.facebook:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedFacebookEngagementQuery
        arguments: [@db]
    engagement-query.instagram:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedInstagramEngagementQuery
        arguments: [@db]
    engagement-query.linkedin:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedLinkedinEngagementQuery
        arguments: [@db]
    engagement-query.sina-weibo:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedSinaWeiboEngagementQuery
        arguments: [@db]
    engagement-query.youtube:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedYoutubeEngagementQuery
        arguments: [@db]

    # metrics
    metric.actions-per-day:
        class: Metric_ActionsPerDay
        arguments: [@translation.translator]
    metric.branding:
        class: Metric_Branding
        arguments: [@translation.translator]
    metric.facebook-engagement:
        class: Metric_FBEngagement
        arguments: [@translation.translator, @engagement-query.facebook]
    metric.instagram-engagement:
        class: Metric_InstagramEngagement
        arguments: [@translation.translator, @engagement-query.instagram]
    metric.klout:
        class: Metric_Klout
        arguments: [@translation.translator]
    metric.likes-per-post:
        class: Metric_LikesPerPost
        arguments: [@translation.translator]
    metric.likes-per-view:
        class: Metric_LikesPerView
        arguments: [@translation.translator]
    metric.linkedin-engagement:
        class: Metric_LinkedinEngagement
        arguments: [@translation.translator, @engagement-query.linkedin]
    metric.popularity:
        class: Metric_Popularity
        arguments: [@translation.translator]
    metric.popularity-time:
        class: Metric_PopularityTime
        arguments: [@translation.translator]
    metric.relevance:
        class: Metric_Relevance
        arguments: [@translation.translator]
    metric.response-ratio:
        class: Metric_ResponseRatio
        arguments: [@translation.translator]
    metric.response-time:
        class: Metric_ResponseTime
        arguments: [@translation.translator]
    metric.sign-off:
        class: Metric_SignOff
        arguments: [@translation.translator]
    metric.sina-weibo-engagement:
        class: Metric_SinaWeiboEngagement
        arguments: [@translation.translator, @engagement-query.sina-weibo]
    metric.youtube-engagement:
        class: Metric_YoutubeEngagement
        arguments: [@translation.translator, @engagement-query.youtube]
    metric.relevant-hashtags:
        class: Metric_RelevantHashtags
        arguments: [@translation.translator]

    # presence types
    presence-type.twitter:
        class: Outlandish\SocialMonitor\PresenceType\TwitterType
        arguments: [@metric.klout, %presence-type.twitter.metrics%]
        calls:
            - [setProvider, [@provider.twitter]]

    presence-type.facebook:
        class: Outlandish\SocialMonitor\PresenceType\FacebookType
        arguments: [@metric.facebook-engagement, %presence-type.facebook.metrics%]
        calls:
            - [setProvider, [@provider.facebook]]

    presence-type.instagram:
        class: Outlandish\SocialMonitor\PresenceType\InstagramType
        arguments: [@metric.instagram-engagement, %presence-type.instagram.metrics%]
        calls:
            - [setProvider, [@provider.instagram]]

    presence-type.youtube:
        class: Outlandish\SocialMonitor\PresenceType\YoutubeType
        arguments: [@metric.youtube-engagement, %presence-type.youtube.metrics%]
        calls:
            - [setProvider, [@provider.youtube]]

    presence-type.linkedin:
        class: Outlandish\SocialMonitor\PresenceType\LinkedinType
        arguments: [@metric.linkedin-engagement, %presence-type.linkedin.metrics%]
        calls:
            - [setProvider, [@provider.linkedin]]

    presence-type.sina-weibo:
        class: Outlandish\SocialMonitor\PresenceType\SinaWeiboType
        arguments: [@metric.sina-weibo-engagement, %presence-type.sina-weibo.metrics%]
        calls:
            - [setProvider, [@provider.sinaweibo]]

    # badges
    badge.engagement:
        class: Badge_Engagement
        arguments: [@db, @translation.translator, %badge.engagement.metrics%]

    badge.quality:
        class: Badge_Quality
        arguments: [@db, @translation.translator, %badge.quality.metrics%]

    badge.reach:
        class: Badge_Reach
        arguments: [@db, @translation.translator, %badge.reach.metrics%]

    badge.total:
        class: Badge_Total
        arguments: [@db, @translation.translator, %badge.total.badges%]

    # charts
    chart.compare:
        class: Chart_Compare
        arguments: [@db, @translation.translator]

    chart.popularity:
        class: Chart_Popularity
        arguments: [@db, @translation.translator]

    chart.popularity-trend:
        class: Chart_PopularityTrend
        arguments: [@db, @translation.translator]

    chart.reach:
        class: Chart_Reach
        arguments: [@db, @translation.translator]

    chart.engagement:
        class: Chart_Engagement
        arguments: [@db, @translation.translator]

    chart.quality:
        class: Chart_Quality
        arguments: [@db, @translation.translator]

    # note: this would ideally be actions-per-day, but for the time being needs to match the 'name' property of the class
    chart.actionsPerDay:
        class: Chart_ActionsPerDay
        arguments: [@db, @translation.translator]

    chart.response-time:
        class: Chart_ResponseTime
        arguments: [@db, @translation.translator]


    kpi_download_linker:
        class: Outlandish\SocialMonitor\KpiPdfLinker

    joyride.home:
        class: Outlandish\SocialMonitor\Joyride\JoyrideService
        arguments: ["joyride-home", %joyride.home.steps%]

    joyride.presence:
        class: Outlandish\SocialMonitor\Joyride\JoyrideService
        arguments: ["joyride-presence", %joyride.presence.steps%]

    # Recaptcha services
    recaptcha.helper:
        class: Outlandish\SocialMonitor\Helper\Recaptcha
        arguments: [%recaptcha.site_key%, %recaptcha.secret%]

    # favicon
    favicon.helper:
        class: Outlandish\SocialMonitor\Helper\Favicon
        arguments: [%favicon.name%]

    # Colour services
    colours.definitions:
        class: Outlandish\SocialMonitor\Services\Colours\ColourDefinitions
        arguments: [%colours.definitions%]

    colours.map:
        class: Outlandish\SocialMonitor\Services\Colours\MapColours
        arguments: [@colours.definitions, %map.cannot_see_colours%]

    # Table Index guard
    table.guard_factory:
        class: Outlandish\SocialMonitor\Services\TableIndex\GuardFactory

    table.guard:
        class: Outlandish\SocialMonitor\Services\TableIndex\Guard
        factory: ["@table.guard_factory", createGuard]
        arguments:
            - %table.rules%

    # Rank Guard
    rank.guard:
        class: Outlandish\SocialMonitor\Services\Rank\Guard
        arguments: [%rank.rules%]

    csrf.exceptions:
        class: Outlandish\SocialMonitor\Services\CsrfExceptionsService
        arguments: [%csrf.exceptions%]