services:
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:host=%db.host%;dbname=%db.name%"
            user: "%db.username%"
            password: "%db.password%"

    guzzle.client:
        class: GuzzleHttp\Client

    ###################################
    # report services
    ###################################
    report.downloader:
        class: Outlandish\SocialMonitor\Report\ReportDownloader
        arguments: ["%pdf.base_url%", "%report.base_url%"]

    ###################################
    # adapters
    ###################################
    adapter.facebook:
        class: Outlandish\SocialMonitor\Adapter\FacebookAdapter
        arguments: ["@facebook.app"]

    adapter.instagram:
        class: Outlandish\SocialMonitor\Adapter\InstagramAdapter
        arguments: ["@instagram.app"]

    adapter.youtube:
        class: Outlandish\SocialMonitor\Adapter\YoutubeAdapter
        arguments: ["@google.youtube"]

    adapter.linkedin:
        class: Outlandish\SocialMonitor\Adapter\LinkedinAdapter
        arguments: ["@linkedin.client"]

    ###################################
    # instagram engagement services
    ###################################
    instagram.app:
        class: Outlandish\SocialMonitor\InstagramApp
        arguments: ["%instagram.app_token%"]

    instagram.query.weighted:
        class:     Outlandish\SocialMonitor\Engagement\Query\WeightedInstagramEngagementQuery
        arguments: ["@pdo"]


    ###################################
    # linked in api services
    ###################################

    linkedin.client:
        class: LinkedIn\LinkedIn
        arguments:
            -
                api_key: "%linkedin.client_id%"
                api_secret: "%linkedin.client_secret%"
                callback_url: "%linkedin.redirect_url%"

    ###################################
    # google api services
    ###################################

    google.client:
        class: Google_Client
        calls:
            - [setApplicationName, ["Social_Monitor"]]
            - [setDeveloperKey, ["%youtube.api_key%"]]

    google.youtube:
        class: Google_Service_YouTube
        arguments: ["@google.client"]

    ###################################
    # sina weibo engagement services
    ###################################
    sina_weibo.engagement.query.weighted:
        class: Outlandish\SocialMonitor\Engagement\Query\WeightedSinaWeiboEngagementQuery
        arguments: ["@pdo"]

    sina_weibo.engagement.weighted:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: ["@sina_weibo.engagement.query.weighted"]

    ###################################
    # facebook engagement services
    ###################################
    facebook_engagement.query.standard:
        class:     Outlandish\SocialMonitor\Engagement\Query\StandardFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.query.weighted:
        class:     Outlandish\SocialMonitor\Engagement\Query\WeightedFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.standard:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: ["@facebook_engagement.query.standard"]

    facebook_engagement.weighted:
        class:     Outlandish\SocialMonitor\Engagement\EngagementMetric
        arguments: ["@facebook_engagement.query.weighted"]

    facebook.session_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\SessionFactory
        arguments: ["%facebook.app_id%", "%facebook.app_secret%"]

    facebook.request_factory:
        class: Outlandish\SocialMonitor\FacebookFetcher\RequestFactory
        arguments: ["@facebook.session_factory"]

    facebook.likes_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\LikesCountFetcher
        arguments: ["@facebook.request_factory"]

    facebook.comments_counter:
        class: Outlandish\SocialMonitor\FacebookFetcher\CommentsCountFetcher
        arguments: ["@facebook.request_factory"]

    facebook.feed_fetcher:
        class: Outlandish\SocialMonitor\FacebookFetcher\FeedFetcher
        arguments: ["@facebook.request_factory", "@facebook.post_parser"]

    facebook.post_parser:
        class: Outlandish\SocialMonitor\FacebookFetcher\PostParser
        arguments: ["@facebook.comments_counter", "@facebook.likes_counter"]

    facebook.app:
        class: Outlandish\SocialMonitor\FacebookApp
        arguments: ["@facebook.request_factory", "@facebook.likes_counter", "@facebook.comments_counter", "@facebook.feed_fetcher", "@facebook_engagement.weighted"]

    # Headers

    table.header.handle:
        class: Outlandish\SocialMonitor\TableIndex\Header\Handle

    table.header.branding:
        class: Outlandish\SocialMonitor\TableIndex\Header\Branding

    table.header.sign_off:
        class: Outlandish\SocialMonitor\TableIndex\Header\SignOff

    table.header.total_rank:
        class: Outlandish\SocialMonitor\TableIndex\Header\TotalRank

    table.header.total_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\TotalScore

    table.header.reach_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\ReachScore

    table.header.engagement_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\EngagementScore

    table.header.quality_score:
        class: Outlandish\SocialMonitor\TableIndex\Header\QualityScore

    table.header.current_audience:
        class: Outlandish\SocialMonitor\TableIndex\Header\CurrentAudience

    table.header.target_audience:
        class: Outlandish\SocialMonitor\TableIndex\Header\TargetAudience

    table.header.actions_per_day:
        class: Outlandish\SocialMonitor\TableIndex\Header\ActionsPerDay

    table.header.response_time:
        class: Outlandish\SocialMonitor\TableIndex\Header\ResponseTime

    table.header.options:
        class: Outlandish\SocialMonitor\TableIndex\Header\Options

    table.header.name:
        class: Outlandish\SocialMonitor\TableIndex\Header\Name

    table.header.digital_population:
        class: Outlandish\SocialMonitor\TableIndex\Header\DigitalPopulation

    table.header.digital_population_health:
        class: Outlandish\SocialMonitor\TableIndex\Header\DigitalPopulationHealth

    table.header.presences:
        class: Outlandish\SocialMonitor\TableIndex\Header\Presences

    table.header.presence_count:
        class: Outlandish\SocialMonitor\TableIndex\Header\PresenceCount

    table.header.countries:
        class: Outlandish\SocialMonitor\TableIndex\Header\Countries

    table.header.country_count:
        class: Outlandish\SocialMonitor\TableIndex\Header\CountryCount

    table.header.parent:
        class: Outlandish\SocialMonitor\TableIndex\Header\ParentName

    # Index table data sources
    table.source.region:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\RegionSource
    table.source.group:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\GroupSource
    table.source.country:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\CountrySource
    table.source.presence:
        class: Outlandish\SocialMonitor\TableIndex\TableSource\PresenceSource

    # Index Tables
    table.region-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['region-index', "@table.source.region"]
        calls:
            - [addHeader, ["@table.header.name"]]
            - [addHeader, ["@table.header.total_rank"]]
            - [addHeader, ["@table.header.total_score"]]
            - [addHeader, ["@table.header.reach_score"]]
            - [addHeader, ["@table.header.engagement_score"]]
            - [addHeader, ["@table.header.quality_score"]]
            - [addHeader, ["@table.header.target_audience"]]
            - [addHeader, ["@table.header.current_audience"]]
            - [addHeader, ["@table.header.countries"]]
            - [addHeader, ["@table.header.country_count"]]
            - [addHeader, ["@table.header.presence_count"]]
            - [addHeader, ["@table.header.options"]]

    table.group-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['group-index', "@table.source.group"]
        calls:
            - [addHeader, ["@table.header.name"]]
            - [addHeader, ["@table.header.total_rank"]]
            - [addHeader, ["@table.header.total_score"]]
            - [addHeader, ["@table.header.reach_score"]]
            - [addHeader, ["@table.header.engagement_score"]]
            - [addHeader, ["@table.header.quality_score"]]
            - [addHeader, ["@table.header.target_audience"]]
            - [addHeader, ["@table.header.current_audience"]]
            - [addHeader, ["@table.header.presences"]]
            - [addHeader, ["@table.header.presence_count"]]
            - [addHeader, ["@table.header.options"]]

    table.country-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['country-index', "@table.source.country"]
        calls:
            - [addHeader, ["@table.header.name"]]
            - [addHeader, ["@table.header.total_rank"]]
            - [addHeader, ["@table.header.total_score"]]
            - [addHeader, ["@table.header.reach_score"]]
            - [addHeader, ["@table.header.engagement_score"]]
            - [addHeader, ["@table.header.quality_score"]]
            - [addHeader, ["@table.header.target_audience"]]
            - [addHeader, ["@table.header.current_audience"]]
            - [addHeader, ["@table.header.digital_population"]]
            - [addHeader, ["@table.header.presences"]]
            - [addHeader, ["@table.header.presence_count"]]
            - [addHeader, ["@table.header.options"]]

    table.presence-index:
        class: Outlandish\SocialMonitor\TableIndex\TableIndex
        arguments: ['presence-index', "@table.source.presence"]
        calls:
            - [addHeader, ["@table.header.handle"]]
            - [addHeader, ["@table.header.parent"]]
            - [addHeader, ["@table.header.branding"]]
            - [addHeader, ["@table.header.sign_off"]]
            - [addHeader, ["@table.header.total_rank"]]
            - [addHeader, ["@table.header.total_score"]]
            - [addHeader, ["@table.header.reach_score"]]
            - [addHeader, ["@table.header.engagement_score"]]
            - [addHeader, ["@table.header.quality_score"]]
            - [addHeader, ["@table.header.current_audience"]]
            - [addHeader, ["@table.header.target_audience"]]
            - [addHeader, ["@table.header.options"]]

    history-query.total-population:
        class: Outlandish\SocialMonitor\Query\TotalPopularityHistoryDataQuery
        arguments: ["@pdo"]

    object-cache-manager:
        class: Outlandish\SocialMonitor\Cache\ObjectCacheManager
        arguments: ["@pdo", "@history-query.total-population"]
        calls:
            - [setPresencesTable, ["@table.presence-index"]]
            - [setCountriesTable, ["@table.country-index"]]
            - [setGroupsTable, ["@table.group-index"]]
            - [setRegionsTable, ["@table.region-index"]]