services:
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:host=%db.host%;dbname=%db.name%"
            user: "%db.username%"
            password: "%db.password%"

    facebook_engagement.query.standard:
        class:     Outlandish\SocialMonitor\FacebookEngagement\Query\StandardFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.query.weighted:
        class:     Outlandish\SocialMonitor\FacebookEngagement\Query\WeightedFacebookEngagementQuery
        arguments: ["@pdo"]

    facebook_engagement.standard:
        class:     Outlandish\SocialMonitor\FacebookEngagement\FacebookEngagementMetric
        arguments: ["@facebook_engagement.query.standard"]

    facebook_engagement.weighted:
        class:     Outlandish\SocialMonitor\FacebookEngagement\FacebookEngagementMetric
        arguments: ["@facebook_engagement.query.weighted"]

    facebook.app:
        class: Outlandish\SocialMonitor\FacebookApp
        arguments: ["%facebook.app_id%", "%facebook.app_secret%"]