<?php
/** @var $presence Model_Presence */
$metric = $this->metric;
$date = new DateTime();
$data = Model_Badge::getAllData('month', $date, $date);
$data = Model_Presence::organizeBadgeData($data);
$data = Model_Presence::calculateTotalScores($data);
?>

<div class="country hide">
	<div class="close"><a href="#"><span class="icon-remove-circle icon-large"></span></a></div>
	<h3>
		<?php $url = $this->gatekeeper()->filter('%url%', array('action'=>'view', 'controller'=>'country', 'id'=>$this->country->id)); if ($url) : ?>
        <a href="<?php echo $url; ?>">
            <span class="icon-globe icon-large"></span>
            <?php echo $this->country->display_name; ?>
        </a>
		<?php else : ?>
		<span>
			<span class="icon-globe icon-large"></span>
			<?php echo $this->country->display_name; ?>
		</span>
		<?php endif; ?>
    </h3>
	<?php if ($this->country->presences) : ?>
    <h4><?php echo Model_Badge::badgeTitle($metric); ?> (<?php echo $date->format('d M Y'); ?>)</h4>
	<ul>
		<?php foreach ($this->country->presences as $presence) : ?>

			<?php $metricValue = $data['month'][$presence->id]->$metric; ?>

            <li>
                <span class="icon-circle icon-large traffic-light"
                      style="color: <?php echo $this->trafficLight()->color($metricValue, $metric); ?>;">
                </span>
                <?php echo $this->partial('partials/presence_inline.phtml',  array('presence' => $presence)); ?>
	            <?php if ($presence->isForTwitter()) : ?>
		            <span class="klout" title="Klout score: <?php echo $presence->klout_score; ?>"><?php echo round($presence->klout_score); ?></span>
	            <?php endif; ?>
                <span style="float:right;">
                    <span class="<?php echo $presence->sign_off ? 'icon-ok-sign': 'icon-remove-sign';?> icon-large"
                          title="Sign off"></span>
                    <span
                        class="<?php echo $presence->branding ? 'icon-ok-sign': 'icon-remove-sign';?> icon-large"
                        title="Branding Compliance"></span>
                </span>
            </li>

		<?php endforeach; ?>
	</ul>
	<?php else : ?>
		None assigned
	<?php endif; ?>
</div>
