<div class="country">
	<div class="close"><a href="#">Close</a></div>
	<h3><a href="<?php echo $this->url(array('action'=>'view', 'controller'=>'country', 'id'=>$this->country->id)); ?>"><?php echo $this->country->display_name; ?></a></h3>
	<?php if ($this->country->presences) : ?>
	<ul class="presence-list">
		<?php /** @var $presence Model_Presence */ ?>
		<?php foreach ($this->country->presences as $presence) : ?>

			<?php
			$kpiData = $presence->getKpiData();
			$metricValue = $kpiData[$this->metric];
			?>

            <li class="social-media box traffic-lights <?php echo $presence->type; ?>">
                <?php $sign = $presence->isForFacebook() ? 'icon-facebook-sign' : 'icon-twitter-sign'; ?>

                <a href="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>$presence->id)); ?>"
                   class="presence"
                   title="<?php echo $this->trafficLight()->label($metricValue, $this->metric); ?>">

                    <span class="<?php echo $sign; ?> icon-large front"></span>
                    <?php echo $presence->getLabel(); ?>
                    <span class="icon-circle icon-large back"
                          style="color: <?php echo $this->trafficLight()->color($metricValue, $this->metric); ?>;">
                    </span>

                </a>
            </li>

		<?php endforeach; ?>
	</ul>
	<?php else : ?>
		None assigned
	<?php endif; ?>
</div>
