<?php
/** @var Badge_Abstract[] $allBadges */
$allBadges = $this->badges;
$pdfLink = null;
if(file_exists(APPLICATION_PATH . '/../data/uploads/kpis.pdf')) {
    $pdfLink = $this->url() . 'data/uploads/kpis.pdf';
}
?>

<div class="row">
    <div class="small-24 large-5 columns homepage-title">
        <h2 class="page-title">Social Media Monitor</h2>
        <span class="help-text-toggle icon-question-sign icon-large">
            <div class="help-text">
                <p>Choose from Reach, Engagement, Quality or Overall to see the health of each country and SBU.</p>
            </div>
        </span>
    </div>
    <div class="small-24 large-19 columns">
        <div id="homepage-tabs">
            <dl class="tabs">
            <?php foreach($allBadges as $badge) : ?>
                <dd data-badge="<?php echo $badge->getName(); ?>" data-title="<?php echo $badge->getTitle(); ?>">
                    <a href="#<?php echo $badge->getName(); ?>"><?php echo $badge->getTitle(); ?></a>
                </dd>
            <?php endforeach; ?>
            </dl>
        </div>
    </div>
</div>

<div class="row">
    <div class="small-24 large-5 columns hide-for-small-down">
        <span class="help-text-toggle icon-question-sign icon-large">
            <div class="help-text">
                <p>Move the date slider to view the historic trend of the score for each country and SBU.</p>
            </div>
        </span>

        <div id="map-date" class="bd-btm" data-current-date="<?php echo $this->currentDate; ?>" data-day-range="<?php echo $this->dayRange; ?>">
            <h4>Date range</h4>
            <div class="date-range-text"></div>
            <div class="range-slider" data-slider="<?php echo $this->dayRange; ?>" data-options="start: 1; end: <?php echo $this->dayRange; ?>; step: 1">
                <span class="range-slider-handle" role="slider" tabindex="0"></span>
                <span class="range-slider-active-segment"></span>
                <input type="hidden">
            </div>
        </div>

        <?php foreach($allBadges as $badge): ?>
        <div class="badge-description" data-badge-name="<?php echo $badge->getName(); ?>">
            <?php echo $badge->getDescription(); ?>
        </div>
        <?php endforeach; ?>

        <?php if(count($this->smallCountries) > 0) : ?>
            <div class="small-country-list">
                <h4>Small Countries</h4>
                <ul class="country-list">
                    <?php foreach($this->smallCountries as $country) : /** @var Model_Country $country */ ?>
                        <li data-id="<?php echo $country->id; ?>" data-badge>
                            <a href="#"><?php echo $country->getName(); ?> <span data-badge-score></span></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
    <div class="small-24 large-14 columns">
        <div id="map">
            <span class="help-text-toggle icon-question-sign icon-large">
                <div class="help-text">
                    <p>Click on the map to select a country and preview the individual social media presences.</p>
                </div>
            </span>
            <div id="geo-map"></div>
        </div>
    </div>
    <div class="small-24 large-5 columns">
        <div id="country-stats">
            <div class="badge-small" data-country-id="0" data-badge data-score="<?php echo(round($this->totalScore)); ?>" data-color="<?php echo(Badge_Abstract::colorize($this->totalScore)); ?>">
                <h3>British Council around the web</h3>
                <div class="badge-score bd-btm">
                    <h4>Overall Score</h4>
                    <div class="score-value" data-badge-score></div>
                </div>
                <div class="bd-btm">
                    <div>
                        This is build up of the total score from all British Coundil presences around the world.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if(isset($this->groups) && count($this->groups) > 0): ?>
    <h2>SBUs</h2>
    <div class="row">
        <div class="small-24 large-23 large-centered columns">
            <div class="row">
                <?php
                /** @var Model_Group $group */
                foreach($this->groups as $group):
                    $presenceGroups = array();
                    foreach(NewModel_PresenceType::enumValues() as $type) {
                        $typePresences = $group->getPresencesByType($type);
                        if (count($typePresences) > 0) {
                            $presenceGroups[] = array(
                                'type' => $type,
                                'presences' => $typePresences
                            );
                        }
                    }
                ?>
                    <div class="small-24 large-8 columns">
                        <div class="badge-small" data-group-id="<?php echo $group->id ?>" data-badge>
                            <h3><a href="<?php echo $this->url(array('controller'=>'group', 'action'=>'view', 'id'=>$group->id)); ?>"><?php echo $group->display_name; ?></a></h3>
                            <div class="badge-score bd-btm">
                                <h4><span data-badge-title></span> Score</h4>
                                <div class="score-value" data-badge-score></div>
                                <div class="score-bar">
                                    <div data-badge-bar></div>
                                </div>
                            </div>
                            <div class="bd-btm badge-presences-buttons">
                                <ul class="small-block-grid-3">
                                    <li>
                                        <a href="#all">
                                            <h4>Presences</h4>
                                            <div class="score-value"><?php echo count($group->getPresences()) ?></div>
                                        </a>
                                    </li>
                                    <?php foreach ($presenceGroups as $pg) : $type = $pg['type']; /** @var $type NewModel_PresenceType */?>
                                        <li>
                                            <a href="#<?php echo $type->getValue(); ?>">
                                                <h4><?php echo $type->getTitle(); ?></h4>
                                                <div class="score-value"><?php echo count($pg['presences']); ?></div>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div class="hide-for-small-down">
                                <ul class="badge-presences" data-all-presences>
                                    <?php foreach($group->getPresences() as $presence) : /** @var $presence NewModel_Presence */ ?>
                                        <li>
                                            <a href="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>$presence->getId())); ?>">
                                                <span class="<?php echo $presence->getPresenceSign(); ?>"></span> <?php echo $presence->getHandle(); ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php foreach ($presenceGroups as $pg) : $type = $pg['type']; /** @var $type NewModel_PresenceType */ ?>
                                    <ul class="badge-presences" data-<?php echo $type->getValue(); ?>-presences>
                                        <?php foreach($pg['presences'] as $presence) : /** @var $presence NewModel_Presence */ ?>
                                            <li>
                                                <a href="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>$presence->getId())); ?>">
                                                    <span class="<?php echo $presence->getPresenceSign(); ?>"></span> <?php echo $presence->getHandle(); ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($pdfLink) : ?>
<div class="button-bc-bar pdflink">
    <div class="row bk-dark">
        <div class="small-24 columns" id="kpi-download">
            <p>These scores are derived from the organisation's social media Key Performance Indicators (KPIs).</p>
            <p>You can download a copy of the PDF that explains them here:</p>
            <ul class="button-group">
                <li><a href="<?php echo $pdfLink; ?>" target="_blank" title="Download KPIs PDF" class="button-bc">Download KPIs</a></li>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
    var mapArgs = <?php echo json_encode($this->mapArgs); ?>;
</script>
