<ul id="map-tabs" class="content-in-header tabs">
    <?php $first = true; foreach($this->metricOptions as $badge => $title) : ?>
        <li class="<?php if ($first) echo 'active';?>" data-val="<?php echo $badge; ?>"><?php echo ucfirst($title); ?></li>
    <?php $first = false; endforeach; ?>
</ul>

<div class="map-date">
    <input type="text" size="25" id="date-slider" disabled value="<?php echo $this->dateRangeString; ?>"
           data-current-date="<?php echo $this->currentDate; ?>" data-day-range="<?php echo $this->dayRange; ?>">
    <div id="slider" data-val="30"></div>
</div>

<div id="map-sidebar" class="">
    <div class="country"></div>
    <div id="instructions-desc" class="desc-box">
        <h3>Instructions</h3>
        <p>Choose from either Overall Score, Reach, Engagement or Quality to see the health of each country, SBU and region.</p>
        <p>Move the date slider to view the historic trend of the score for each country, SBU and region.</p>
        <p>Click on the map to select a country and preview the individual social media presences.</p>
    </div><?php
    foreach($this->badgeDescriptions as $badgeTitle => $badgeDesc) : ?>
        <div id="<?php echo $badgeTitle; ?>-desc" class="desc-box hide">
            <h3><?php echo ucfirst($badgeTitle); ?></h3>
            <p><?php echo $badgeDesc; ?></p>
        </div><?php
    endforeach; ?>

    <div class="loading"></div>
</div>
<div id="map">
	<div id="geo-map"></div>
    <div id="small-maps" class="grid justify">
        <?php foreach($this->smallMapData as $country) : ?>
            <div id="small-map-<?php echo $country->id; ?>"></div>
        <?php endforeach; ?>
    </div>
    <div id="group-map">
        <h3><?php
            $url = $this->gatekeeper()->filter('%url%', array('controller' => 'group'));
            if($url) : ?>
            <a href="<?php echo $url; ?>"><span class="<?php echo Model_Group::ICON_TYPE; ?>"></span> SBUs</a><?php
            endif; ?>
        </h3>
        <ul></ul>
    </div>
    <div id="region-map">
        <h3><?php
            $url = $this->gatekeeper()->filter('%url%', array('controller' => 'region'));
            if($url) : ?>
            <a href="<?php echo $url; ?>">
	        <?php endif; ?>
	        <span class="<?php echo Model_Region::ICON_TYPE; ?>"></span> Regions
	        <?php if($url) : ?>
            </a>
            <?php endif; ?>
        </h3>
        <ul></ul>
    </div>
</div>


<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	var mapData = <?php echo json_encode((object) $this->mapData); ?>;
    var smallMapData = <?php echo json_encode(array_values($this->smallMapData)); ?>;
    var groupData = <?php echo json_encode((object) $this->groupData); ?>;
    var regionData = <?php echo json_encode((object) $this->regionData); ?>;
</script>