<h2 class="page-title">Social Media Monitor</h2>

<div class="row">
    <div class="small-24 medium-8 columns">
        <p>Choose from either Overall, Reach, Engagement or Quality to see the health of each country and SBU.</p>
    </div>
    <div class="small-24 medium-8 columns">
        <p>Move the data slider to view the historic trend of the score for each country and SBU.</p>
    </div>
    <div class="small-24 medium-8 columns">
        <p>Click on a map to select a country and preview the individual social media presences.</p>
    </div>
</div>

<h2 data-badge-title></h2>
<div class="row">
    <div class="small-24 large-5 columns">
        <div class="row">
            <div class="small-12 large-24 columns">
                <?php
                /** @var Badge_Abstract $badge */
                foreach($this->badges as $badge): ?>
                    <div class="badge-description" data-badge-description="<?php echo $badge->getName(); ?>">
                        <?php echo $badge->getDescription(); ?>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="small-12 large-24 columns">
                <h4>Small Countries</h4>
                <ul>
                    <?php
                    /** @var Model_Country $country */
                    foreach($this->smallCountries as $country):
                        $badges = $country->getBadges(); ?>
                        <li><?php echo $country->getName(); ?> <span data-badge-score></span></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="small-24 large-14 columns">
        <div id="map"><div id="geo-map"></div></div>
    </div><?php
    /** @var Model_Country $country */
    $country = $this->countries[0];
    $badges = $country->getBadges();
    $presences = $country->getPresences(); ?>
    <div class="small-24 large-5 columns">
        <div class="badge-small"
             data-total="<?php echo round($badges['total']); ?>"
             data-reach="<?php echo round($badges['reach']); ?>"
             data-engagement="<?php echo round($badges['engagement']); ?>"
             data-quality="<?php echo round($badges['quality']); ?>"
             data-total-color="<?php echo $badges['total_color']; ?>"
             data-reach-color="<?php echo $badges['reach_color']; ?>"
             data-engagement-color="<?php echo $badges['engagement_color']; ?>"
             data-quality-color="<?php echo $badges['quality_color']; ?>">
            <h3><?php echo $country->display_name; ?></h3>
            <div class="badge-score bd-btm">
                <h4><span data-badge-title></span> Score</h4>
                <div class="score-value" data-badge-score>63%</div>
                <div class="score-bar"><div data-badge-bar></div></div>
            </div>
            <div class="bd-btm">
                <h4>Presences</h4>
                <div class="score-value"><?php echo count($presences);?></div>
            </div>
            <?php foreach(NewModel_PresenceType::toArray() as $name => $typeName) :
                /** @var NewModel_PresenceType $type */
                $type = NewModel_PresenceType::$name();
                $typePresences = $country->getPresencesByType($type);
                if(count($typePresences) > 0) : ?>
                    <div class="bd-btm">
                        <h4><?php echo $type->getTitle(); ?></h4>
                        <ul class="badge-presences">
                            <?php
                            /** @var NewModel_Presence $presence */
                            foreach($presences as $presence):
                                if($presence->getType() != $type) continue; ?>
                                <li>
                                    <span class="<?php echo $presence->getPresenceSign(); ?>"></span> <?php echo $presence->getName(); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif;
            endforeach; ?>
        </div>

    </div>
</div>

<div class="button-bc-bar">
    <div class="row">
        <div class="small-24 columns">
            <ul class="inline-list badge-buttons">
                <?php
                /** @var Badge_Abstract $badge */
                foreach($this->badges as $badge): ?>
                    <li><a href="#<?php echo $badge->getName(); ?>" class="button-bc"><?php echo $badge->getTitle(); ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<?php if(isset($this->groups) && count($this->groups) > 0): ?>
    <h2>SBUs</h2>
    <div class="row">
        <div class="small-24 large-23 large-centered columns">
            <div class="row">
                <?php
                /** @var Model_Group $group */
                foreach($this->groups as $group):
                    $badges = $group->getBadges(); ?>
                    <div class="small-24 large-8 columns">
                        <div class="badge-small"
                             data-total="<?php echo round($badges['total']); ?>"
                             data-reach="<?php echo round($badges['reach']); ?>"
                             data-engagement="<?php echo round($badges['engagement']); ?>"
                             data-quality="<?php echo round($badges['quality']); ?>"
                             data-total-color="<?php echo round($badges['total_color']); ?>"
                             data-reach-color="<?php echo round($badges['reach_color']); ?>"
                             data-engagement-color="<?php echo round($badges['engagement_color']); ?>"
                             data-quality-color="<?php echo round($badges['quality_color']); ?>">
                            <h3><?php echo $group->display_name; ?></h3>
                            <h4><span data-badge-title></span> Score</h4>
                            <div class="score-value" data-badge-score></div>
                            <div class="score-bar">
                                <div data-badge-bar></div>
                            </div>
                            <div class="row">
                                <div class="small-24 large-8 columns">
                                    <h4>Presences</h4>
                                    <div class="score-value">26</div>
                                </div>
                                <div class="small-24 large-8 columns">
                                    <h4>Twitter</h4>
                                    <div class="score-value">13</div>
                                </div>
                                <div class="small-24 large-8 columns">
                                    <h4>Facebook</h4>
                                    <div class="score-value">13</div>
                                </div>
                            </div>
                            <ul class="presence-list">
                                <?php foreach($group->presences as $presence): ?>
                                    <li><span class="<?php echo $presence->getPresenceSign(); ?>"></span> <?php echo $presence->getHandle(); ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<div id="badge-titles"
     data-total-title="<?php echo $this->badges['total']->getTitle(); ?>"
     data-quality-title="<?php echo $this->badges['quality']->getTitle(); ?>"
     data-reach-title="<?php echo $this->badges['reach']->getTitle(); ?>"
     data-engagement-title="<?php echo $this->badges['engagement']->getTitle(); ?>"></div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
    var mapData = <?php echo json_encode($this->mapData); ?>;
    var smallMapData = <?php echo json_encode($this->smallMapData); ?>;
    var groupData = <?php echo json_encode($this->groupData); ?>;
</script>