<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="baseUrl" content="<?php echo $this->baseUrl('/'); ?>">
	<title>British Council :: <?php echo strip_tags($this->title); ?></title>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/') . 'assets/img/favicon.ico';?>">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet">
	<?php
		echo $this->minifyHeadLink()
			->appendStylesheet('assets/fonts/proxima-nova-fontfacekit/stylesheet.css')
			->appendStylesheet('assets/lib/bootstrap/bootstrap.css')
			->appendStylesheet('assets/lib/tipsy/css/tipsy.css')
			->appendStylesheet('assets/css/svg.css')
			->appendStylesheet('assets/css/bc.css')
			->appendStylesheet('assets/css/uni-form.css')
			->appendStylesheet('assets/css/bc.uni-form.css')
			->appendStylesheet('assets/css/ui.daterangepicker.css')
//			->appendStylesheet('assets/lib/datatables/media/css/jquery.dataTables.css')
//			->appendStylesheet('assets/css/jquery.dataTables.custom.css')
			->appendStylesheet('assets/lib/farbtastic/farbtastic.css')
	?>
    <!--[if lte IE 8]>
    <link rel="stylesheet" media="print" href="assets/css/print.css" type="text/css" />
    <![endif]-->
</head>
<body class="<?php echo $this->bodyClass; ?>">
	<div id="wrapper">
		<header id="main-header">
			<div class="hold">

				<div id="nav-bar">
					<div id="nav">
						<div class="main">
                            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>" class="site-title-link"><div class="site-title"><span>British Council Social Media Monitor</span></div></a>
                            <?php
                                //if (Zend_Auth::getInstance()->hasIdentity()) :
                                    echo $this->navigation()->menu()->setPartial('partials/menu.phtml')->render();
                                //endif;
                            ?>
						</div>
						<div class="extra">
						    <?php
                                if (Zend_Auth::getInstance()->hasIdentity() && $this->user) {
	                                switch ($this->user->user_level) {
		                                case Model_User::USER_LEVEL_ADMIN:
		                                case Model_User::USER_LEVEL_MANAGER:
											$menu = $this->adminMenu;
										    break;
		                                case Model_User::USER_LEVEL_USER:
										default:
											$menu = $this->nonAdminMenu;
										    break;
						            }
                                    echo $this->navigation()->menu()->render($menu);
							    } else {
                                    echo $this->navigation()->menu()->render($this->nonUserMenu);
						        }
                            ?>
						</div>
					</div>
				</div>
                <div class="beta-tag">[ BETA ]</div>
				<div class="page-title <?php if ($this->subtitle) echo 'with-subtitle'; ?>">
					<?php if($this->titleImage) { echo $this->titleImage; } ?>
					<h1>
						<?php if ($this->titleIcon) : ?>
						<span class="<?php echo $this->titleIcon; ?> icon-large"></span>
						<?php endif; ?>
						<?php echo $this->title; ?>
						<?php if ($this->titleInfo) : ?>
						<a href="#" class="accordion-btn" data-id="title-info"><span class="icon-caret-down icon-small"></span></a>
						<?php endif; ?>
					</h1>
					<?php if($this->subtitle) { echo '<h2>'.$this->subtitle.'</h2>'; } ?>
				</div>
                <?php if(isset($this->titleInfo)) : ?>
                    <div id="title-info" class="accordion">
                        <dl>
                            <?php foreach($this->titleInfo as $k => $info) : ?>

                                <?php $value = $k == 'notes' ? '<p>'.$info->value.'</p>' : $info->value ; ?>
                                <dt><?php echo $info->title; ?>:</dt>
                                <dd><?php echo $value; ?></dd>

                            <?php endforeach; ?>
                        </dl>
                    </div>
                <?php endif; ?>
			</div>
		</header>
		<div id="content" class="clearfix">
			<?php echo $this->FlashMessages(); ?>
			<?php echo $this->layout()->content; ?>
		</div>
        <div id="footer">
            <?php echo $this->navigation()->menu()->setPartial('partials/footer-menu.phtml')->render(); ?>
        </div>
	</div>
	<div id="loader" class="dead"></div>

	<?php
	$scripts = array(
		array('link', 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'),
		array('link', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js'),
		array('code', 'var jsConfig = ' . json_encode($this->jsConfig) . ';'),
		array('code', 'var geochartMetrics = ' . json_encode($this->geochartMetrics) . ';'),
		array('link', 'assets/lib/d3/d3.v2.min.js'), //use preminified version to avoid error
		array('link', 'assets/lib/jquery/date.js'),
		array('link', 'assets/lib/jquery/daterangepicker.jQuery.js'),
		array('link', 'assets/lib/tipsy/js/jquery.tipsy.js'),
		array('link', 'assets/lib/datatables/media/js/jquery.dataTables.js'),
		array('link', 'assets/js/dataTables.filteringDelay.js'),
		array('link', 'assets/lib/jquery/uni-form.jquery.min.js'),
		array('link', 'assets/lib/farbtastic/farbtastic.js'),
		array('link', 'assets/js/plugins.js'),
		array('link', 'assets/lib/backbone/underscore.js'),
		array('link', 'assets/lib/bootstrap/bootstrap.js'),
		array('link', 'assets/js/datatables.js'),
		array('link', 'assets/js/charts.js'),
        array('link', 'assets/js/badges.js'),
		array('link', 'assets/js/geochart.js'),
		array('link', 'assets/js/main.js')
	);

	$debug = true; // enable this to print out the scripts individually, so you don't have to wait for minify to execute
	if ($debug) {
		foreach ($scripts as $type=>$script) {
			list($type, $s) = $script;
			if ($type == 'link') {
				if (strpos($s, 'http://') !== 0) {
					$s = $this->baseUrl($s);
				}
				echo '<script type="text/javascript" src="' . $s . '"></script>' . PHP_EOL;
			} else {
				echo '<script type="text/javascript">' . $s . '</script>' . PHP_EOL;
			}
		}
	} else {
		$minify = $this->minifyHeadScript();
		foreach ($scripts as $type=>$script) {
			list($type, $s) = $script;
			if ($type == 'link') {
				$minify->appendFile($s);
			} else {
				$minify->appendScript($s);
			}
		}
		echo $minify;
	}
	?>

	<script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-39877642-1', 'idea.pm');
        ga('send', 'pageview');

    </script>
</body>
</html>