<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="baseUrl" content="<?php echo $this->baseUrl('/'); ?>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<title><?php echo $this->clientName; ?> :: <?php echo strip_tags($this->pageTitle); ?></title>
    <link rel="shortcut icon" href="<?php echo $this->assetUrl('img/favicon.ico');?>"/>
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"/>
	<link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet"/>
	<link href="//cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css" rel="stylesheet"/>
	<link href="//cdn.datatables.net/fixedheader/3.1.1/css/fixedHeader.dataTables.min.css" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('fonts/proxima-nova-fontfacekit/stylesheet.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('lib/foundation/css/normalize.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('lib/foundation/css/foundation.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('lib/tipsy/css/tipsy.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/svg.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('lib/c3/css/c3.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/ui.daterangepicker.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('lib/farbtastic/farbtastic.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/font-awesome.min.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/multiselect.jQuery.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/jquery.dataTables.custom.css');?>" rel="stylesheet"/>
	<link href="<?php echo $this->assetUrl('css/social-monitor.css');?>" rel="stylesheet"/>

    <!--[if lte IE 8]>
    <link rel="stylesheet" media="print" href="<?php echo $this->assetUrl('css/print.css');?>" type="text/css" />
    <![endif]-->
    <script type="text/javascript" src="<?php echo $this->assetUrl('js/modernizr.min.js');?>"></script>
</head>
<body class="<?php echo $this->bodyClass; ?>">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1>
					<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>"></a>
				</h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
		</ul>

		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">
				<?php
					$this->navigation()->menu()->setPartial('partials/foundation-menu.phtml');
					if (Zend_Auth::getInstance()->hasIdentity() && $this->user) {
						switch ($this->user->user_level) {
							case Model_User::USER_LEVEL_ADMIN:
							case Model_User::USER_LEVEL_MANAGER:
								$menu = $this->adminMenu;
								break;
							case Model_User::USER_LEVEL_USER:
							default:
								$menu = $this->nonAdminMenu;
								break;
						}
						echo $this->navigation()->menu()->render($menu);
					} else {
						echo $this->navigation()->menu()->render($this->nonUserMenu);
					}
				?>
			</ul>

			<!-- Left Nav Section -->
			<ul class="left">
				<?php echo $this->navigation()->menu()->render(); ?>
			</ul>
		</section>
	</nav>
	<div id="feedback"><button><?php echo $this->translate()->trans('Base.layout.feedback-button'); ?></button></div>
	<div id="content" class="clearfix">
		<div class="row">
			<div class="small-24 columns">
				<?php echo $this->FlashMessages(); ?>
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</div>
	<?php echo $this->partial('partials/feedback-modal.phtml'); ?>
	<div id="footer">
		<?php echo $this->navigation()->menu()->setPartial('partials/footer-menu.phtml')->render(); ?>
	</div>
	<div id="loader" class="dead"></div>

	<?php
	$scripts = array(
		array('link', '//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'),
		array('link', '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js'),
		array('code', 'var jsConfig = ' . json_encode($this->jsConfig) . ';'),
		array('link', 'lib/d3/v3/d3.min.js'), //use preminified version to avoid error
		array('link', 'lib/c3/js/c3.js'),
		array('link', 'lib/jquery/date.js'),
		array('link', 'lib/jquery/daterangepicker.jQuery.js'),
		array('link', 'lib/jquery/multiselect.jQuery.js'),
		array('link', 'lib/tipsy/js/jquery.tipsy.js'),
		array('link', '//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js'),
		array('link', '//cdn.datatables.net/fixedheader/3.1.1/js/dataTables.fixedHeader.min.js'),
//		array('link', 'lib/datatables/media/js/jquery.dataTables.js'),
		array('link', 'js/dataTables.filteringDelay.js'),
		array('link', 'lib/farbtastic/farbtastic.js'),
		array('link', 'js/plugins.js'),
		array('link', 'lib/backbone/underscore.js'),
		array('link', 'lib/moment/moment.js'),
//		array('link', 'lib/bootstrap/bootstrap.js'),
		array('link', 'lib/foundation/js/foundation/foundation.js'),
		array('link', 'lib/foundation/js/foundation/foundation.topbar.js'),
		array('link', 'lib/foundation/js/foundation/foundation.tab.js'),
		array('link', 'lib/foundation/js/foundation/foundation.slider.js'),
		array('link', 'js/datatables.js'),
		array('link', 'js/new_charts.js'),
		array('link', 'js/home.js'),
		array('link', 'js/main.js')
	);

	$debug = true; // enable this to print out the scripts individually, so you don't have to wait for minify to execute
	if ($debug) {
		foreach ($scripts as $type=>$script) {
			list($type, $s) = $script;
			if ($type == 'link') {
				if ((strpos($s, 'http://') !== 0) && (substr($s, 0, 2) != '//')) {
					$s = $this->assetUrl($s);
				}
				echo '<script type="text/javascript" src="' . $s . '"></script>' . PHP_EOL;
			} else {
				echo '<script type="text/javascript">' . $s . '</script>' . PHP_EOL;
			}
		}
	} else {
		/** @var Zend_View_Helper_MinifyHeadScript $minify */
		$minify = $this->minifyHeadScript();
		foreach ($scripts as $type=>$script) {
			list($type, $s) = $script;
			if ($type == 'link') {
				$minify->appendFile($s);
			} else {
				$minify->appendScript($s);
			}
		}
		echo $minify;
	}
	?>
	<script>
		$(document).foundation();
	</script>
	<script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-39877642-1', 'socialmonitor.britishcouncil.net');
        ga('send', 'pageview');

    </script>
	<!-- <?php echo APPLICATION_ENV; ?> -->
</body>
</html>