<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>British Council :: <?php echo strip_tags($this->title); ?></title>
	<link rel="stylesheet" href="<?php echo $this->baseUrl('assets//fonts/proxima-nova-fontfacekit/stylesheet.css'); ?>">
	<link href="<?php echo $this->cacheBust('assets/lib/foundation/css/normalize.css'); ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->cacheBust('assets/lib/foundation/css/foundation.css'); ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->cacheBust('assets/lib/jquery/smoothness/jquery-ui-1.8.17.custom.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/uni-form.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/bc.uni-form.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/bc.css'); ?>" rel="stylesheet" type="text/css"/>
</head>
<body class="<?php echo $this->bodyClass; ?>">

<div class="row">
    <div class="small-24 medium-16 large-8 medium-centered columns">
        <div id="loginWrapper">
            <?php echo $this->FlashMessages(); ?>
            <nav class="top-bar" data-topbar role="navigation">
                <ul class="title-area">
                    <li class="name">
                        <h1>
                            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>">
                                <span>British Council Social Media Monitor</span>
                            </a>
                        </h1>
                    </li>
                </ul>
            </nav>
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>


</body>
</html>
