<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title><?php echo $this->clientName; ?> :: <?php echo strip_tags($this->pageTitle); ?></title>
	<link rel="shortcut icon" href="<?php echo $this->assetUrl('img/favicon.ico');?>"/>
	<link rel="stylesheet" href="<?php echo $this->assetUrl('fonts/proxima-nova-fontfacekit/stylesheet.css'); ?>">
	<link href="<?php echo $this->cacheBust('lib/foundation/css/normalize.css'); ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->cacheBust('lib/foundation/css/foundation.css'); ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->cacheBust('lib/jquery/smoothness/jquery-ui-1.8.17.custom.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('css/social-monitor.css'); ?>" rel="stylesheet" type="text/css"/>
	<?php echo $this->captcha()->generateScript(); ?>
</head>
<body class="<?php echo $this->bodyClass; ?>">

<div class="row">
    <?php echo $this->FlashMessages(); ?>
    <div class="small-24 medium-16 large-8 medium-centered columns">
        <div id="loginWrapper">
            <nav class="top-bar" data-topbar role="navigation">
                <ul class="title-area">
                    <li class="name">
                        <h1>
                            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>"></a>
                        </h1>
                        <h4><?php echo $this->translate()->trans('views.scripts.notabs.small-heading'); ?></h4>
                    </li>
                </ul>
            </nav>
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>

<!-- <?php echo APPLICATION_ENV; ?> -->
</body>
</html>
