<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>33D :: <?php echo strip_tags($this->title); ?></title>
	<link rel="stylesheet" href="<?php echo $this->baseUrl('assets//fonts/proxima-nova-fontfacekit/stylesheet.css'); ?>">
	<link href="<?php echo $this->cacheBust('assets/css/normalize.css'); ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->cacheBust('assets/lib/jquery/smoothness/jquery-ui-1.8.17.custom.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/ui-custom.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/uni-form.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/33d.uni-form.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->cacheBust('assets/css/33d.css'); ?>" rel="stylesheet" type="text/css"/>
</head>
<body class="<?php echo $this->bodyClass; ?>">

<div id="loginWrapper">
<?php echo $this->FlashMessages(); ?>
<?php echo $this->layout()->content; ?>
</div>

</body>
</html>
