<div class="content" id="statuses">
    <h2 class="page-title">Statuses</h2>

    <div class="statusesDisplay all">
        <?php
        $buttons = array();
        array_unshift($buttons, '<div id="search-table">Loading data...</div>');

        echo $this->partial('partials/button-bar.phtml', array('buttons' => $buttons, 'dark' => true));

        echo $this->partial('partials/daterange.phtml', array('dateRangeString' => $this->dateRangeString));

        foreach($this->queryOptions as $option) {
            echo $this->partial(
                'partials/multi-select-box.phtml',
                array(
                    'label' => $option['label'],
                    'queryParamName' => $option['name'],
                    'options' => $option['options']
                )
            );
        }

        ?>
        <div>
            <table>
                <thead>
                <tr>
                    <th class="message">Message</th>
                    <th class="date">Date</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
