<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

$buttons = array('<div id="search-table">' . $translator->trans('Global.loading-data') . '</div>');

?>
<div class="content" id="statuses">
    <h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

    <div class="statusesDisplay combined-statuses">
        <?php echo $this->partial('partials/button-bar.phtml', array('buttons' => $buttons, 'dark' => true)); ?>

        <div class="filters" style="display:none;"> <!-- show when data is returned -->
            <div class="date-filter-container">
                <?php echo $this->partial('partials/daterange.phtml', array('dateRangeString' => $this->dateRangeString)); ?>
                <label><?php echo $translator->trans('route.statuses.index.you-are-viewing'); ?></label>
            </div>
            <?php
            foreach ($this->queryOptions as $option) {
				if ($option['options']) {
					echo $this->partial(
						'partials/multi-select-box.phtml',
						array(
							'label' => $option['label'],
							'queryParamName' => $option['name'],
							'options' => $option['options']
						)
					);
				}
            }
            ?>
        </div>
        <div class="table-container">
            <table>
                <thead>
                <tr>
                    <th class="message"><?php echo $translator->trans('route.statuses.index.table-header.content'); ?></th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type='text/javascript'>
    var presences = <?php echo json_encode($this->presences); ?>;
</script>
