<?php
$bottomBar = array();
if ($this->canEdit) {
    $bottomBar = $this->gatekeeper()->filterAll(array(
            '<a class="button-bc" href="%url%">' . $this->translate()->trans('Global.cancel') .  '</a>' => array('controller'=>'index', 'action'=>'index'),
            //todo: reinstate this
//          '<a class="button-bc" href="%url%">Download as CSV</a>' => array('action'=>'download')
        ));
    $bottomBar[] = '<button type="submit" class="button-bc">' . $this->translate()->trans('Global.save') . '</button>';
}
$topBar = $bottomBar;
array_unshift($topBar, '<div id="search-table">'. $this->translate()->trans('Global.loading-data') . '</div>');
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<div class="row">
    <div class="small-24 medium-12 columns">
		<p><?php echo $this->translate()->trans('Domain.index.paragraph-1'); ?></p>
    </div>
    <div class="small-24 medium-12 columns">
        <p><?php echo $this->translate()->trans('Domain.index.paragraph-2'); ?></p>
    </div>
</div>

<form method="post" action="<?php echo $this->url(); ?>">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true)); ?>

	<table class="text dtable" id="domains">
		<thead>
			<tr>
				<th data-sort="auto"><?php $this->translate()->trans('Domain.table.header.domain'); ?></th>
				<th data-sort="numeric"><?php $this->translate()->trans('Domain.table.header.links'); ?></th>
				<th data-sort="checkbox"><?php $this->translate()->trans('Domain.table.header.relevant'); ?></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>

</form>