<h2 class="page-title">Domains</h2>
<p>This shows the list of all domains linked to by tweets or facebook statues. Click the links to see more usage information and the specific URLs.</p>
<p>You can say whether or not a domain belongs to the British Council by toggling the checkbox on the right, and clicking 'save'.
	Note that if you reorder the columns before saving, any changes will be lost.</p>

<?php
$buttons = array();
if ($this->canEdit) : ?>
		<?php $buttons = $this->gatekeeper()->filterAll(array(
			'<a class="button-bc" href="%url%">Cancel</a>' => array('action'=>'index')
		)); ?>
<?php endif; ?>
<form method="post" action="<?php echo $this->url(); ?>">

	<div class="button-bc-bar">
		<div class="row bk-dark">
			<div class="small-24 large-centered columns">
				<ul class="button-group">
					<li><div id="domain-search"><?php // search box will go in here ?></div></li>
<!--					<li><a class="button-bc" href="#">Download CSV</a></li>-->
					<?php foreach($buttons as $button): ?>
						<li><?php echo $button; ?></li>
					<?php endforeach; ?>
					<li><button formaction="submit" class="button-bc">Save</button></li>
				</ul>
			</div>
		</div>
	</div>

	<table class="text dtable" id="domains">
		<thead>
			<tr>
				<th data-sort="auto">Domain</th>
				<th data-sort="numeric">Links</th>
				<th data-sort="checkbox">British Council</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>

	<div class="button-bc-bar">
		<div class="row bk-dark">
			<div class="small-24 large-centered columns">
				<ul class="button-group">
<!--					<li><a class="button-bc" href="#">Download CSV</a></li>-->
					<?php foreach($buttons as $button): ?>
						<li><?php echo $button; ?></li>
					<?php endforeach; ?>
					<li><button formaction="submit" class="button-bc">Save</button></li>
				</ul>
			</div>
		</div>
	</div>

</form>