<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

$sites = $this->pluralise($translator->trans('route.domain.view.site.single'), count($this->links), $translator->trans('route.domain.view.site.plural'));
$statuses = $this->pluralise($translator->trans('route.domain.view.status.single'), $this->domain->getLinkCount(), $translator->trans('route.domain.view.status.plural'));
$summary = $translator->trans('route.domain.view.linked-to-from', ['%sites%' => $sites, '%statuses%' => $statuses]);
?>
<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<p><?php echo $summary; ?></p>
<?php foreach ($this->links as $link) : ?>
<div class="domain-link" data-domain-id="<?php echo $this->domain->id; ?>" data-url="<?php echo $link->url; ?>">
    <div class="link-title">
        <a href="#" class="toggle-expand"></a>
        <a href="<?php echo $link->url; ?>" target="_blank"><?php echo highlight($link->url, $this->domain->domain); ?> <span class="icon-external-link"></span></a>
        (<?php echo $this->pluralise('mention', count($link->statuses)); ?>)
    </div>
</div>
<?php endforeach; ?>

<?php
function highlight($url, $domain) {
	$text = $url;
	$pos = strpos($url, $domain);
	if ($pos >= 0) {
		$pos += strlen($domain) + 1;
		$text = substr($url, 0, $pos) . '<strong>' . substr($url, $pos) . '</strong>';
	}
	return $text;
}