<?php echo $this->render('partials/daterange.phtml'); ?>

<div id="charts" data-controller="search">
	<div id="legend">Legend:</div>
	<div class="chart" id="mentions" data-y-label="mentions"></div>
	<div class="chart" id="sentiment" data-y-label="sentiment"></div>
</div>

<div id="searches" class="lineSelector">
	<h3>Pages</h3>
	<table class="dtable">
		<thead>
		<tr>
			<th>Page</th>
			<th>Likes</th>
			<th>Last updated info</th>
			<th>Last fetched posts</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($this->pages as $page) : ?>
		<tr data-line-id="<?php echo BaseController::makeLineId(get_class($page), $page->id); ?>">
			<td><?php echo $page->name; ?></td>
			<td><?php echo $page->fan_count; ?></td>
			<td><?php echo $this->prettyDate($page->last_updated, 'Never'); ?></td>
			<td><?php echo $this->prettyDate($page->last_fetched, 'Never'); ?></td>
		</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<div id="posts" class="statusesDisplay">
	<div class="inner">
		<h3>Posts</h3>
		<table class="dtable">
			<thead>
			<tr>
				<th class="actor">Author</th>
				<th class="message">Message</th>
				<th class="comments">Cmnts</th>
				<th class="likes">Likes</th>
				<th class=""><abbr title="Sentiment">+/-</abbr></th>
				<th class="date">Date</th>
			</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>