<form method="post" action="<?php echo $this->url(); ?>" class="uniForm">

	<fieldset class="inlineLabels">
		<legend>Page details</legend>
		<div class="ctrlHolder">
			<label for="name" class="requiredField">
				Page username<span class="asteriskField">*</span>
			</label>
			<input name="username" id="name" type="text" value="<?php echo $this->editingPage->username; ?>"> 
			<p class="formHint">For www.facebook.com/<strong>platform</strong> the username is '<strong>platform</strong>'</p>
		</div>
		<div class="ctrlHolder checkbox">
			<p class="label">Sentiment analysis</p>
			<?php if ($this->campaign->analysis_quota) : ?>
			<ul class="blockLabels">
				<?php foreach (array(1 => 'Enabled', 0 => 'Disabled') as $val => $name) : ?>
				<li>
					<label class="radio"><input name="should_analyse" type="radio" value="<?php echo $val; ?>"
						<?php if ($this->editingPage->should_analyse == $val) echo 'checked'; ?>> <?php echo $name; ?>
					</label>
				</li>
				<?php endforeach; ?>
			</ul>
			<?php else : ?>
			Sentiment analysis is disabled for this campaign
			<?php endif; ?>
		</div>
	</fieldset>
	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', $this->gatekeeper()->fallbackUrlArgs(array('action'=>'index')), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>
