<?php
	$links = $this->gatekeeper()->filterAll(array(
		'<a class="button add" href="%url%">Add new</a>' => array('action' => 'new'),
		'<a class="button" href="%url%">Compare</a>' => array('action' => 'compare')
	));
	if ($links) :
?>
<p>
	<?php echo implode('', $links); ?>
</p>
<?php endif; ?>

<table class="text">
	<tr>
		<th>Page</th>
		<th>Likes</th>
		<th><abbr title="Posts in month to date">MTD</abbr></th>
		<th><abbr title="Posts in past 24 hours">24h</abbr></th>
		<th>Last updated info</th>
		<th>Last fetched posts</th>
		<th>Facebook page</th>
		<?php if ($this->campaign->analysis_quota) : ?>
		<th>Sentiment analysis</th>
		<?php endif; ?>
		<th></th>
	</tr>
	<?php foreach ($this->pages as $page) : ?>
	<tr>
		<td><?php echo $this->gatekeeper()->filter('<a href="%url%">' . $page->name . '</a>', array('action'=>'view', 'id'=>$page->id)); ?></td>
		<td><?php echo $page->fan_count; ?></td>
		<td><?php echo $page->posts_this_month; ?></td>
		<td><?php echo $page->posts_last_24_hours; ?></td>
		<td><?php echo $this->prettyDate($page->last_updated, 'Never'); ?></td>
		<td><?php echo $this->prettyDate($page->last_fetched, 'Never'); ?></td>
		<td><a href="<?php echo $page->page_url; ?>"><img src="<?php echo $page->pic_square; ?>"></a></td>
		<?php if ($this->campaign->analysis_quota) : ?>
		<td><?php echo $page->should_analyse ? 'Enabled' : 'Disabled'; ?></td>
		<?php endif; ?>
		<td>
			<?php
				$links = $this->gatekeeper()->filterAll(array(
					'<a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$page->id),
					'<a href="%url%">Update info</a>' => array('action'=>'update', 'id'=>$page->id),
					'<a href="%url%" class="autoConfirm">Delete</a>' => array('action'=>'delete', 'id'=>$page->id)
				));
				echo implode(' | ', $links);
			?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>