<?php echo $this->render('partials/daterange.phtml'); ?>

<div id="charts" data-controller="facebook" data-controller-label="facebook page" data-default-line-id="<?php echo $this->defaultLineId; ?>">
	<div id="legend">Legend:</div>
	<div class="chart" id="mentions" data-y-label="posts"></div>
	<div class="chart" id="sentiment" data-y-label="sentiment"></div>
</div>

<div id="topics" class="lineSelector">
	<h3>Topics</h3>
	<table class="dtable">
		<thead>
			<tr>
				<th class="topic">Topic</th>
				<th class="mentions">Mentions</th>
				<th class="sentiment"><abbr title="Sentiment">+/-</abbr></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>
<div id="posts" class="statusesDisplay">
	<div class="inner">
		<h3>Posts</h3>
		<table class="dtable">
			<thead>
				<tr>
					<th class="actor">Author</th>
					<th class="message">Message</th>
					<th class="comments">Cmnts</th>
					<th class="likes">Likes</th>
					<th class=""><abbr title="Sentiment">+/-</abbr></th>
					<th class="date">Date</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>