<h2 class="page-title">Edit All SBUs</h2>

<form method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-all-groups">

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 columns">
                <ul class="button-group">
                    <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'group', 'action'=>'index'), null, true); ?></li>
                    <li><button type="submit" class="button-bc">Save</button></li>
                </ul>
            </div>
        </div>
    </div>

    <table class="text dtable standard" id="all-groups">
        <thead>
            <tr>
                <th data-name="name" data-sort="forminput">Display name</th>
                <th data-name="audience" data-sort="fuzzy-numeric">Audience Size</th>
            </tr>
        </thead>
        <tbody>
        <?php /** @var $group Model_Group */ ?>
        <?php foreach ($this->groups as $group) : ?>
            <tr>
                <td>
                    <input name="<?php echo $group->id; ?>_display_name" value="<?php echo htmlspecialchars($group->display_name); ?>" class="textInput"
                           type="text" id="<?php echo $group->id; ?>_display_name">
                </td>
                <td>
                    <input name="<?php echo $group->id; ?>_audience" value="<?php echo htmlspecialchars($group->audience); ?>" class="textInput"
                           type="text" id="<?php echo $group->id; ?>_audience">
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 columns">
                <ul class="button-group">
                    <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'group', 'action'=>'index'), null, true); ?></li>
                    <li><button type="submit" class="button-bc">Save</button></li>
                </ul>
            </div>
        </div>
    </div>
</form>

