<?php
$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a class="button-bc" href="%url%">Cancel</a>', array('controller'=>'group', 'action'=>'index'), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">Save</button>';
$topBar = $bottomBar;
array_unshift($topBar, '<div id="search-table"></div>');
?>

<h2 class="page-title">Edit All SBUs</h2>

<form class="edit-all" method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-all-groups">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true)); ?>

    <table class="text dtable standard" id="all-groups">
        <thead>
            <tr>
                <th data-name="name" data-sort="forminput">Display name</th>
                <th data-name="audience" data-sort="fuzzy-numeric">Audience Size</th>
            </tr>
        </thead>
        <tbody>
        <?php /** @var $group Model_Group */ ?>
        <?php foreach ($this->groups as $group) : ?>
            <tr>
                <td>
                    <input name="<?php echo $group->id; ?>_display_name" value="<?php echo htmlspecialchars($group->display_name); ?>" class="textInput"
                           type="text" id="<?php echo $group->id; ?>_display_name">
                </td>
                <td>
                    <input name="<?php echo $group->id; ?>_audience" value="<?php echo htmlspecialchars($group->audience); ?>" class="textInput"
                           type="text" id="<?php echo $group->id; ?>_audience">
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>
</form>

