<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

/** @var Model_Group $sbu */
$sbu = $this->editingGroup;
$presences = $sbu->getPresences();
$topBar = array();
$bottomBar = array();
$cancelArgs = array('controller'=>'group');
if ($this->isNew) {
	$cancelArgs['action'] = 'index';
} else {
	$cancelArgs['action'] = 'view';
	$cancelArgs['id'] = $sbu->id;
	$topBar = $this->gatekeeper()->filterAll(array(
		'<a class="button-bc button-view" href="%url%">' . $translator->trans('Group.buttons.view-sbu') . '</a>' => array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id),
		'<a class="button-bc button-manage" href="%url%">' . $translator->trans('Group.buttons.manage-presences') . '</a>' => array('controller'=>'group', 'action'=>'manage', 'id'=>$sbu->id),
		'<a class="button-bc button-delete" href="%url%">' . $translator->trans('Global.delete') . '</a>' => array('controller'=>'group', 'action'=>'delete', 'id'=>$sbu->id)
	));
}
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">' . $translator->trans('Global.cancel') . '</a>', $cancelArgs, null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">' . $translator->trans('Global.save') . '</button>';
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<?php
if ($topBar) {
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));
}
?>

<form class="edit" method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-group">

	<fieldset class="inlineLabels">
        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <label for="display_name" class="requiredField">
					<?php echo $translator->trans('Global.display-name') ?><span class="asteriskField">*</span>
                </label>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <input name="display_name" value="<?php echo htmlspecialchars($sbu->display_name); ?>" class="textInput"
                       type="text" id="display_name">
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <label for="audience">
					<?php echo $translator->trans('Global.available-audience-size') ?>
                </label>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <input name="audience" value="<?php echo htmlspecialchars($sbu->audience); ?>" class="textInput"
                       type="text" id="audience">
            </div>
        </div>

	</fieldset>

    <input name="campaign_type" value="<?php echo Model_Group::$campaignType; ?>" type="hidden" id="campaign_type">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>
</form>

