<?php
/** @var Model_Group $sbu */
$sbu = $this->editingGroup;
$presences = $sbu->getPresences();
$topBar = $this->gatekeeper()->filterAll(array(
	'<a class="button-bc button-view" href="%url%">View SBU</a>' => array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id),
	'<a class="button-bc button-manage" href="%url%">Manage Presences</a>' => array('controller'=>'group', 'action'=>'manage', 'id'=>$sbu->id),
    '<a class="button-bc button-delete" href="%url%">Delete</a>' => array('controller'=>'group', 'action'=>'delete', 'id'=>$sbu->id)
));
$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">Save</button>';
?>

<h2 class="page-title"><?php echo $this->title; ?></h2>

<?php
if ($topBar && $this->showButtons) {
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));
}
?>

<form method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-group">

	<fieldset class="inlineLabels">
        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <label for="display_name" class="requiredField">
                    Display name<span class="asteriskField">*</span>
                </label>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <input name="display_name" value="<?php echo htmlspecialchars($sbu->display_name); ?>" class="textInput"
                       type="text" id="display_name">
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <label for="audience">
                    Available audience size
                </label>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <input name="audience" value="<?php echo htmlspecialchars($sbu->audience); ?>" class="textInput"
                       type="text" id="audience">
            </div>
        </div>

	</fieldset>

    <input name="campaign_type" value="<?php echo Model_Group::$campaignType; ?>" type="hidden" id="campaign_type">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>
</form>

