<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button add" href="%url%"><span class="icon-plus icon-large"></span> Add new</a>' => array('action'=>'new'),
    '<a class="button" href="%url%"><span class="icon-edit icon-large"></span> Edit All</a>' => array('action'=>'edit-all'),
    '<a class="button download" href="%url%"><span class="icon-download"></span> Download CSV</a>' => array('action' => 'download')
));
?>

<?php if ($buttons) : ?>
    <p>
        <?php echo implode('', $buttons); ?>
    </p>
<?php endif; ?>

<?php if (!$this->groups) : ?>
<h3>No groups found</h3>
<?php else : ?>
<table class="text dtable standard" id="all-countries">
	<thead>
		<tr><?php
            foreach($this->tableHeaders as $headers): ?>
                <th <?php
                if(isset($headers->name)) echo "data-name='$headers->name'";
                if(isset($headers->desc)) echo "title='$headers->desc'";
                if(isset($headers->sort)) echo "data-sort='$headers->sort'";
                if(isset($headers->width)) echo "data-width='$headers->width'"; ?> ><?php
                if(isset($headers->title)) echo $headers->title; ?>
                </th><?php
            endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php /** @var $group Model_Group */ ?>
		<?php foreach ($this->groups as $group) : ?>
		<tr>
			<?php $presences = $group->getPresences(); ?>
			<td>
				<?php $url = $this->gatekeeper()->filter('%url%', array('action'=>'view', 'id'=>$group->id)); if ($url) : ?>
					<a href="<?php echo $url; ?>"><?php echo $group->display_name; ?></a>
				<?php else : ?>
					<?php echo $group->display_name; ?>
				<?php endif; ?>
			</td>
            <td><?php echo $this->badgeData[$group->id]->total_rank; ?></td>
            <td><?php echo round($this->badgeData[$group->id]->total, 1); ?></td>
            <td><?php echo number_format($group->audience); ?></td>
			<?php if ($presences == true) : ?>
                <?php $kpiData = $group->getKpiAverages(); foreach ($this->tableMetrics as $key=>$label) : $value = $kpiData[$key]; ?>
                    <td>
                        <span class="icon-circle icon-large pull-left" data-value="<?php echo $value; ?>" style="color:<?php echo $this->trafficLight()->color($value, $key); ?>;"></span>
                        <?php echo $this->trafficLight()->label($value, $key); ?>
                    </td>
                <?php endforeach; ?>
                <td>
                    <ul class="entity-list">
                        <?php foreach($presences as $presence) : ?>
                            <li>
                                <?php echo $this->partial('partials/presence_inline.phtml',  array('presence' => $presence)); ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </td>
			<?php else : ?>
			    <?php foreach ($this->tableMetrics as $key=>$label) : ?>
                    <td>-</td>
                <?php endforeach; ?>
			    <td>-</td>
			<?php endif; ?>
			<td>
				<?php
					$actions = $this->gatekeeper()->filterAll(array(
						'- <a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$group->id),
						'- <a href="%url%">Presences</a>' => array('action'=>'manage', 'id'=>$group->id),
						'- <a href="%url%" class="autoConfirm">Delete</a>' => array('action'=>'delete', 'id'=>$group->id)
					));
					echo implode('<br />', $actions);
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table><?php

    $buttons = $this->gatekeeper()->filterAll(array(
        '<a class="button download" href="%url%"><span class="icon-download"></span> Download CSV</a>' => array('action' => 'download'),
    ));


    if ($buttons) : ?>
        <p><?php
        echo implode('', $buttons); ?>
        </p><?php
    endif;

endif; ?>