<?php
$sbu = $this->group;

$topBar = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc button-view" href="%url%">' . $this->translate('Group.buttons.view-sbu') . '</a>' => array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id),
    '<a class="button-bc button-edit" href="%url%">' . $this->translate('Group.buttons.edit-sbu') . '</a>' => array('controller'=>'group', 'action'=>'edit', 'id'=>$sbu->id)
));

$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">' . $this->translate('Global.cancel') . '</a>', array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">' . $this->translate('Global.save') . '</button>';
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<form class="management" method="post" action="<?php echo $this->url(); ?>" novalidate id="manage-group">
    <?php
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));

	echo $this->partial('partials/assign-presences.phtml', array(
			'owner' => $sbu,
			'presences' => $this->presences,
		));

    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true));
    ?>
</form>

