<?php
/** @var \Symfony\Component\Translation\Translator $translator */
use Volnix\CSRF\CSRF;

$translator = $this->translate();

$sbu = $this->group;

$topBar = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc button-view" href="%url%">' . $translator->trans('buttons.group.view') . '</a>' => array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id),
    '<a class="button-bc button-edit" href="%url%">' . $translator->trans('buttons.group.edit') . '</a>' => array('controller'=>'group', 'action'=>'edit', 'id'=>$sbu->id)
));

$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">' . $translator->trans('buttons.common.cancel') . '</a>', array('controller'=>'group', 'action'=>'view', 'id'=>$sbu->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">' . $translator->trans('buttons.common.save') . '</button>';
?>

<h2 class="page-title"><?php echo htmlspecialchars($this->pageTitle); ?></h2>

<form class="management" method="post" action="<?php echo $this->url(); ?>" novalidate id="manage-group">
	<?php echo CSRF::getHiddenInputString(); ?>
    <?php
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));

	echo $this->partial('partials/assign-presences.phtml', array(
			'owner' => $sbu,
			'presences' => $this->presences,
		));

    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true));
    ?>
</form>

