<?php
    /** @var Model_Group $group */
    $group = $this->group;
    $presences = array_map(function($c) {
        /** @var Model_Presence $c */
        return $c->getName();
    }, $group->getPresences());
    $presenceCount = count($presences);
?>

<div class="row">
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2><?php echo $this->translate()->trans('Global.presences')?>: <?php echo $presenceCount; ?></h2>
            <p><?php echo implode(", ", $presences) ?>.</p>
        </section>
    </div>
</div>