<?php
/** @var Model_Group $group */
$group = $this->campaign;
$presences = $group->getPresences();
?>

<h4 class="campaign-name">
    <?php echo $group->display_name; ?>
</h4>

<h4><?php echo $this->translate()->trans('route.group.view.info-panel.presences', ['%count%' => count($presences)]); ?></h4>
<?php if ($presences) : ?>
    <ul class="entity-list">
        <?php foreach ($presences as $p) : ?>
            <?php echo $this->partial('partials/presence_box.phtml', array('presence'=>$p)); ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
