<?php
$buttons = $this->gatekeeper()->filterAll(array(
	'<a class="button" href="%url%"><span class="icon-edit icon-large"></span> Edit Group</a>' => array('action'=>'edit', 'id'=>$this->group->id),
	'<a class="button" href="%url%"><span class="icon-tasks icon-large"></span> Manage Presences</a>' => array('action'=>'manage', 'id'=>$this->group->id)
));
?>


<div class="row">
    <div class="small-24 large-12 xlarge-8 columns">

        <?php //echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons)); ?>

        <?php echo $this->partial("partials/badges.phtml", array("badges" => $this->badgePartial)); ?>

    </div>
    <div class="small-24 large-12 xlarge-16 columns">

        <div class="show-for-medium-up">

            <div id="pickers" class="bd-btm">
                <?php echo $this->render('partials/metricpicker.phtml'); ?>
                <?php echo $this->render('partials/daterange.phtml'); ?>
            </div>

            <div class="chart-description"></div>

            <div id="new-chart" data-controller="group" data-id="<?php echo $this->group->id; ?>"></div>

        </div>

    </div>
</div>