<h2 class="page-title">Edit region</h2>
<?php
$buttons = $this->gatekeeper()->filterAll(array(
	'<a class="button-bc button-view" href="%url%">View Region</a>' => array('controller'=>'region', 'action'=>'view', 'id'=>$this->editingRegion->id),
	'<a class="button-bc button-manage" href="%url%">Manage Countries</a>' => array('controller'=>'region', 'action'=>'manage', 'id'=>$this->editingRegion->id),
    '<a class="button-bc button-delete" href="%url%">Delete</a>' => array('controller'=>'region', 'action'=>'delete', 'id'=>$this->editingRegion->id)
));
if ($buttons && $this->showButtons) {
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true));
}
?>

<form method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-region">
    <div class="row">
        <div class="small-24 medium-8 large-8 columns">
            <label for="display_name" class="requiredField">
                Display name<span class="asteriskField">*</span>
            </label>
        </div>
        <div class="small-24 medium-16 large-16 end columns">
            <input name="display_name" value="<?php echo htmlspecialchars($this->editingRegion->display_name); ?>" class="textInput" type="text" id="display_name">
        </div>
    </div>

    <?php if(!empty($this->presences)) : ?>
    <fieldset class="inlineLabels">
        <h2>Presence details</h2>
        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <p>These presences will be automatically added to this region:</p>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <ul id="added-presences">
                    <?php
                    foreach ($this->presences as $presence) {
                        echo $this->partial('partials/presence_box.phtml', array('presence'=>$presence, 'varname'=>'p'));
                    }
                    ?>
                </ul>
            </div>
        </div>
    </fieldset>
    <?php endif; ?>

    <input name="campaign_type" value="<?php echo Model_Region::$campaignType; ?>" type="hidden" id="campaign_type">

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 large-centered columns">
                <ul class="button-group">
                        <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true); ?></li>
                        <li><input type="submit" value="Save" class="primaryAction button-bc"></li>
                </ul>
            </div>
        </div>
    </div>
</form>

