<?php
$buttons = $this->gatekeeper()->filterAll(array(
	'<a class="button-bc" href="%url%"><span class="icon-eye-open icon-large"></span> View Region</a>' => array('controller'=>'region', 'action'=>'view', 'id'=>$this->editingRegion->id),
	'<a class="button-bc" href="%url%"><span class="icon-tasks icon-large"></span> Manage Countries</a>' => array('controller'=>'region', 'action'=>'manage', 'id'=>$this->editingRegion->id),
    '<a href="%url%" class="button-bc remove"><span class="icon-remove icon-large"></span> Delete</a>' => array('controller'=>'region', 'action'=>'delete', 'id'=>$this->editingRegion->id)
));
if ($buttons && $this->showButtons) :
?>
    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 large-centered columns">
                <ul class="button-group">
                    <?php foreach($buttons as $button): ?>
                        <li><?php echo $button; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>

<form method="post" action="<?php echo $this->url(); ?>" class="uniForm" novalidate id="edit-region">

	<fieldset class="inlineLabels">
		<h2 class="page-title">Region details</h2>
        <div class="ctrlHolder">
            <label for="display_name" class="requiredField">
                Display name<span class="asteriskField">*</span>
            </label>
            <input name="display_name" value="<?php echo htmlspecialchars($this->editingRegion->display_name); ?>"
                   type="text" id="display_name">
        </div>
        <!--<div class="ctrlHolder">
            <label for="audience">
                Available audience size
            </label>
            <input name="audience" value="<?php echo htmlspecialchars($this->editingRegion->audience); ?>" class="textInput"
                   type="text" id="audience">
        </div>-->
	</fieldset>

    <?php if(!empty($this->presences)) : ?>
    <fieldset class="inlineLabels">
        <h2 class="page-title">Presence details</h2>
        <div class="ctrlHolder">
            <p>These presences will be automatically added to this region:</p>
            <ul id="added-presences">
	            <?php
	            foreach ($this->presences as $presence) {
		            echo $this->partial('partials/presence_box.phtml', array('presence'=>$presence, 'varname'=>'p'));
	            }
	            ?>
            </ul>
        </div>
    </fieldset>
    <?php endif; ?>

    <input name="campaign_type" value="<?php echo Model_Region::$campaignType; ?>" type="hidden" id="campaign_type">

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 large-centered columns">
                <ul class="button-group">
                        <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true); ?></li>
                        <li><input type="submit" value="Save" class="primaryAction button-bc"></li>
                </ul>
            </div>
        </div>
    </div>
</form>

