<div class="button-bc-bar">
    <div class="row bk-dark">
        <div class="small-24 columns">
            <ul class="button-group">
                <li id="search-table"><?php // search box will go in here ?></li>
            </ul>
        </div>
    </div>
</div>

<form method="post" action="<?php echo $this->url(); ?>" class="uniForm" novalidate id="edit-all-regions">

    <table class="text dtable" id="all-regions">
        <thead>
            <tr>
                <th data-name="name">Display name</th>
            </tr>
        </thead>
        <tbody>
        <?php /** @var $region Model_Region */ ?>
        <?php foreach ($this->regions as $region) : ?>
            <tr>
                <td>
                    <input
                        name="<?php echo $region->id; ?>_display_name"
                        value="<?php echo htmlspecialchars($region->display_name); ?>"
                        type="text"
                        id="<?php echo $region->id; ?>_display_name"
                    />
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 large-centered columns">
                <ul class="button-group">
                        <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true); ?></li>
                        <li><input type="submit" value="Save" class="primaryAction button-bc"></li>
                </ul>
            </div>
        </div>
    </div>
</form>

