<?php
$buttons = $this->gatekeeper()->filterAll(array(
	'<a class="button" href="%url%"><span class="icon-eye-open icon-large"></span> View Region</a>' => array('controller'=>'region', 'action'=>'view', 'id'=>$this->editingRegion->id),
	'<a class="button" href="%url%"><span class="icon-tasks icon-large"></span> Manage Presences</a>' => array('controller'=>'region', 'action'=>'manage', 'id'=>$this->editingRegion->id),
    '<a href="%url%" class="button remove"><span class="icon-remove icon-large"></span> Delete</a>' => array('controller'=>'region', 'action'=>'delete', 'id'=>$this->editingRegion->id)
));
if ($buttons && $this->showButtons) :
?>
<p>
	<?php echo implode('', $buttons); ?>
</p>
<?php endif; ?>

<form method="post" action="<?php echo $this->url(); ?>" class="uniForm" novalidate id="edit-region">

	<fieldset class="inlineLabels">
		<legend>Region details</legend>
        <div class="ctrlHolder">
            <label for="display_name" class="requiredField">
                Display name<span class="asteriskField">*</span>
            </label>
            <input name="display_name" value="<?php echo htmlspecialchars($this->editingRegion->display_name); ?>" class="textInput"
                   type="text" id="display_name">
        </div>
        <div class="ctrlHolder">
            <label for="audience">
                Available audience size
            </label>
            <input name="audience" value="<?php echo htmlspecialchars($this->editingRegion->audience); ?>" class="textInput"
                   type="text" id="audience">
        </div>
	</fieldset>

    <?php if(!empty($this->presences)) : ?>
    <fieldset class="inlineLabels">
        <legend>Presence details</legend>
        <div class="ctrlHolder">
            <p>These presences will be automatically added to this region:</p>
            <ul id="added-presences">
	            <?php
	            foreach ($this->presences as $presence) {
		            echo $this->partial('partials/presence_box.phtml', array('presence'=>$presence, 'varname'=>'p'));
	            }
	            ?>
            </ul>
        </div>
    </fieldset>
    <?php endif; ?>

    <input name="is_country" value="2" type="hidden" id="is_country">

	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>

