<?php
$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc button-save">Save</button>';
$topBar = $bottomBar;
array_unshift($topBar, '<div id="search-table"></div>');
?>

<h2 class="page-title">Edit All Regions</h2>

<form method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-all-regions">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true)); ?>

    <table class="text dtable" id="all-regions">
        <thead>
            <tr>
                <th data-name="name">Display name</th>
            </tr>
        </thead>
        <tbody>
        <?php /** @var $region Model_Region */ ?>
        <?php foreach ($this->regions as $region) : ?>
            <tr>
                <td>
                    <input
                        name="<?php echo $region->id; ?>_display_name"
                        value="<?php echo htmlspecialchars($region->display_name); ?>"
                        type="text"
                        id="<?php echo $region->id; ?>_display_name"
                    />
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>
</form>

