<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button add" href="%url%"><span class="icon-plus icon-large"></span> Add new</a>' => array('action'=>'new'),
    '<a class="button" href="%url%"><span class="icon-edit icon-large"></span> Edit All</a>' => array('action'=>'edit-all'),
    '<a class="button download" href="%url%"><span class="icon-download"></span> Download CSV</a>' => array('action' => 'download')
));
?>

<?php if ($buttons) : ?>
    <p>
        <?php echo implode('', $buttons); ?>
    </p>
<?php endif; ?>

<?php if (!$this->regions) : ?>
<h3>No regions found</h3>
<?php else : ?>
<table class="text dtable standard" id="all-countries">
	<thead>
		<tr><?php
            foreach($this->tableHeaders as $headers): ?>
                <th <?php
                if(isset($headers->name)) echo "data-name='$headers->name'";
                if(isset($headers->desc)) echo "title='$headers->desc'";
                if(isset($headers->sort)) echo "data-sort='$headers->sort'";
                if(isset($headers->width)) echo "data-width='$headers->width'"; ?> ><?php
                if(isset($headers->title)) echo $headers->title; ?>
                </th><?php
            endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php /** @var $region Model_Region */ ?>
		<?php foreach ($this->regions as $region) : ?>
		<tr>
			<?php
                $presences = $region->getPresences();
                $countries = $region->getCountries();
            ?>
			<td>
				<?php $url = $this->gatekeeper()->filter('%url%', array('action'=>'view', 'id'=>$region->id)); if ($url) : ?>
					<a href="<?php echo $url; ?>"><?php echo $region->display_name; ?></a>
				<?php else : ?>
					<?php echo $region->display_name; ?>
				<?php endif; ?>
			</td>
            <td>
                <?php echo (array_key_exists($region->id, $this->badgeData) ? $this->badgeData[$region->id]->total_rank : 'N/A'); ?>
            </td>
            <td>
                <?php echo (array_key_exists($region->id, $this->badgeData) ? round($this->badgeData[$region->id]->total, 1) : 'N/A'); ?>
            </td>
            <td><?php echo number_format($region->audience); ?></td>
            <td><?php
                $perc = $region->getPercentTargetAudience();
                echo is_null($perc) ? 'N/A' : round($perc, 2).'%';
            ?></td>
            <?php
                $kpiData = $region->getKpiAverages();
                foreach ($this->tableMetrics as $key=>$label) :
                    $value = array_key_exists($key, $kpiData) ? $kpiData[$key] : '-';
            ?>
                    <td>
                        <?php if ($value == '-'): ?>
                            -
                        <?php else: ?>
                            <span class="icon-circle icon-large pull-left" data-value="<?php echo $value; ?>" style="color:<?php echo $this->trafficLight()->color($value, $key); ?>;"></span>
                            <?php echo $this->trafficLight()->label($value, $key); ?>
                        <?php endif; ?>
                    </td>
            <?php endforeach; ?>
            <td class="countries">
                <span class="entity-list-toggle"><?php echo(count($countries)); ?> countries</span>
                <ul class="entity-list">
                    <?php foreach($countries as $country) : ?>
                        <li>
                            <?php echo $this->partial('partials/country_inline.phtml',  array('country' => $country)); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
			<td>
				<?php
					$actions = $this->gatekeeper()->filterAll(array(
						'- <a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$region->id),
						'- <a href="%url%">Presences</a>' => array('action'=>'manage', 'id'=>$region->id),
						'- <a href="%url%" class="autoConfirm">Delete</a>' => array('action'=>'delete', 'id'=>$region->id)
					));
					echo implode('<br />', $actions);
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table><?php

    $buttons = $this->gatekeeper()->filterAll(array(
        '<a class="button download" href="%url%"><span class="icon-download"></span> Download CSV</a>' => array('action' => 'download'),
    ));


    if ($buttons) : ?>
        <p><?php
        echo implode('', $buttons); ?>
        </p><?php
    endif;

endif; ?>