<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc" href="%url%">Add New</a>' => array('action'=>'new'),
    '<a class="button-bc" href="%url%">Edit All</a>' => array('action'=>'edit-all'),
    '<a class="button-bc" href="%url%">Download CSV</a>' => array('action' => 'download')
));
array_unshift($buttons, '<div id="search-table">Loading data...</div>');

echo '<h2 class="page-title">Regions</h2>';

echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true));

echo $this->partial("partials/index-table.phtml", array(
    "tableHeaders" => $this->tableHeaders,
    "tableId" => "all-regions",
    "rows" => $this->regions,
    'emptyText' => 'No regions found',
    'sortCol' => $this->sortCol
));
