<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc" href="%url%">Add new</a>' => array('action'=>'new'),
    '<a class="button-bc" href="%url%">Edit All</a>' => array('action'=>'edit-all'),
    '<a class="button-bc" href="%url%">Download CSV</a>' => array('action' => 'download')
));
?>

<h2 class="page-title">Regions</h2>

<div class="button-bc-bar">
    <div class="row bk-dark">
        <div class="small-24 columns">
            <ul class="button-group">
                <li id="search-table"><?php // search box will go in here ?></li>
                <?php foreach($buttons as $button) : ?>
                    <li><?php echo $button; ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<?php echo $this->partial("partials/index-table.phtml", array(
    "tableHeaders" => $this->tableHeaders,
    "tableId" => "all-regions",
    "rows" => $this->regions,
    'emptyText' => 'No regions found',
    'sortCol' => $this->sortCol
)); ?>