<?php
$region = $this->region;

$topBar = $this->gatekeeper()->filterAll(array(
        '<a class="button-bc button-view" href="%url%">'.$this->translate("Region.buttons.view-region").'</a>' => array('controller'=>'region', 'action'=>'view', 'id'=>$region->id),
        '<a class="button-bc button-edit" href="%url%">'.$this->translate("Region.buttons.edit-region").'</a>' => array('controller'=>'region', 'action'=>'edit', 'id'=>$region->id)
    ));

$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">'.$this->translate("Global.cancel").'</a>', array('controller'=>'region', 'action'=>'view', 'id'=>$region->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">'.$this->translate("Global.save").'</button>';
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<form class="management" method="post" action="<?php echo $this->url(); ?>" novalidate id="manage-region">

	<?php
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));

	echo $this->partial('partials/assign-countries.phtml', array(
			'owner'=>$region,
			'allCountries'=>$this->allCountries
		));

    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true));
    ?>
</form>

