<form method="post" action="<?php echo $this->url(); ?>" class="uniForm management" novalidate id="manage-region">

	<?php
	echo $this->partial('partials/assign-countries.phtml', array(
			'owner'=>$this->region,
			'allCountries'=>$this->allCountries
		));
	?>

	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', array('controller'=>'region', 'action'=>'index'), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>

