<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

$countriesCount = count($this->countries);
$countries = array_map(function($c) {
	/** @var Model_Country $c */
	return $c->getName();
}, $this->countries);

$presences = array_map(function($c) {
	/** @var Model_Country $c */
	return $c->getName();
}, $this->region->getPresences());
$presenceCount = count($presences);
?>

<div class="row">
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2><?php echo $translator->trans('route.region.report.countries.header', ['%count%' => $countriesCount]); ?></h2>
            <p><?php echo htmlspecialchars(implode(", ", $countries))?>.</p>
        </section>
    </div>
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2><?php echo $translator->trans('route.region.report.presences.header', ['%count%' => $presenceCount]); ?></h2>
            <p><?php echo htmlspecialchars(implode(", ", $presences))?>.</p>
        </section>
    </div>
</div>