<?php
/** @var Model_Region $region */
$region = $this->campaign;
$presences = $region->getPresences();
$countries = $region->getCountries();
?>

<h4 class="campaign-name">
    <?php echo $region->display_name; ?>
</h4>

<h4><?php echo $this->translate()->trans('Global.countries') ?>: <?php echo count($countries); ?></h4>
<?php if ($countries) : ?>
<ul class="entity-list">
    <?php foreach ($countries as $c) : ?>
        <?php echo $this->partial('partials/country_box.phtml', array('country'=>$c)); ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<h4><?php echo $this->translate()->trans('Global.presences') ?>: <?php echo count($presences); ?></h4>
<?php if ($presences) : ?>
    <ul class="entity-list">
        <?php foreach ($presences as $p) : ?>
            <?php echo $this->partial('partials/presence_box.phtml', array('presence'=>$p)); ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
