<?php //print_r($this->presence); ?>
<div id="pickers">
	<?php echo $this->render('partials/metricpicker.phtml'); ?>
	<?php echo $this->render('partials/daterange.phtml'); ?>
</div>

<?php
    $links = $this->gatekeeper()->filterAll(array(
        '<a class="button add" href="%url%"><span class="icon-plus"></span>  Create Group</a>' => array('controller'=>'group','action' => 'new', 'presences'=>implode(',', array_keys($this->compareData))),
    ), null, true);
    if ($links) {
        echo '<div class="buttons">' . implode('', $links) . '</div>';
    }
?>

<?php if (empty($this->compareData)) : ?>

    <h3>No presences found</h3>

<?php else : ?>

    <div id="charts" data-controller="presence" data-controller-label="presence">
        <?php
        $currentId = 1;
        foreach($this->compareData as $data) :
        ?>
	    <div class="presence-charts">
		    <div class="presence <?php echo $data->presence->type; ?>"><?php echo $data->presence->label; if ($data->presence->label != $data->presence->handle) { echo ' (' . $data->presence->handle . ')'; } ?></div>
            <?php
	        foreach ($data->graphs as $graph) {
                $graph->id = $currentId++;
                $this->graph = $graph;
                echo $this->render('partials/chart.phtml');
            }
	        ?>
		</div>
        <?php endforeach; ?>
    </div>

	<h3>Scores for the last 30 days:</h3>

    <table class="text">

        <tr>
            <th>Handle</th>
            <?php foreach ($this->tableMetrics as $key=>$label) : ?>
                <th><?php echo $label; ?></th>
            <?php endforeach; ?>
        </tr>

        <?php foreach($this->compareData as $data) : $presence = $data->presence?>
            <tr>
                <td>
                    <div class="presence <?php echo $presence->type; ?>">
                        <?php echo $this->gatekeeper()->filter('<a href="%url%">' . $presence->handle . '</a>', array('controller'=>'presence', 'action'=>'view', 'id'=>$presence->id)); ?>
                        <a href="<?php echo $presence->page_url; ?>" target="_blank" class="icon external"></a>
                    </div>
                </td>
                <?php $kpiData = $presence->getKpiData(); foreach ($this->tableMetrics as $key=>$label) : $value = $kpiData[$key]; ?>
                    <td>
                        <span class="icon-circle icon-large pull-left" data-value="<?php echo $value; ?>" style="color:<?php echo $this->trafficLight()->color($value, $key); ?>;"></span>
                        <?php echo $this->trafficLight()->label($value, $key); ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>

    </table>

<?php endif; ?>
