<?php
/** @var Model_Presence $presence */
$presence = $this->presence;
/** @var Enum_PresenceType[] $types */
$types = $this->types;
/** @var Model_User $user */
$user = $this->user;

$topBar = $this->gatekeeper()->filterAll(array(
    '<a href="%url%" class="button-bc button-view">View</a>' => array('action'=>'view', 'id'=>$presence->id),
    '<a href="%url%" class="button-bc button-delete">Delete</a>' => array('action'=>'delete', 'id'=>$presence->id)
));
$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'presence', 'action'=>'view', 'id'=>$presence->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc button-save">Save</button>';
?>

<h2 class="page-title"><?php echo $this->title; ?></h2>

<?php
if ($topBar && $this->showButtons) {
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));
}
?>

<form class="edit" method="post" action="<?php echo $this->url(); ?>">

	<fieldset class="inlineLabels">
        <div class="row">
            <div class="small-24 medium-6 large-4 columns">
                <p class="label">Type<span class="asteriskField">*</span></p>
            </div>
            <div class="small-24 medium-18 large-20 end columns">
                <ul class="blockLabels">
                    <?php foreach ($types as $val) :
                        $requiresAccessToken = $val->requiresAccessToken() && !$user->getAccessToken($val);
                        $title = $val->getTitle(); ?>
                    <li>
                        <label class="radio withFormHint"><input name="type" type="radio" value="<?php echo $val->getValue(); ?>"
                            <?php if ($presence->type == $val) echo 'checked'; ?>
                            <?php if (!$this->editType || $requiresAccessToken) echo 'disabled'; ?>>
                            <?php echo $title; ?>
                        </label><span class="formHint"><?php echo $requiresAccessToken ? "(Please connect your account to {$title})": ""; ?></span>
                        <?php if (!$this->editType && ($presence->type == $val)) : ?>
                            <input type="hidden" value="<?php echo $val->getValue(); ?>" name="type">
                        <?php endif; ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-6 large-4 columns">
                <label for="handle" class="requiredField">
                    Handle<span class="asteriskField">*</span>
                </label>
            </div>
            <div class="small-24 medium-8 large-8 columns">
                <input name="handle" id="handle" type="text" value="<?php echo $presence->handle; ?>">
            </div>
            <div class="small-24 medium-10 large-12 end columns">
                <p class="formHint">
                    For www.facebook.com/<strong>platform</strong> or www.twitter.com/<strong>platform</strong> the handle is '<strong>platform</strong>'<br />
                    For facebook pages without vanity URLs, the handle is the long number in the URL, eg www.facebook.com/pages/My-Facebook-Page/<strong>012345678901234</strong>
                </p>
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-6 large-4 columns">
                <label for="size">
                    Size
                </label>
            </div>
            <div class="small-24 medium-8 large-8 columns">
                <select name="size" id="size">
                    <?php foreach(Model_Presence::getSizes() as $value => $label) :
                        $selected = ($this->isNew ? '' : ($value == $presence->getSize() ? "selected" : "")); ?>
                        <option value="<?php echo $value; ?>" <?php echo $selected; ?>><?php echo $label; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="small-24 medium-10 large-12 end columns">
                <p class="formHint">
                    Size will affect the weighting of a presence when calculating the target for its popularity.<br/>
                    Size will only affect presences that belong to SBU.<br/>
                    Large presences in an SBU will take a larger share of the SBU's target population, Medium presences a smaller share, and Small presences an even smaller share.
                </p>
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-6 large-4 columns">
                <p class="label">Signed Off</p>
            </div>
            <div class="small-24 medium-18 large-20 end columns">
                <ul class="blockLabels">
                    <li>
                        <label class="radio"><input name="sign_off" type="radio" value="0"
                                <?php if ($presence->sign_off < 1) echo 'checked'; ?>> No
                        </label>
                    </li>
                    <li>
                        <label class="radio"><input name="sign_off" type="radio" value="1"
                                <?php if ($presence->sign_off > 0) echo 'checked'; ?>> Yes
                        </label>
                    </li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="small-24 medium-6 large-4 columns">
                <p class="label">Branding</p>
            </div>
            <div class="small-24 medium-18 large-20 end columns">
                <ul class="blockLabels">
                    <li>
                        <label class="radio"><input name="branding" type="radio" value="0"
                                <?php if ($presence->branding < 1) echo 'checked'; ?>> No
                        </label>
                    </li>
                    <li>
                        <label class="radio"><input name="branding" type="radio" value="1"
                                <?php if ($presence->branding > 0) echo 'checked'; ?>> Yes
                        </label>
                    </li>
                </ul>
            </div>
        </div>

	</fieldset>

    <?php if (!$this->editType && $presence->getType()->requiresAccessToken()) : ?>
    <fieldset>
        <div clas="row">
            <div class="columns small-24">
                <h2>Access Token</h2>
                <p>This type of presence requires an access token to fetch data.</p>
                <?php if ($presence->getUser()) : ?>
                    <p>This presence is currently using the access token from the following user: <strong><?php $presence->getUser()->name; ?></strong></p>
                <?php else : ?>
                    <p>This presence does not currently have an access token and so cannot be fetched.</p>
                <?php endif; ?>

                <?php if ($user->getAccessToken($presence->getType())) :
                    $accessButton = $this->gatekeeper()->filter('<a href="%url%" class="button-bc inline">Use your access token</a>', array('controller'=>'presence', 'action'=>'assign', 'id'=>$presence->id), null, true);?>
                    <p><?php echo $accessButton; ?></p>
                <?php endif; ?>

            </div>
        </div>
    </fieldset>
    <?php endif; ?>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>
</form>