<form method="post" action="<?php echo $this->url(); ?>" class="uniForm">

	<fieldset class="inlineLabels">
		<legend>Presence details</legend>
		<div class="ctrlHolder checkbox">
			<p class="label">Type<span class="asteriskField">*</span></p>
			<ul class="blockLabels">
				<?php foreach ($this->types as $val => $name) : ?>
				<li>
					<label class="radio"><input name="type" type="radio" value="<?php echo $val; ?>"
						<?php if ($this->presence->type == $val) echo 'checked'; ?>
                        <?php if (!$this->editType) echo 'disabled'; ?>> <?php echo $name; ?>
					</label>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="ctrlHolder">
			<label for="handle" class="requiredField">
				Handle<span class="asteriskField">*</span>
			</label>
			<input name="handle" id="handle" type="text" value="<?php echo $this->presence->handle; ?>">
			<p class="formHint">For www.facebook.com/<strong>platform</strong> or www.twitter.com/<strong>platform</strong> the handle is '<strong>platform</strong>'</p>
		</div>
<!--        <div class="ctrlHolder">-->
<!--            <label for="group" class="requiredField">-->
<!--                Campaign<span class="asteriskField">*</span>-->
<!--            </label>-->
<!--            <select name="campaign_id" id="group">-->
<!--               --><?php //foreach($this->campaigns as $group) : ?>
<!--                    <option value="--><?php //echo $group->id; ?><!--" --><?php //if($group->id == $this->editingPage->campaign_id) echo 'selected'; ?><!-- >--><?php //echo $group->display_name; ?><!--</option>-->
<!--                --><?php //endforeach; ?>
<!--            </select>-->
<!--        </div>-->
	</fieldset>
    <input type="hidden" value="<?php $this->type; ?>">
	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', $this->gatekeeper()->fallbackUrlArgs(array('action'=>'index')), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>