<?php
/** @var NewModel_Presence $presence */
$presence = $this->presence;
/** @var NewModel_PresenceType[] $types */
$types = $this->types;
$buttons = $this->gatekeeper()->filterAll(array(
    '<a href="%url%" class="button remove"><span class="icon-remove icon-large"></span> Delete</a>' => array('action'=>'delete', 'id'=>$presence->id)
));
if ($buttons && $this->showButtons) :
    ?>
    <p>
        <?php echo implode('', $buttons); ?>
    </p>
<?php endif; ?>


<form method="post" action="<?php echo $this->url(); ?>" class="uniForm">

	<fieldset class="inlineLabels">
		<legend>Presence details</legend>
		<div class="ctrlHolder checkbox">
			<p class="label">Type<span class="asteriskField">*</span></p>
			<ul class="blockLabels">
				<?php foreach ($types as $val) : ?>
				<li>
					<label class="radio"><input name="type" type="radio" value="<?php echo $val->getValue(); ?>"
						<?php if ($presence->type == $val) echo 'checked'; ?>
                        <?php if (!$this->editType) echo 'disabled'; ?>> <?php echo $val->getTitle(); ?>
					</label>
                    <?php if (!$this->editType && ($presence->type == $val)) : ?>
                        <input type="hidden" value="<?php echo $val->getValue(); ?>" name="type">
                    <?php endif; ?>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="ctrlHolder">
			<label for="handle" class="requiredField">
				Handle<span class="asteriskField">*</span>
			</label>
			<input name="handle" id="handle" type="text" value="<?php echo $presence->handle; ?>">
			<p class="formHint">
				For www.facebook.com/<strong>platform</strong> or www.twitter.com/<strong>platform</strong> the handle is '<strong>platform</strong>'<br />
				For facebook pages without vanity URLs, the handle is the long number in the URL, eg www.facebook.com/pages/My-Facebook-Page/<strong>012345678901234</strong>
			</p>
		</div>

        <div class="ctrlHolder">
            <p class="label">Signed Off</p>
            <?php $name = "sign_off"; ?>

            <ul class="blockLabels">
                <li>
                    <label class="radio"><input name="sign_off" type="radio" value="0"
                            <?php if ($presence->sign_off < 1) echo 'checked'; ?>> No
                    </label>
                </li>
                <li>
                    <label class="radio"><input name="sign_off" type="radio" value="1"
                            <?php if ($presence->sign_off > 0) echo 'checked'; ?>> Yes
                    </label>
                </li>
            </ul>
        </div>

        <div class="ctrlHolder">
            <p class="label">Branding</p>
            <?php $name = "branding"; ?>
            <ul class="blockLabels">
                    <li>
                        <label class="radio"><input name="branding" type="radio" value="0"
                                <?php if ($presence->branding < 1) echo 'checked'; ?>> No
                        </label>
                    </li>
                    <li>
                        <label class="radio"><input name="branding" type="radio" value="1"
                                <?php if ($presence->branding > 0) echo 'checked'; ?>> Yes
                        </label>
                    </li>
            </ul>
        </div>


<!--        <div class="ctrlHolder">-->
<!--            <label for="group" class="requiredField">-->
<!--                Campaign<span class="asteriskField">*</span>-->
<!--            </label>-->
<!--            <select name="campaign_id" id="group">-->
<!--               --><?php //foreach($this->campaigns as $group) : ?>
<!--                    <option value="--><?php //echo $group->id; ?><!--" --><?php //if($group->id == $this->editingPage->campaign_id) echo 'selected'; ?><!-- >--><?php //echo $group->display_name; ?><!--</option>-->
<!--                --><?php //endforeach; ?>
<!--            </select>-->
<!--        </div>-->
	</fieldset>
	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', $this->gatekeeper()->fallbackUrlArgs(array('action'=>'index')), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>