<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc" href="%url%">Add New</a>' => array('action'=>'new'),
    '<a class="button-bc" href="%url%">Download CSV</a>' => array('action'=>'download'),
));
array_unshift($buttons, '<span id="filter-presence-type"></span>');
array_unshift($buttons, '<span id="filter-region"></span>');
array_unshift($buttons, '<div id="search-table">Loading data...</div>');

echo '<h2 class="page-title">Presences</h2>';

echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true));

echo $this->partial("partials/new-index-table.phtml", array(
    "tableHeaders" => $this->tableHeaders,
    "tableId" => "all-presences",
    "rows" => $this->rows,
    'emptyText' => 'No presences found',
    'sortCol' => $this->sortCol
));
