<?php
$buttons = array(
	'<a class="button-bc" href="%url%">Add New</a>' => array('action' => 'new')
);
if ($this->rows) {
	$buttons['<a class="button-bc" href="%url%">Download CSV</a>'] = array('action' => 'download');
}
$buttons = $this->gatekeeper()->filterAll($buttons);
if ($this->rows) {
	array_unshift($buttons, '<span id="filter-presence-type"></span>');
	array_unshift($buttons, '<span id="filter-region"></span>');
	array_unshift($buttons, '<div id="search-table">Loading data...</div>');
}
?>

<h2 class="page-title">Presences</h2>

<?php if (!$this->rows) : ?>
	<h3 class="empty-table">No presences found</h3>
	<?php echo $this->partial('partials/button-bar.phtml', array('buttons' => $buttons, 'dark' => true)); ?>
<?php else :
	echo $this->partial('partials/button-bar.phtml', array('buttons' => $buttons, 'dark' => true));

	echo $this->partial("partials/new-index-table.phtml", array(
		"tableHeaders" => $this->tableHeaders,
		"tableId" => "all-presences",
		"rows" => $this->rows,
		'sortCol' => $this->sortCol
	));
endif;