<div class="row">
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2>Additional Info</h2>
            <p>This is a <?php echo $this->presence->getType()->getTitle(); ?> presence</p>
            <?php if ($this->presence->isForFacebook()) : ?>
                <p>Yesterday's Facebook Engagement score: <?php echo $this->presence->facebook_engagement; ?></p>
                <p>Monthly Average Facebook Engagement score: <?php echo $this->presence->getMetricValue('facebook_engagement'); ?></p>
            <?php elseif ($this->presence->isForTwitter()) : ?>
                <p>Yesterday's Klout score: <?php echo $this->presence->klout_score; ?></p>
                <p>Monthly Average Klout score: <?php echo $this->presence->getMetricValue('klout_score'); ?></p>
            <?php endif; ?>
            <?php if ($this->owner) : ?>
                <p>This presence contributes to the statistics for <?php echo $this->owner->display_name; ?></p>
                <p>The target audience size is <?php echo number_format($this->presence->getTargetAudience()); ?></p>
                <p>The current audience size is <?php echo number_format($this->presence->getCurrentAudience()); ?></p>
            <?php endif; ?>
        </section>
    </div>
</div>