<div class="row">
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2>Additional Info</h2>
            <h3>Countries: 18</h3>
            <p>Albania  Armenia  Azerbaijan  Bosnia and Herzegovina  Croatia  Estonia  Georgia  Israel  Kazakhstan  Kosovo  Lithuania  Macedonia, the Former Yugoslav Republic of  Montenegro  Russian Federation  Serbia  Turkey  Ukraine  Uzbekistan</p>
        </section>
    </div>
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h3>Presences: 32</h3>
            <p>@alBritish  @amBritish  @azBritish  BritishCouncilAlbania  Brit-ishCouncilArmenia  BritishCouncilAzerbaijan  BritishCouncilBos-niaandHerzegovina  BritishCouncilCroatia  BritishCouncilEstonia  BritishCouncilGeorgia  BritishCouncilIsrael  BritishCouncilKazakhstan  BritishCouncilKosovo  BritishCouncilLithuania  BritishCouncilMacedo-nia  BritishCouncilMontenegro  BritishCouncilRussia  BritishCouncilS-erbia  BritishCouncilTurkey  BritishCouncilUkraine  BritishCouncilUz-bekistan  @eeBritish  @geBritish  @hrBritish  @ilBritish  @ksBritish  @mkBritish  OblaAirTeMesojmeAnglishten  @rsBritish  @ruBritish  @trBritish  @uaBritish</p>
        </section>
    </div>
</div>