<?php //print_r($this->presence); ?>

<div id="pickers">
	<?php echo $this->render('partials/daterange.phtml'); ?>
</div>

<div id="share-box"><span class="link">Link to this page</span></div>

<div class="presence <?php echo $this->presence->type; ?>">
	<a href="<?php echo $this->presence->page_url; ?>" target="_blank"><?php echo $this->presence->page_url; ?></a>
</div>
<p>Info last updated: <?php echo $this->prettyDate($this->presence->last_updated, 'Never'); ?></p>
<p>Statuses last updated: <?php echo $this->prettyDate($this->presence->last_fetched, 'Never'); ?></p>

<div id="charts" data-controller="presence" data-controller-label="presence">
	<?php
	$currentId = 1;
	foreach ($this->graphs as $graph) {
		$graph->id = $currentId++;
		$graph->presence_id = $this->presence->id;
		$this->graph = $graph;
		echo $this->render('partials/chart.phtml');
	}
	?>
</div>

<div id="statuses" class="statusesDisplay <?php echo $this->presence->type; ?>" data-presence-id="<?php echo $this->presence->id; ?>">
	<div class="inner">
		<h3>Statuses</h3>
		<table>
			<thead>
				<tr>
				<?php if ($this->presence->isForFacebook()) : ?>
					<th class="user">User</th>
					<th class="message">Message</th>
					<th class="response">Response</th>
					<th class="date">Date</th>
				<?php else : ?>
					<th class="message">Message</th>
					<th class="date">Date</th>
				<?php endif; ?>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>
