<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button-bc button-edit" href="%url%">'.$this->translate()->trans('Presence.buttons.edit-presence').'</a>' => array('action'=>'edit', 'id'=>$this->presence->id),
    '<a class="button-bc button-delete" href="%url%"></span>'.$this->translate()->trans('Presence.buttons.delete-presence').'</a>' => array('action'=>'delete', 'id'=>$this->presence->id),
    '<a id="report-download" class="button-bc button-download" href="%url%" data-href="%url%"></span>'.$this->translate()->trans('Global.download-report').'</a>' => array('action'=>'download-report', 'id'=>$this->presence->id),
));
/** @var Model_Presence $presence */
$presence = $this->presence;
$presenceType = $presence->getType()->getTitle();
$owner = $presence->getOwner();
$ownerUrl = null;
$targetSize = $presence->getTargetAudience();
$currentSize = $presence->getPopularity();
$timeToTarget = $presence->getTargetAudienceDate();
if ($owner) {
    $ownerController = strtolower(substr(get_class($owner), 6));
    $ownerUrl = $this->url(array('controller'=>$ownerController, 'action'=>'view', 'id'=>$owner->id));
}
$sizeDiff = $targetSize - $currentSize;
$requiredRates = array();
if ($sizeDiff > 0) {
    //get the different targets (best, good, bad)
    $scores = array(
        'best' => BaseController::getOption('achieve_audience_best'),
        'good' => BaseController::getOption('achieve_audience_good'),
        'bad' => BaseController::getOption('achieve_audience_bad')
    );

    $daysPerMonth = 365/12;
    foreach ($scores as $key=>$score) {
        $rate = $sizeDiff/($daysPerMonth*$score);
        //what rates are required to meet the different targets
        if ($rate > 0) {
            $requiredRates[] = array(
                'type' => $key,
                'rate' => round($rate, 1),
                'date' => date('F Y', strtotime('now +' . $score . ' months'))
            );
        }
    }
}
?>

<div class="row">
	<div class="small-24 large-12 xlarge-8 columns">

        <div class="model-header bd-btm">
            <a href="<?php echo $presence->page_url; ?>" target="_blank"><span class="page-icon white-background <?php echo $presence->getPresenceSign(); ?>"></span></a>
            <div class="picker">
                <label for="presence-switcher">Presence:</label>
                <select id="presence-switcher" data-url-template="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>'the_id')); ?>">
                    <?php foreach ($this->allPresences as $type=>$presences) : ?>
                        <optgroup label="<?php echo $type; ?>">
                            <?php foreach ($presences as $p) : ?>
                            <option value="<?php echo $p->id; ?>" <?php if ($p->id == $presence->id) { echo 'selected'; } ?>><?php echo $p->name . ' (' . $p->handle . ')'; ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

		<?php echo $this->partial("partials/badges.phtml", array("badges" => $this->badgePartial, 'titles'=>true, 'showMetrics' => true)); ?>
	</div>

	<div class="small-24 large-12 xlarge-16 columns">

        <dl class="tabs" data-tab id="model-tabs">
            <dd class="active"><a href="#chart"><?php echo $this->translate()->trans('Global.charts'); ?></a></dd>
            <dd><a href="#info"><?php echo $this->translate()->trans('Global.info'); ?></a></dd>
            <dd><a href="#statuses"><?php echo $this->translate()->trans('Global.statuses'); ?></a></dd>
        </dl>
        <div class="tabs-content" id="model-tabs-content">
            <div class="content active" id="chart">
                <div class="show-for-medium-up">
                    <div id="pickers">
                        <?php echo $this->render('partials/chart-picker.phtml'); ?>
                        <?php echo $this->render('partials/daterange.phtml'); ?>
                    </div>

                    <div class="chart-description"></div>

                    <div id="new-chart" data-controller="presence" data-id="<?php echo $presence->getId(); ?>"></div>
                    <div id="new-chart-values"></div>
                </div>
                <div class="hide-for-medium-up">
                    <p><?php echo $this->translate()->trans('Campaign.view.charts-unavailable'); ?></p>
                </div>
            </div>
            <div class="content" id="info">
                <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons)); ?>
                <h4 class="presence-name">
                    <?php if ($presence->image_url) : ?>
                    <img src="<?php echo $presence->image_url; ?>" />
                    <?php endif; ?>
                    <?php echo $presence->getName(); ?>
                </h4>
				<?php
					$type = strtolower($presenceType);
					$typeLink = "<a href=\"{$presence->page_url}\" target=\"_blank\">{$type} <span class=\"icon-external-link\"></span></a>";
				?>
				<p><?php echo $this->translate()->trans('Presence.view.info.presence-type', ['%type%' => $typeLink]); ?></p>
				<?php if ($presence->isForTwitter()) : ?>
					<p><?php echo $this->translate()->trans('Presence.view.info.twitter.score', ['%score%' => $presence->klout_score]); ?></p>
					<p><?php echo $this->translate()->trans('Presence.view.info.twitter.average-score', ['%score%' => $presence->getMetricValue('klout_score')]); ?></p>
				<?php else : ?>
					<p><?php echo $this->translate()->trans('Presence.view.info.presence.score', ['%type%' => $presenceType, '%score%' => $presence->getEngagementScore()->getScore()]); ?></p>
					<p><?php echo $this->translate()->trans('Presence.view.info.presence.average-score', ['%type%' => $presenceType, '%score%' => $presence->getEngagementScore(true)->getScore()]); ?></p>
				<?php endif; ?>
                <?php if ($ownerUrl) : ?>
					<?php $ownerLink = "<a href=\"{$ownerUrl}\">{$owner->display_name}</a>"; ?>
					<p><?php echo $this->translate()->trans('Presence.view.info.owner-name', ['%link%' => $ownerLink]); ?></p>
                    <p><?php echo $this->translate()->trans('Presence.view.info.target-audience', ['%size%' => number_format($targetSize)]); ?></p>
                    <p><?php echo $this->translate()->trans('Presence.view.info.current-audience', ['%size%' => number_format($currentSize)]); ?></p>
                    <?php if ($requiredRates) : ?>
                        <?php if ($timeToTarget) : ?>
                        <p><?php echo $this->translate()->trans('Presence.view.info.time-to-target', ['%date%' => $timeToTarget->format('F Y')]); ?></p>
                        <?php endif; ?>
                        <p><?php echo $this->translate()->trans('Presence.view.info.daily-gains'); ?></p>
                        <table id="audience-rates">
                            <tbody>
                            <tr>
                                <th><?php echo $this->translate()->trans('Global.target-date'); ?></th>
                                <?php foreach ($requiredRates as $rate) : ?>
                                <td class="<?php echo $rate['type']; ?>">by <?php echo $rate['date']; ?></td>
                                <?php endforeach; ?>
                            </tr>
                            <tr>
                                <th><?php echo $this->translate()->trans('Global.gain-per-day'); ?></th>
                                <?php foreach ($requiredRates as $rate) : ?>
                                <td class="<?php echo $rate['type']; ?>"><?php echo $rate['rate']; ?></td>
                                <?php endforeach; ?>
                            </tr>
                            </tbody>
                        </table>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="content" id="statuses">
                <div class="statusesDisplay <?php echo str_replace(' ', '_', strtolower($presenceType)); ?>" data-presence-id="<?php echo $presence->id; ?>">
                    <?php
                    $buttons = array();
                    array_unshift($buttons, '<div id="search-table"></div>');

                    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true));
                    ?>
                    <table>
                        <thead>
                            <tr>
                                <th class="message"><?php echo $this->translate()->trans('Global.content'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

	</div>
</div>