<?php
$buttons = $this->gatekeeper()->filterAll(array(
    '<a class="button" href="%url%">Edit Presence</a>' => array('action'=>'edit', 'id'=>$this->presence->id)
));
?>

<div id="pickers">
	<?php echo $this->render('partials/daterange.phtml'); ?>
</div>

<?php if ($buttons) : ?>
    <p>
        <?php echo implode('', $buttons); ?>
    </p>
<?php endif; ?>

<?php
$kpis = $this->presence->getKpiData();
$badges = $this->presence->getOverallKpi();
?>
<?php foreach($badges as $name => $badge) : ?>
    <div class="badge box <?php echo $name; ?>">

        <h3><?php echo $badge->title; ?></h3>

        <div class="score-card">
            <div class="score ranking">
                <div class="text">Ranking</div>
                <div class="number">
                    <?php echo $badge->ranking; ?>
                </div>
                <div class="text">of <?php echo $badge->rankingTotal; ?></div>
            </div>
            <div class="score overall-score">
                <div class="text">Score</div>
                <div class="number">
                    <?php echo $badge->score < 100 ? $badge->score : 99; ?>
                </div>
                <div class="text">out of 100</div>
            </div>
        </div>

        <?php if(isset($badge->values)) : ?>

            <dl>
                <h4>Percent to Target</h4>
                <?php foreach($badge->values as $key => $value) : ?>
                    <dd title="Target = <?php echo $value->target; ?>"><?php echo $value->percent; ?></dd>
                    <dt><?php echo $value->title; ?></dt>
                <?php endforeach; ?>
            </dl>

        <?php endif; ?>

    </div>
<?php endforeach; ?>


<div id="charts" data-controller="presence" data-controller-label="presence">
	<?php
	$currentId = 1;
	foreach ($this->graphs as $graph) {
		$graph->id = $currentId++;
		$graph->presence_id = $this->presence->id;
		$this->graph = $graph;
		echo $this->render('partials/chart.phtml');
	}
	?>
</div>

<div id="statuses" class="statusesDisplay <?php echo $this->presence->type; ?>" data-presence-id="<?php echo $this->presence->id; ?>">
	<div class="inner">
		<h3>Statuses</h3>
		<table>
			<thead>
				<tr>
				<?php if ($this->presence->isForFacebook()) : ?>
					<th class="user">User</th>
					<th class="message">Message</th>
					<th class="links">Links</th>
					<th class="response">Response</th>
					<th class="date">Date</th>
				<?php else : ?>
					<th class="message">Message</th>
					<th class="date">Date</th>
				<?php endif; ?>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>
