<?php if ($this->availableDates) : ?>
<div id="charts" data-controller="campaign" data-default-line-id="<?php echo $this->defaultLineId; ?>">
	<div id="api-calendar" data-date-range="<?php echo htmlspecialchars($this->defaultDateRange); ?>">
		Select a month:
		<div class="dates">
			<ul class="years">
				<?php foreach ($this->availableDates as $year => $months) : ?>
				<li>
					<?php echo $year; ?>
					<ul class="months">
						<?php foreach ($months as $month => $data) : ?>
						<li data-line-id="<?php echo $data['line-id']; ?>" data-date-range="<?php echo htmlspecialchars($data['date-range']); ?>"<?php if ($data['line-id'] == $this->defaultLineId) echo ' class="selected"'; ?>>
							<?php echo $data['label']; ?>
						</li>
						<?php endforeach; ?>
					</ul>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<div class="chart" id="api-stats" data-y-label="API requests"></div>
</div>
<?php else : ?>
	This campaign has no API data yet
<?php endif; ?>