<form method="post" action="<?php echo $this->url(array('controller'=>'campaign')); ?>" class="uniForm" novalidate>

	<fieldset class="inlineLabels">
		<legend>Campaign details</legend>
		<div class="ctrlHolder">
			<label for="name" class="requiredField">
				Campaign name<span class="asteriskField">*</span>
			</label>
			<input name="name" value="<?php echo htmlspecialchars($this->editingCampaign->name); ?>" class="textinput"
			       maxlength="20" type="text" id="name">
		</div>
		<div class="ctrlHolder">
			<label for="country" class="requiredField">
				Country<span class="asteriskField">*</span>
			</label>
			<select name="country" id="country" class="selectInput">
				<option value="">--Select--</option>
				<?php foreach ($this->countries as $code => $name) : ?>
				<option value="<?php echo $code; ?>" <?php if ($this->editingCampaign->country == $code) echo 'selected'; ?>><?php echo $name; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div class="ctrlHolder">
			<label for="audience">
				Audience size</span>
			</label>
			<input name="audience" value="<?php echo htmlspecialchars($this->editingCampaign->audience); ?>" class="textinput"
			       maxlength="20" type="text" id="audience">
		</div>
	</fieldset>

	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', array('controller'=>'campaign', 'action'=>'index'), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>

