<?php echo $this->gatekeeper()->filter('<p><a class="button add" href="%url%">Add new</a></p>', array('action'=>'new')); ?>

<?php if ($this->campaigns) : ?>
<table class="user-campaigns text">
	<tr>
		<th>Name</th>
		<th>Statuses <abbr title="Month to date">MTD</abbr></th>
		<th>Lists</th>
		<th>Searches</th>
		<th>Trends</th>
		<th>Pages</th>
		<th>Networks</th>
		<th>Analysis quota</th>
		<th>Twitter</th>
		<th></th>
	</tr>
	<?php foreach ($this->campaigns as $campaign) : ?>
	<tr>
		<td><a href="<?php echo $this->url(array('controller'=>'campaign', 'action'=>'view', 'id'=>$campaign->id)); ?>"><?php echo $campaign->name; ?></a></td>
		<td><?php echo number_format($campaign->statusCountThisMonth); ?></td>
		<td><?php echo count($campaign->twitterLists); ?></td>
		<td><?php echo count($campaign->twitterSearches); ?></td>
		<td><?php echo count($campaign->twitterTrendRegions); ?></td>
		<td><?php echo count($campaign->facebookPages); ?></td>
		<td><?php echo count($campaign->networks); ?></td>
		<td><?php echo $campaign->analysis_quota ?: 'Disabled'; ?></td>
		<td><?php

			if ($campaign->twitterToken && $campaign->twitterToken->twitterUser) {
				echo "@". $campaign->twitterToken->twitterUser->screen_name;
			} else {
				echo 'not authed';
			}

		?></td>
		<td>
			<?php
				$actions = $this->gatekeeper()->filterAll(array(
					'<a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$campaign->id),
					'<a href="%url%">Delete</a>' => array('action'=>'delete', 'id'=>$campaign->id)
				));
				echo implode(' | ', $actions);
			?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
<?php else : ?>
<p>You have no campaigns.</p>
<?php endif; ?>
