<?php echo $this->gatekeeper()->filter('<p><a class="button add" href="%url%">Add new</a></p>', array('action'=>'new')); ?>

<table class="campaigns text">
	<tr>
		<th>Name</th>
		<th>Country</th>
		<th>Audience Size</th>
		<th>Facebook pages</th>
		<th>Twitter accounts</th>
		<th class="options"></th>
	</tr>
	<?php /** @var $campaign Model_Campaign */ ?>
	<?php foreach ($this->campaigns as $campaign) : ?>
	<tr>
		<td><a href="<?php echo $this->url(array('controller'=>'campaign', 'action'=>'view', 'id'=>$campaign->id)); ?>"><?php echo $campaign->name; ?></a></td>
		<td><?php echo $this->countries[$campaign->country]; ?></td>
		<td><?php echo number_format($campaign->audience); ?></td>
		<td><?php echo number_format(count($campaign->getFacebookPages())); ?></td>
		<td><?php echo number_format(count($campaign->getTwitterAccounts())); ?></td>
		<td class="options">
			<?php
				$actions = $this->gatekeeper()->filterAll(array(
					'<a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$campaign->id),
					'<a href="%url%">Presences</a>' => array('action'=>'manage', 'id'=>$campaign->id),
					'<a href="%url%" class="autoConfirm">Delete</a>' => array('action'=>'delete', 'id'=>$campaign->id)
				));
				echo implode(' | ', $actions);
			?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
