<?php echo $this->render('partials/daterange.phtml'); ?>

<div id="charts" data-controller="search">
	<div id="legend">Legend:</div>
	<div class="chart" id="mentions" data-y-label="mentions"></div>
	<div class="chart" id="sentiment" data-y-label="sentiment"></div>
</div>

<div id="searches" class="lineSelector">
	<h3>Searches</h3>
	<table class="dtable">
		<thead>
		<tr>
			<th>Query</th>
			<th>Last fetched</th>
			<th>Status</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($this->lists as $list) : ?>
		<tr data-line-id="<?php echo BaseController::makeLineId(get_class($list), $list->id); ?>">
			<td><?php echo $list->name; ?></td>
			<td title="<?php echo $list->last_fetched; ?> UTC"><?php echo $this->prettyDate($list->last_fetched); ?></td>
			<td><?php echo $list->statusText; ?></td>
		</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<div id="tweets" class="statusesDisplay">
	<div class="inner">
		<h3>Tweets</h3>
		<table class="dtable">
			<thead>
			<tr>
				<th class="user">User</th>
				<th class="tweet">Tweet</th>
				<th class="retweets"><abbr title="Native Retweets">RTs</abbr></th>
				<th class="sentiment"><abbr title="Sentiment">+/-</abbr></th>
				<th class="date">Date</th>
			</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

