<?php
	$links = $this->gatekeeper()->filterAll(array(
		'<a class="button add" href="%url%">Add new</a>' => array('controller'=>'list', 'action' => 'new'),
		'<a class="button" href="%url%">Compare</a>' => array('controller'=>'list', 'action' => 'compare')
	));
	if ($links) :
?>
<p>
	<?php echo implode('', $links); ?>
</p>
<?php endif; ?>

<table class="twitter-lists text">
	<tr>
		<th>Name</th>
		<th>Slug</th>
		<th><abbr title="Tweets in month to date">MTD</abbr></th>
		<th><abbr title="Tweets in past 24 hours">24h</abbr></th>
		<th>Last fetched</th>
		<th>Status</th>
<!--		<th>Tweets per hour</th>-->
		<?php if ($this->campaign->analysis_quota) : ?>
		<th>Sentiment analysis</th>
		<?php endif; ?>
		<th></th>
	</tr>
	<?php foreach ($this->lists as $list) : ?>
	<tr>
		<td><?php echo $this->gatekeeper()->filter('<a href="%url%">' . $list->name . '</a>', array('controller'=>'list', 'action'=>'view', 'id'=>$list->id), null, true); ?></td>
		<td><?php echo $list->slug; ?></td>
		<td><?php echo number_format($list->tweets_this_month); ?></td>
		<td><?php echo number_format($list->tweets_last_24_hours); ?></td>
		<td title="<?php echo $list->last_fetched; ?> UTC"><?php echo $this->prettyDate($list->last_fetched, 'Never'); ?></td>
		<td><?php echo $list->statusText; ?></td>
		<?php if ($this->campaign->analysis_quota) : ?>
		<td><?php echo $list->should_analyse ? 'Enabled' : 'Disabled'; ?></td>
		<?php endif; ?>
		<td>
			<?php
				$links = $this->gatekeeper()->filterAll(array(
					'<a href="%url%">Edit</a>' => array('controller'=>'list', 'action'=>'edit', 'id'=>$list->id),
					'<a href="%url%" class="autoConfirm">Delete</a>' => array('controller'=>'list', 'action'=>'delete', 'id'=>$list->id)
				), null, true);
				echo implode(' | ', $links);
			?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>