<?php echo $this->render('partials/daterange.phtml'); ?>

<div id="charts" data-controller="list" data-default-line-id="<?php echo $this->defaultLineId; ?>">
	<div id="legend">Legend:</div>
	<div class="chart" id="mentions" data-y-label="mentions"></div>
	<div class="chart" id="sentiment" data-y-label="sentiment"></div>
</div>

<div id="topics" class="lineSelector">
	<h3>Topics</h3>
	<table class="dtable">
		<thead>
			<tr>
				<th class="topic">Topic</th>
				<th class="mentions">Mentions</th>
				<th class="sentiment"><abbr title="Sentiment">+/-</abbr></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>
<div id="tweets" class="statusesDisplay">
	<div class="inner">
		<h3>Tweets</h3>
		<table class="dtable">
			<thead>
				<tr>
					<th class="user">User</th>
					<th class="tweet">Tweet</th>
					<th class="retweets"><abbr title="Native Retweets">RTs</abbr></th>
					<th class="sentiment"><abbr title="Sentiment">+/-</abbr></th>
					<th class="date">Date</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

<div class="clear"></div>