<form method="post" action="<?php echo $this->url(array('controller'=>'search')); ?>" class="uniForm">

	<fieldset class="inlineLabels">
		<legend>Search Details</legend>

		<div class="ctrlHolder">
			<label for="query" class="requiredField">
				Query<span class="asteriskField">*</span>
			</label>		
			<input name="query" id="query" type="text" size="20" value="<?php echo htmlspecialchars($this->editingSearch->query); ?>">
		</div>

		<div class="ctrlHolder">
			<label for="name" class="requiredField">
				Name<span class="asteriskField">*</span>
			</label>		
			<input name="name" id="name" type="text" size="20" value="<?php echo htmlspecialchars($this->editingSearch->name); ?>">
			<p class="formHint">A nice name, for display purposes</p>
		</div>

		<div class="ctrlHolder">
			<p class="label">Geolocation</p>
			<ul class="blockLabels">
				<?php foreach (array(1 => 'Enabled', 0 => 'Disabled') as $val => $name) : ?>
				<li>
					<label class="radio">
					<input name="geocode" type="radio" value="<?php echo $val; ?>"
						class="toggler" data-toggle-target=".geo" data-toggle-show="<?php echo $val; ?>"
						<?php if (is_object($this->editingSearch->geoArgs) == $val) echo 'checked'; ?> /> <?php echo $name; ?>
					</label>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div class="ctrlHolder geo suboption">
			<label>
				Areas
			</label>
			<ul class="blockLabels">
				<?php if ($this->presetRegions) : ?>
				<li>
					Load from preset:
					<select id="preset-regions">
						<option value="">-</option>
						<?php foreach ($this->presetRegions as $i=>$region) : ?>
						<option value="<?php echo htmlspecialchars($region->args_json); ?>"><?php echo $region->name; ?></option>
						<?php endforeach; ?>
					</select>
				</li>
				<?php endif; ?>
				<?php
					$html = '<li>' .
						'Save as new preset: <input type="text" id="new-region-name" placeholder="New region" /> ' .
						'<a href="#" id="save-new-region" data-url="%controller%&#47;%action%">Save</a> ' .
						'<span class="ajax-message"></span></li>';
					echo $this->gatekeeper()->filter($html, array('controller'=>'region', 'action'=>'new'), null, true);
				?>
				<li>
					<div id="editableLocationMap"></div>
				</li>
			</ul>
			<p class="formHint">Click and drag the markers to move them</p>
		</div>
		<div class="ctrlHolder geo suboption">
			<label>
				Area Radii (km)
			</label>
			<?php
				if ($this->editingSearch->geoArgs) {
					$areas = $this->editingSearch->geoArgs->areas;
				} else {
					$areas = array((object)array('lat'=>0, 'lon'=>0, 'radius'=>100));
				}
			?>
			<ul class="blockLabels" id="areas">
				<?php foreach ($areas as $i=>$area) : ?>
				<li class="area">
					<div class="marker marker-<?php echo $i+1; ?>"></div>
					<input type="hidden" class="lat" name="lat[]" value="<?php echo $area->lat; ?>" />
					<input type="hidden" class="lon" name="lon[]" value="<?php echo $area->lon; ?>" />
					<input type="number" class="radius" name="rad[]" value="<?php echo $area->radius; ?>" />
					<div class="clear"></div>
				</li>
				<?php endforeach; ?>
			</ul>
			<p class="formHint">Position up to 10 areas (the fewer the better)</p>
		</div>

		<div class="ctrlHolder">
			<p class="label">Status</p>
			<ul class="blockLabels">
				<?php foreach (Model_TwitterBase::$statuses as $val => $name) : ?>
				<li>
					<label class="radio"><input name="status" type="radio" value="<?php echo $val; ?>"
					<?php if($this->editingSearch->status==$val) echo 'checked'; ?>> <?php echo $name; ?></label>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div class="ctrlHolder">
			<label for="backfill">
				Backfill
			</label>		
			<select name="backfill" id="backfill" class="selectInput">
				<?php for ($i = 0; $i <= 20; $i += 5) : ?>
				<option value="<?php echo $i; ?>"><?php echo $i * Zend_Registry::get('config')->twitter->search_fetch_per_page; ?> tweets</option>
				<?php endfor; ?>
			</select>

			<p class="formHint">Note that backfilling is not always possible, and the more tweets fetched, the longer
				this search will take to save.</p>
		</div>

		<div class="ctrlHolder checkbox">
			<p class="label">Sentiment analysis</p>
			<?php if ($this->campaign->analysis_quota) : ?>
			<ul class="blockLabels">
				<?php foreach (array(1 => 'Enabled', 0 => 'Disabled') as $val => $name) : ?>
				<li>
					<label class="radio"><input name="should_analyse" type="radio" value="<?php echo $val; ?>"
						<?php if ($this->editingSearch->should_analyse == $val) echo 'checked'; ?>> <?php echo $name; ?>
					</label>
				</li>
				<?php endforeach; ?>
			</ul>
			<?php else : ?>
			Sentiment analysis is disabled for this campaign
			<?php endif; ?>
		</div>

	</fieldset>
	
	<div class="buttonHolder">
		<?php echo $this->gatekeeper()->filter('<a href="%url%">Cancel</a>', $this->gatekeeper()->fallbackUrlArgs(array('controller'=>'search', 'action'=>'index')), null, true); ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>

</form>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
