<?php
	$links = $this->gatekeeper()->filterAll(array(
		'<a class="button add" href="%url%">Add new</a>' => array('controller'=>'search', 'action' => 'new'),
		'<a class="button" href="%url%">Compare</a>' => array('controller'=>'search', 'action' => 'compare'),
		'<a class="button" href="%url%">Manage Regions</a>' => array('controller'=>'region', 'action' => 'index')
	), null, true);
	if ($links) :
?>
<p>
	<?php echo implode('', $links); ?>
</p>
<?php endif; ?>

<table class="twitter-searches text">
	<tr>
		<th>Name</th>
		<th>Query</th>
		<th><abbr title="Tweets in month to date">MTD</abbr></th>
		<th><abbr title="Tweets in past 24 hours">24h</abbr></th>
		<th>Last fetched</th>
		<th>Status</th>
		<?php if ($this->campaign->analysis_quota) : ?>
		<th>Sentiment analysis</th>
		<?php endif; ?>
		<th></th>
	</tr>
	<?php foreach ($this->searches as $search) : ?>
	<tr>
		<td><?php echo $this->gatekeeper()->filter('<a href="%url%">' . $search->name . '</a>', array(
			'controller' => 'search', 'action' => 'view', 'id' => $search->id
		), null, true); ?></td>
		<td><?php echo $search->query; ?><?php if ($search->geoArgs) : ?><div class="geolocated" title="This search is geolocated"></div><?php endif; ?></td>
		<td><?php echo number_format($search->tweets_this_month); ?></td>
		<td><?php echo number_format($search->tweets_last_24_hours); ?></td>
		<td title="<?php echo $search->last_fetched; ?> UTC"><?php echo $this->prettyDate($search->last_fetched, 'Never'); ?></td>
		<td><?php echo $search->statusText; ?></td>
		<?php if ($this->campaign->analysis_quota) : ?>
		<td><?php echo $search->should_analyse ? 'Enabled' : 'Disabled'; ?></td>
		<?php endif; ?>
		<td>
			<?php
				$links = $this->gatekeeper()->filterAll(array(
					'<a href="%url%">Edit</a>' => array('controller'=>'search', 'action'=>'edit', 'id'=>$search->id),
					'<a href="%url%" class="autoConfirm">Delete</a>' => array('controller'=>'search', 'action'=>'delete', 'id'=>$search->id)
				), null, true);
				echo implode(' | ', $links);
			?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>