<?php
/** @var \Symfony\Bundle\FrameworkBundle\Translation\Translator $translator */
$translator = $this->translate();
$buttons = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">'.$translator->trans('buttons.common.cancel').'</a>', array('controller'=>'user', 'action'=>'index'), null, true);
if (!$cancel) {
	$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">'.$translator->trans('buttons.common.cancel').'</a>', array('controller'=>'index', 'action'=>'index'), null, true);
}
$buttons[] = $cancel;
$buttons[] = '<button type="submit" class="button-bc">'.$translator->trans('buttons.common.save').'</button>';
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<p><?php echo $translator->trans('views.scripts.user.edit.title'); ?></p>

<form class="edit" method="post" action="<?php echo $this->url(array('controller'=>'user')); ?>">

	<div class="row">
		<div class="small-24 columns">
			<fieldset>
				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label for="name" class="requiredField">
							<?php echo $translator->trans('Global.user'); ?><span class="asteriskField">*</span>
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<input id="name" name="name" type="text" class="textInput" value="<?php echo $this->editingUser->safeName; ?>" />
					</div>
				</div>

				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label for="email" class="requiredField">
							<?php echo $translator->trans('views.scripts.user.edit.label.user.email'); ?><span class="asteriskField">*</span>
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<input id="email" name="email" type="text" class="textInput" value="<?php echo htmlspecialchars($this->editingUser->email); ?>" />
					</div>
				</div>

				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label for="user_level" class="requiredField">
							<?php echo $translator->trans('views.scripts.user.edit.label.user.level'); ?><span class="asteriskField">*</span>
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<select id="user_level" name="user_level" class="selectInput" <?php if (!$this->canChangeLevel) echo 'disabled'; ?>>
							<?php foreach ($this->userLevels as $value=>$label) : ?>
								<option value="<?php echo $value; ?>" <?php if ($value == $this->editingUser->user_level) echo 'selected'; ?>><?php echo $label; ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>

				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label for="password" class="requiredField">
							<?php echo $translator->trans('Global.password'); ?><span class="asteriskField">*</span>
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<input id="password" name="password" type="password" class="textInput" />
					</div>
				</div>

				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label for="password_confirm" class="requiredField">
							<?php echo $translator->trans('Global.password-confirm'); ?><span class="asteriskField">*</span>
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<input id="password_confirm" name="password_confirm" type="password" class="textInput" />
					</div>
				</div>

				<?php if ($this->showAccessTokens) : ?>

				<div class="row">
					<div class="small-24 medium-8 large-8 columns">
						<label>
							Linkedin
						</label>
					</div>
					<div class="small-24 medium-16 large-16 end columns">
						<a href="<?php echo $this->linkedinUrl ?>"
						   class="button-bc inline"><?php echo $this->linkedinToken ? $translator->trans('views.scripts.user.edit.label.refresh-linkedin') : $translator->trans('views.scripts.user.edit.label.connect-linkedin'); ?></a>
						<?php if ($this->linkedinToken && !$this->linkedinToken->isExpired()) : ?>
							<div><?php echo $translator->trans('views.scripts.user.edit.label.linkedin-expires'); ?><?php echo $this->linkedinToken->getExpires()->diffForHumans(); ?></div>
						<?php endif; ?>
					</div>
				</div>

				<?php endif; ?>

			</fieldset>
		</div>
	</div>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>

</form>

