<?php
use Volnix\CSRF\CSRF;

$translator = $this->translate();
$buttons = array(
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'login')) . '" class="button-bc">'.$translator->trans('views.scripts.user.forgotten.button.back-to-login').'</a>',
    '<button type="submit" class="button-bc">'.$translator->trans('Global.send').'</button>'
);
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<form method="post" action="<?php echo $this->url(); ?>">
	<?php echo CSRF::getHiddenInputString(); ?>
    <input type="hidden" name="redirect_to" value="<?php echo $this->redirect_to; ?>" />
    <fieldset>
        <div>
            <label for="username"><?php $translator->trans('views.scripts.user.forgotten.username.label'); ?></label>
            <input id="username" name="username" type="text" size="26">
        </div>

    </fieldset>

	<div class="recaptcha-wrapper">
		<?php echo $this->captcha()->generateHtml(); ?>
	</div>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>

