<?php
$buttons = array(
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'login')) . '" class="button-bc">Back to login</a>',
    '<button type="submit" class="button-bc">Send</button>'
);
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<form method="post" action="<?php echo $this->url(); ?>">
    <input type="hidden" name="redirect_to" value="<?php echo $this->redirect_to; ?>" />
    <fieldset>
        <div>
            <label for="username">Name/Email</label>
            <input id="username" name="username" type="text" size="26">
        </div>

    </fieldset>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>

