<?php
/** @var \Symfony\Bundle\FrameworkBundle\Translation\Translator $translator */
$translator = $this->translate();
$buttons = array();
$new = $this->gatekeeper()->filter('<a class="button-bc" href="%url%">'.$translator->trans('views.scripts.user.index.add-new').'</a>', array('controller'=>'user', 'action'=>'new'), null, true);
if ($new) {
    $buttons[] = $new;
}
array_unshift($buttons, '<div id="search-table">'.$translator->trans('views.scripts.user.index.loading-prompt').'</div>');
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true));?>

<table class="users text dtable" id="all-users" data-sort-col="name">
	<thead>
	<tr>
		<th class="name" data-name="name" data-sort="auto"><?php echo $translator->trans('Global.name')?></th>
		<th class="email" data-name="email" data-sort="auto"><?php echo $translator->trans('views.scripts.user.index.user-table.heading.email');?></th>
		<th class="user-level" data-name="user-level" data-sort="auto"><?php echo $translator->trans('views.scripts.user.index.user-table.heading.user-level');?></th>
		<th class="access" data-name="access" data-sort="auto"><?php echo $translator->trans('views.scripts.user.index.user-table.heading.access');?></th>
		<th class="last-sign-in" data-name="last-sign-in" data-sort="data-value-numeric"><?php echo $translator->trans('views.scripts.user.index.user-table.heading.last-sign-in');?></th>
		<th class="options" data-name="options" data-sort="none" data-width="160px"><?php echo $translator->trans('views.scripts.user.index.user-table.heading.options');?></th>
	</tr>
	</thead>
	<tbody>
<?php foreach ($this->users as $user) : ?>
	<?php
		/** @var Model_User $user */
		$userLevel = array_key_exists($user->user_level, $this->userLevels) ? $this->userLevels[$user->user_level] : $translator->trans('views.scripts.user.index.user-level.unknown', ['%user_level%' => $user->user_level]);
	?>
	<tr <?php if ($user->id == $this->user->id) echo 'class="current-user"'; ?>>
		<td class="name left-align"><?php echo $user->safeName; ?></td>
		<td class="email left-align"><?php echo $user->email; ?></td>
		<td class="user-level left-align"><?php echo $userLevel; ?></td>
		<td class="access left-align">
			<?php if ($user->isManager) : ?>
			all
			<?php else : ?>
			<ul class="entity-list">
				<?php $entities = $user->getAccessEntities(); if ($entities) : ?>
				<?php foreach($entities as $e) : ?>
					<li>
						<?php $url = $this->gatekeeper()->filter('%url%', array('controller'=>$e->controller, 'action'=>'view', 'id'=>$e->entity_id)); if ($url) : ?>
						<a href="<?php echo $url; ?>" title="<?php echo $e->title; ?>" class="entity <?php echo $e->entity_type; ?>">
							<span class="icon-large <?php echo $e->icon;?>"></span>
							<?php echo $e->text; ?>
						</a>
						<?php else : ?>
						<span title="<?php echo $e->title; ?>" class="entity <?php echo $e->entity_type; ?>">
							<span class="icon-large <?php echo $e->icon;?>"></span>
							<?php echo $e->text; ?>
						</span>
						<?php endif; ?>
					</li>
				<?php endforeach; ?>
				<?php else : ?>
				none
				<?php endif; ?>
			</ul>
			<?php endif; ?>
		</td>
		<td class="last-sign-in left-align">
			<span data-value="<?php echo($user->last_sign_in ? strtotime($user->last_sign_in) : 0); ?>">
				<?php echo $this->prettyDate($user->last_sign_in, $translator->trans('views.scripts.user.index.last-sign-in.never')); ?>
			</span>
		</td>
		<td class="cell-options">
			<?php
				$links = array();
				if ($this->user->id == $user->id) {
					$links['<a href="%url%" class="button-bc">'.$translator->trans('Global.edit').'</a>'] = array('controller'=>'user', 'action'=>'edit-self');
				} else {
					$links['<a href="%url%" class="button-bc">'.$translator->trans('Global.edit').'</a>'] = array('controller'=>'user', 'action'=>'edit', 'id'=>$user->id);
					if (!$user->isManager) {
						$links['<a href="%url%" class="button-bc">'.$translator->trans('views.scripts.user.index.cell-options.access-rights').'</a>'] = array('controller'=>'user', 'action'=>'manage', 'id'=>$user->id);
					}
					if ($user->confirm_email_key !== null) {
						$queryString = http_build_query([
							'name' => $user->name,
							'confirm_email_key' => $user->confirm_email_key
						]);
						$links['<a href="%url%?'. $queryString .'" class="button-bc">'.$translator->trans('views.scripts.user.index.cell-options.confirm-mail').'</a>'] = array('controller'=>'user', 'action'=>'confirm-email');
					}
					$links['<a href="%url%" class="autoConfirm button-bc">'.$translator->trans('Global.delete').'</a>'] = array('controller'=>'user', 'action'=>'delete', 'id'=>$user->id);
				}
				$links = $this->gatekeeper()->filterAll($links);
			?>
			<ul>
				<?php foreach($links as $link): ?>
					<li><?php echo $link; ?></li>
				<?php endforeach; ?>
			</ul>
		</td>
	</tr>
<?php endforeach; ?>
	</tbody>
</table>