<?php
$buttons = array(
    '<input type="submit" class="button-bc primary" value="Log in" />',
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'forgotten'), null, true) . '">Forgot password?</a>'
);
?>

<h2 class="page-title">Login</h2>
<form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'login')); ?>">
	<input type="hidden" name="redirect_to" value="<?php echo $this->redirect_to; ?>" />
	<fieldset>
		<div>
            <label for="username">Name/Email</label>
            <input id="username" name="username" type="text" size="26">
		</div>
        <div>
            <label for="password">Password</label>
            <input id="password" name="password" type="password" size="26">
        </div>
	</fieldset>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>

