<?php
$translator = $this->trans();
$buttons = array(
    '<input type="submit" class="button-bc primary" value="'.$translator->trans('views.scripts.user.login.button.submit').'" />',
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'forgotten'), null, true) . '">'.$translator->trans('views.scripts.user.login.button.forgot-password').'</a>'
);
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'login')); ?>">
	<input type="hidden" name="redirect_to" value="<?php echo $this->redirect_to; ?>" />
	<fieldset>
		<div>
            <label for="username"><?php echo $translator->trans('views.scripts.user.login.form.label.username'); ?></label>
            <input id="username" name="username" type="text" size="26">
		</div>
        <div>
            <label for="password"><?php echo $translator->trans('Global.password'); ?><</label>
            <input id="password" name="password" type="password" size="26">
        </div>
	</fieldset>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>

