<?php $translator = $this->translate(); ?>
<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<?php if ($this->editingUser->isManager) : ?>
	<?php $buttons = $this->gatekeeper()->filterAll(array(
		'<p><a href="%url%" class="button-bc">Back</a></p>' => array('controller'=>'user', 'action'=>'index')
	)); ?>
	<?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
	<p><?php echo $translator->trans('views.scripts.user.manage.automatic-access'); ?></p>
<?php else : ?>
	<form class="management" method="post" action="<?php echo $this->url(); ?>" novalidate id="manage-user">

		<fieldset class="inlineLabels">
			<div class="row">
				<div class="small-24 columns">
					<div class="formHint"><p><?php echo $translator->trans('views.scripts.user.manage.form.form-hint'); ?></p></div>
				</div>
			</div>
			<div class="row">
				<div class="small-24 medium-8 large-8 columns">
					<label for="country">
						<?php echo $translator->trans('Global.available-countries'); ?>
					</label>
				</div>
				<div class="small-24 medium-13 large-11 columns">
					<select id="country" class="selectInput" data-icon="<?php echo Model_Country::ICON_TYPE; ?>" data-type="country">
						<option value=""><?php echo $translator->trans('Global.select-placeholder'); ?></option>
						<?php foreach ($this->countries as $c) : ?>
							<option value="<?php echo $c->id; ?>"
							        data-url="<?php echo $this->url(array('controller'=>'country', 'action'=>'view', 'id'=>$c->id)); ?>"
							        data-label="<?php echo htmlspecialchars($c->display_name); ?>"
							        data-hover="<?php echo htmlspecialchars($c->display_name); ?>">
								<?php echo htmlspecialchars($c->display_name); ?>
							</option>
						<?php endforeach; ?>
					</select>
				</div>
                <div class="small-24 medium-3 large-5 end columns">
					<button type="button" class="button-bc add-item"><?php echo $translator->trans('Global.add'); ?></button>
				</div>
			</div>

			<div class="row">
				<div class="small-24 medium-8 large-8 columns">
					<label for="group">
						<?php echo $translator->trans('views.scripts.user.manage.label.available-groups'); ?>
					</label>
				</div>
				<div class="small-24 medium-13 large-11 columns">
					<select id="group" class="selectInput" data-icon="<?php echo Model_Group::ICON_TYPE; ?>" data-type="group">
						<option value=""><?php echo $translator->trans('Global.select-placeholder'); ?></option>
						<?php foreach ($this->groups as $g) : ?>
							<option value="<?php echo $g->id; ?>"
							        data-url="<?php echo $this->url(array('controller'=>'group', 'action'=>'view', 'id'=>$g->id)); ?>"
							        data-label="<?php echo htmlspecialchars($g->display_name); ?>"
							        data-hover="<?php echo htmlspecialchars($g->display_name); ?>">
								<?php echo htmlspecialchars($g->display_name); ?>
							</option>
						<?php endforeach; ?>
					</select>
				</div>
                <div class="small-24 medium-3 large-5 end columns">
					<button type="button" class="button-bc add-item"><?php echo $translator->trans('Global.add'); ?></button>
				</div>
			</div>

			<div class="row">
				<div class="small-24 medium-8 large-8 columns">
					<label for="twitter">
                        <?php echo $translator->trans('views.scripts.user.manage.label.twitter'); ?>
					</label>
				</div>
				<div class="small-24 medium-13 large-11 columns">
					<select id="twitter" class="selectInput" data-icon="icon-twitter-sign" data-type="twitter">
						<option value=""><?php echo $translator->trans('Global.select-placeholder'); ?></option>
						<?php foreach ($this->twitterPresences as $p) : ?>
							<option value="<?php echo $p->id; ?>"
							        data-url="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>$p->id)); ?>"
							        data-label="<?php echo htmlspecialchars('@' . $p->handle); ?>"
							        data-hover="<?php echo htmlspecialchars($p->name); ?>">
								<?php echo htmlspecialchars('@' . $p->handle . ' (' . $p->name . ')'); ?>
							</option>
						<?php endforeach; ?>
					</select>
				</div>
                <div class="small-24 medium-3 large-5 end columns">
					<button type="button" class="button-bc add-item"><?php echo $translator->trans('Global.add'); ?></button>
				</div>
			</div>

			<div class="row">
				<div class="small-24 medium-8 large-8 columns">
					<label for="facebook">
						<?php echo $translator->trans('views.scripts.user.manage.label.facebook'); ?>
					</label>
				</div>
				<div class="small-24 medium-13 large-11 columns">
					<select id="facebook" class="selectInput" data-icon="icon-facebook-sign" data-type="facebook">
						<option value=""><?php echo $translator->trans('Global.select-placeholder'); ?></option>
						<?php foreach ($this->facebookPresences as $p) : ?>
							<option value="<?php echo $p->id; ?>"
							        data-url="<?php echo $this->url(array('controller'=>'presence', 'action'=>'view', 'id'=>$p->id)); ?>"
							        data-label="<?php echo htmlspecialchars($p->handle); ?>"
							        data-hover="<?php echo htmlspecialchars($p->name); ?>">
								<?php echo htmlspecialchars($p->handle . ' (' . $p->name . ')'); ?>
							</option>
						<?php endforeach; ?>
					</select>
				</div>
                <div class="small-24 medium-3 large-5 end columns">
					<button type="button" class="button-bc add-item"><?php echo $translator->trans('Global.add'); ?></button>
				</div>
			</div>

			<div class="row">
				<div class="small-24 medium-8 large-8 columns">
					<label>
						<?php echo $translator->trans('views.scripts.user.manage.label.assigned'); ?>
					</label>
				</div>
				<div class="small-24 medium-16 large-16 end columns">
					<ul id="assigned">
						<?php foreach ($this->editingUser->getAccessEntities() as $entity) : ?>
							<?php $url = $this->gatekeeper()->filter('%url%', array('controller'=>$entity->controller, 'action'=>'view', 'id'=>$entity->entity_id)); ?>
							<li class="link box <?php echo $entity->entity_type; ?> split">
								<input type="hidden" value="<?php echo $entity->entity_id;?>" name="assigned[<?php echo $entity->entity_type; ?>][]">
								<a href="<?php echo $url ?: '#'; ?>" class="first" title="<?php echo $entity->title; ?>" target="_blank">
									<span class="<?php echo $entity->icon; ?> icon-large"></span>
									<?php echo htmlspecialchars($entity->text); ?>
								</a><a href="#" class="remove-item last">
									<span class="icon-remove"></span>
								</a>
							</li>
						<?php endforeach; ?>
						<li class="none-found">
							<?php echo $translator->trans('views.scripts.user.manage.none-assigned'); ?>
						</li>
					</ul>
				</div>
			</div>
		</fieldset>
		<?php
		$buttons = $this->gatekeeper()->filterAll(array(
			'<p><a href="%url%" class="button-bc">'.$translator->trans('buttons.common.cancel').'</a></p>' => array('controller'=>'user', 'action'=>'index')
		));
		$buttons[] = '<input type="submit" value="'.$translator->trans('buttons.common.save').'" class="primaryAction button-bc">';
		?>
		<?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
	</form>
<?php endif; ?>