<?php
$buttons = array(
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'login'), null, true) . '">Already have an account?</a>',
    '<input type="submit" class="button-bc primary" value="Register" />'
);
?>

<h2 class="page-title">Register</h2>
<form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'register')); ?>">
    <fieldset>
        <div>
            <label for="name">User name*</label>
            <input id="name" name="name" type="text" size="26" required>
        </div>
        <div>
            <label for="email">Email*</label>
            <input id="email" name="email" type="email" required>
        </div>
        <div>
            <label for="password">Password*</label>
            <input id="password" name="password" type="password" size="26" required>
        </div>
        <div>
            <label for="password_confirm">Password (again)*</label>
            <input id="password_confirm" name="password_confirm" type="password" size="26" required>
        </div>
    </fieldset>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>

