<?php
use Volnix\CSRF\CSRF;

$translator = $this->translate();
$buttons = array(
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'login'), null, true) . '">'.$translator->trans('views.scripts.user.register.button.already-registered').'</a>',
    '<input type="submit" class="button-bc primary" value="'.$translator->trans('navigation-menu.register').'"/>'
);
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<?php if ($this->registerSuccessful) : ?>

    <p><?php echo $translator->trans('views.scripts.user.register.register-successful.first-line'); ?></p>
    <p><?php echo $translator->trans('views.scripts.user.register.register-successful.second-line'); ?></p>

<?php else : ?>

    <form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'register')); ?>">
		<?php echo CSRF::getHiddenInputString(); ?>
        <fieldset>
            <div>
                <label for="name"><?php echo $translator->trans('Global.user'); ?>*</label>
                <input id="name" name="name" type="text" size="26" required>
            </div>
            <div>
                <label for="email"><?php echo $translator->trans('Global.email'); ?>*</label>
                <input id="email" name="email" type="email" required>
            </div>
            <div>
                <label for="password"><?php echo $translator->trans('Global.password'); ?>*</label>
                <input id="password" name="password" type="password" size="26" required>
            </div>
            <div>
                <label for="password_confirm"><?php echo $translator->trans('Global.password-confirm'); ?>*</label>
                <input id="password_confirm" name="password_confirm" type="password" size="26" required>
            </div>
        </fieldset>

        <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
    </form>

<?php endif; ?>