<div class="login-title">
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>" class="site-title-link"><div class="site-title"><span>British Council Social Media Monitor</span></div></a>
</div>
<h2 class="page-title">Change Password</h2>
<form method="post" action="<?php echo $this->url(); ?>">
    <h2><?php echo $this->editingUser->safeName; ?></h2>
    <input type="hidden" name="name" value="<?php echo $this->editingUser->safeName; ?>" />
    <input type="hidden" name="reset_key" value="<?php echo $this->editingUser->reset_key; ?>" />
    <fieldset>
        <div>
            <label for="password">New password</label>
            <input id="password" name="password" type="password" size="20">
        </div>
        <div>
            <label for="password_confirm">New password (again)</label>
            <input id="password_confirm" name="password_confirm" type="password" size="20">
        </div>
    </fieldset>

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 columns">
                <ul class="button-group">
                    <li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'login')); ?>" class="button-bc">Back to login</a></li>
                    <li><button type="submit" class="button-bc">Log in</button></li>
                </ul>
            </div>
        </div>
    </div>
</form>