<?php
$translator = $this->translate();
$buttons = array(
    '<a href="' . $this->url(array('controller'=>'user', 'action'=>'login')) . '" class="button-bc">Back to login</a></li>',
    '<button type="submit" class="button-bc">'.$translator->trans('views.scripts.user.reset-password.log-in').'</button>'
);
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>
<form method="post" action="<?php echo $this->url(); ?>">
    <h2><?php echo $this->editingUser->safeName; ?></h2>
    <input type="hidden" name="name" value="<?php echo $this->editingUser->safeName; ?>" />
    <input type="hidden" name="reset_key" value="<?php echo $this->editingUser->reset_key; ?>" />
    <fieldset>
        <div>
            <label for="password"><?php echo $translator->trans('views.scripts.user.reset-password.new-password'); ?></label>
            <input id="password" name="password" type="password" size="20">
        </div>
        <div>
            <label for="password_confirm"><?php echo $translator->trans('views.scripts.user.reset-password.new-password-confirm'); ?></label>
            <input id="password_confirm" name="password_confirm" type="password" size="20">
        </div>
    </fieldset>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons, 'dark'=>true)); ?>
</form>