<?php
//foreach (array('user', 'campaign') as $type) {
//	$token = $this->{$type}->twitterToken;
//	if ($token && $token->twitterUser) {
//		$minutes = round((strtotime($token->reset_time.' UTC') - time()) / 60);
//		if ($minutes < 0) {
//			$class = 'unknown';
//		} else {
//			$title = "$token->remaining_hits hits remaining, reset in $minutes minutes";
//			$proportionHitsUsed = ($token->hourly_limit - $token->remaining_hits) / $token->hourly_limit;
//			$proportionTimeUsed = 1 - $minutes/60;
//			$class = $proportionHitsUsed < $proportionTimeUsed ? 'ok' : 'danger';
//		}
//		echo "<span data-hits='{$token->remaining_hits}' data-reset='$minutes' data-type='$type' data-status='$class'
//			class='$class'>@{$token->twitterUser->screen_name}</span> ";
//	} else {
//		echo $this->gatekeeper()->filter('<a href="%url%">' . ucfirst($type) . ' not authed</a> ', array(
//			'controller' => $type, 'action' => 'oauth'
//		), 'default', true);
//	}
//}
?>
