<?php $translator = $this->translate();?>
<fieldset class="inlineLabels">
    <h2><?php echo $translator->trans('Global.available-countries'); ?></h2>
	<div class="row">
        <div class="small-24 medium-21 large-19 columns">
			<select id="countries" class="selectInput">
				<option value=""><?php echo $translator->trans('Global.select-placeholder'); ?></option>
				<?php foreach ($this->allCountries as $c) : /** @var $c Model_Country */ ?>
					<option value="<?php echo $c->id; ?>"
							data-url="<?php echo $this->url(array('controller'=>'country', 'action'=>'view', 'id'=>$c->id)); ?>"
							data-label="<?php echo htmlspecialchars($c->getName()); ?>"
							data-flag="<?php echo htmlspecialchars($c->getCountryCode()); ?>"
					>
						<?php echo htmlspecialchars($c->getName()); ?>
					</option>
				<?php endforeach; ?>
			</select>
        </div>
        <div class="small-24 medium-3 large-5 end columns">
            <button type="button" class="button-bc add-item"><?php echo $translator->trans('Global.add'); ?></button>
        </div>
    </div>

    <h2><?php echo $translator->trans('views.scripts.partials.assign-countries.heading.currently-assigned'); ?></h2>
    <div class="row">
        <div class="small-24 columns">
			<ul id="assigned">
				<?php
				foreach ($this->owner->getCountries() as $country) {
					echo $this->partial('partials/country_box.phtml', array('country'=>$country, 'varname'=>'assigned[]'));
				}
				?>
				<li class="none-found">
					<?php echo $translator->trans('views.scripts.partials.assign-countries.heading.none-assigned'); ?>
				</li>
			</ul>
        </div>
    </div>
</fieldset>
