<fieldset class="inlineLabels">
    <h2>Available countries</h2>
	<div class="row">
        <div class="small-24 columns">
			<select id="countries" class="selectInput">
				<option value="">-- Select --</option>
				<?php foreach ($this->allCountries as $c) : ?>
					<option value="<?php echo $c->id; ?>"
							data-url="<?php echo $this->url(array('controller'=>'country', 'action'=>'view', 'id'=>$c->id)); ?>"
							data-label="<?php echo $c->getName(); ?>"
							data-flag="<?php echo $this->baseUrl('/'); ?>assets/img/flags/<?php echo($c->getCountryCode()); ?>.png"
					>
						<?php echo $c->getName(); ?>
					</option>
				<?php endforeach; ?>
			</select>
            <button type="button" class="button-bc add-item">Add</button>
        </div>
    </div>

    <h2>Currently assigned countries</h2>
    <div class="row">
        <div class="small-24 columns">
			<ul id="assigned">
				<?php
				foreach ($this->owner->getCountries() as $country) {
					echo $this->partial('partials/country_box.phtml', array('country'=>$country, 'varname'=>'assigned[]'));
				}
				?>
				<li class="none-found">
					No countries assigned
				</li>
			</ul>
        </div>
    </div>
</fieldset>
