<?php

$locale = 'en_US';
$nf = new NumberFormatter($locale, NumberFormatter::ORDINAL);

function metricAttributes($metric) {
    $attrs = array();
    $title = $metric['title'];
    if (array_key_exists('score', $metric)) {
        $score = $metric['score'];
        $attrs['style'] = "color: " . $metric['color'];
        if ($score > 0) {
            $score = round($score*10)/10; // use 1 decimal place maximum
            $attrs['title'] = "This presence has scored {$score}% for {$title} based on an average of the last 30 days of data.";
        } else {
            if ($metric['gliding'] || $score === null) {
                $attrs['title'] = "There is no data available to calculate {$title}.";
            } else {
                $attrs['title'] = "This presence has scored 0% for {$title}.";
            }
        }
    } else {
        $attrs['title'] = "{$title} is not applicable for this presence";
    }

    $attrStrings = [];
    foreach ($attrs as $key=>$value) {
        $attrStrings[] = $key . '="' . $value . '"';
    }

    return implode(' ', $attrStrings);
}
?>

<div class="badges">
    <div class="badge-main bd-btm">
        <?php $badge = $this->badges['main']; ?>
        <h2 class="bd-btm"><?php echo $badge['title']; ?></h2>
        <div class="row">
            <div class="small-24 medium-12 columns">

                <div class="badge-rank">
                    <h3>Rank</h3>
                    <div class="rank-value">
                        <span class="numerator"><?php echo $badge['rank']['value']; ?><span><?php echo trim(str_replace(range(0,9),'',$nf->format($badge['rank']['value'])));?></span></span><span class="denominator">/<?php echo $badge['rank']['denominator']; ?></span>
                    </div>
                </div>

            </div>
            <div class="small-24 medium-12 columns">

                <div class="badge-score">
                    <h3>Score</h3>
                    <div class="score-value" style="color:<?php echo $badge['score']['color']; ?>;">
                        <?php echo $badge['score']['value']; ?>%
                    </div>
                </div>

            </div>
        </div>

    </div>
    <div class="row">
        <?php foreach($this->badges['small'] as $badge) : ?>
            <div class="small-24 medium-8 columns">
                <div class="badge-small">
                    <h2 class="bd-btm"><?php echo $badge['title']; ?></h2>

                    <div class="badge-rank bd-btm">
                        <h3>Rank</h3>
                        <div class="rank-value">
                            <!-- breaking the line causes the display not display properly -->
                            <span class="numerator"><?php echo $badge['rank']['value']; ?><span><?php echo trim(str_replace(range(0,9),'',$nf->format($badge['rank']['value'])));?></span></span><span class="denominator">/<?php echo $badge['rank']['denominator']; ?></span>
                        </div>
                    </div>

                    <div class="badge-score bd-btm">
                        <h3>Score</h3>
                        <div class="score-value" style="color:<?php echo $badge['score']['color']; ?>;">
                            <?php echo $badge['score']['value']; ?>%
                        </div>
                        <div class="score-bar">
                            <div class="score-bar-score" style="background:<?php echo $badge['score']['color']; ?>; width: <?php echo $badge['score']['value']; ?>%;"></div>
                        </div>
                    </div>

                    <?php if ($this->showMetrics): ?>
                        <ul class="badge-metrics show-for-large-up">
                            <?php foreach($badge['metrics'] as $metric): ?>
                                <li class="bd-btm"
                                    <?php if (!empty($this->titles)) { echo metricAttributes($metric); } ?> >
                                    <span class="<?php echo $metric['icon']; ?> fa-fw"></span> <?php echo $metric['title']; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>