<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Matthew
 * Date: 05/06/13
 * Time: 12:36
 * To change this template use File | Settings | File Templates.
 */
?>

<div id="<?php echo $this->badge; ?>" class="badge box">

    <h3><?php echo ucfirst($this->badge); ?></h3>

    <div class="score-card">

        <div class="score ranking">
            <div class="text title">Ranking</div>
            <div class="number">
                ?
            </div>
            <div class="text denominator">of ?</div>
        </div>

        <div class="score overall-score">
            <div class="text">Score</div>
            <div class="number">
                ?
            </div>
            <div class="text">out of 100</div>
        </div>

    </div>

    <?php if($this->badge != 'total') : ?>

        <dl>
            <h4>Percent to Target</h4>

        </dl>

    <?php endif; ?>

</div>