<div class="row">
    <div class="small-24 large-12 xlarge-8 columns">

        <?php //echo $this->partial('partials/button-bar.phtml', array('buttons'=>$buttons)); ?>

        <div class="model-header bd-btm picker">
            <label for="campaign-switcher"><?php echo $this->campaignType; ?>:</label>
            <select id="campaign-switcher" data-url-template="<?php echo $this->url(array('controller'=>$this->controllerName, 'action'=>'view', 'id'=>'the_id')); ?>">
                <?php foreach ($this->allCampaigns as $c) : ?>
                <option value="<?php echo $c->id; ?>" <?php if ($c->id == $this->campaign->id) { echo 'selected'; } ?>><?php echo $c->display_name; ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <?php echo $this->partial("partials/badges.phtml", array("badges" => $this->badgePartial)); ?>

    </div>
    <div class="small-24 large-12 xlarge-16 columns">

        <div class="show-for-medium-up">

            <div id="pickers" class="bd-btm">
                <?php echo $this->render('partials/chart-picker.phtml'); ?>
                <?php echo $this->render('partials/daterange.phtml'); ?>
            </div>

            <div class="chart-description"></div>

            <div id="new-chart" data-controller="<?php echo $this->controllerName; ?>" data-id="<?php echo $this->campaign->id; ?>"></div>

        </div>

    </div>
</div>