<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

/** @var Model_Country|Model_Group|Model_Region $campaign */
$campaign = $this->campaign;
$presences = $campaign->getPresences();
$region = null;
$countries = array();
if ($campaign instanceof Model_Country) {
    $region = $campaign->getRegion();
} else if ($campaign instanceof Model_Region) {
    $countries = $campaign->getCountries();
}
?>

<div class="row">
    <div class="small-24 large-12 xlarge-8 columns">

        <div class="model-header bd-btm">
            <span class="page-icon icon-large <?php echo $this->titleIcon; ?>"></span>
            <div class="picker">
                <label for="campaign-switcher"><?php echo $this->campaignType; ?>:</label>
                <select id="campaign-switcher" data-url-template="<?php echo $this->url(array('controller'=>$this->controllerName, 'action'=>'view', 'id'=>'the_id')); ?>">
                    <?php foreach ($this->allCampaigns as $c) : ?>
                    <option value="<?php echo $c->id; ?>" <?php if ($c->id == $campaign->id) { echo 'selected'; } ?>><?php echo $c->display_name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <?php echo $this->partial("partials/badges.phtml", array("badges" => $this->badgePartial, 'showMetrics' => false, 'pdfLink' => $this->pdfLink)); ?>

        <?php echo $this->partial("partials/country-list.phtml", array("countries" => $countries)); ?>

    </div>
    <div class="small-24 large-12 xlarge-16 columns">

        <dl class="tabs" data-tab id="model-tabs">
            <dd class="active"><a href="#chart"><?php echo $translator->trans('Global.tabs.charts.label') ?></a></dd>
            <dd><a href="#info"><?php echo $translator->trans('Global.tabs.info.label') ?></a></dd>
        </dl>
        <div class="tabs-content" id="model-tabs-content">
            <div class="content active" id="chart">
                <div class="show-for-medium-up">
                    <div id="pickers">
                        <?php echo $this->render('partials/chart-picker.phtml'); ?>
                        <?php echo $this->render('partials/daterange.phtml'); ?>
                    </div>

                    <div class="chart-description"></div>

                    <div id="new-chart" data-controller="<?php echo $this->controllerName; ?>" data-id="<?php echo $campaign->id; ?>"></div>
                    <div id="new-chart-values"></div>
                </div>
                <div class="hide-for-medium-up">
                    <p><?php echo $translator->trans('Global.tabs.charts.unavailable') ?></p>
                </div>
            </div>
            <div class="content" id="info">
                <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$this->buttons)); ?>
                <?php echo $this->partial($this->controllerName . '/view-info-panel.phtml', array('campaign'=>$campaign)); ?>
            </div>
        </div>

    </div>
</div>