<div id="chart-picker-box" class="picker">

	<label for="chart-picker"><?php echo $this->translate()->trans('Global.tabs.charts.chart.label') ?>:</label>
	<select id="chart-picker">
        <?php foreach($this->chartOptions as $chart) : /** @var $chart Chart_Abstract */?>
            <option value="<?php echo $chart->getName(); ?>"><?php echo htmlspecialchars($chart->getTitle()); ?></option>
        <?php endforeach;?>
	</select>

</div>