<?php $graph = $this->graph; ?>

<div class="chart-container">

    <div class="health">

<!--        <h3 class="title">--><?php ////echo $graph->title; ?><!--</h3>-->

        <div class="fieldset">
            <h4 class="legend"></h4>
            <p class="value"></p>
        </div>

        <p class="target"></p>

    </div>

    <div id="chart_<?php echo $graph->id; ?>" class="chart" data-metric="<?php echo $graph->metric; ?>" data-y-label="<?php echo $graph->yAxisLabel; ?>" data-presence-id="<?php echo $graph->presence_id; ?>">

        <div class="downloadChart">Download as <span class="link">PNG</span> or <span class="link">SVG</span></div>

    </div>

    <div class="clearfix"></div>

</div>