<?php $graph = $this->graph; ?>

<div class="chart-container">

    <div class="health">

        <div class="fieldset hidden">
            <h4 class="legend hidden"></h4>
            <p class="value"></p>
        </div>

        <p class="target"></p>

    </div>

    <div id="chart_<?php echo $graph->id; ?>"
         class="chart"
         data-metric="<?php echo $graph->metric; ?>"
         data-y-label="<?php echo $graph->yAxisLabel; ?>"
         data-presence-id="<?php echo $graph->presence_id; ?>">
    </div>

    <div class="clearfix"></div>

</div>