<?php $translator = $this->translate() ?>
<?php if ($this->countries) : ?>
    <div id="country-list">
    <h4><?php echo $translator->trans('route.region.view.info.countries.header', ['%count%' => count($this->countries)]); ?></h4>
    <ul class="entity-list">
        <?php foreach ($this->countries as $c) : ?>
            <?php echo $this->partial('partials/country_box.phtml', array('country'=>$c)); ?>
        <?php endforeach; ?>
    </ul>
    </div>
<?php endif; ?>