<?php $url = $this->gatekeeper()->filter('%url%', array('controller'=>'country', 'action'=>'view', 'id'=>$this->country->id));
if ($url) : ?>
	<a href="<?php echo $url; ?>" title="<?php echo $this->country->getName(); ?>" class="entity country">
		<span class="flag"><img src="assets/img/flags/<?php echo($this->country->getCountryCode()); ?>.png" /></span>
		<?php echo $this->country->getName; ?>
	</a>
<?php else : ?>
    <span title="<?php echo $this->presence->label; ?>" class="entity presence <?php echo $this->presence->type; ?>">
		<span class="flag"><img src="assets/img/flags/<?php echo($this->country->getCountryCode()); ?>.png" /></span>
        <?php echo $this->country->getName; ?>
	</span>
<?php endif; ?>
