<?php
$url = $this->gatekeeper()->filter('%url%', array('controller'=>'country', 'action'=>'view', 'id'=>$this->country->id));
if ($url) {
    $tag = 'a';
    $attrs = 'href="' . $url . '"';
} else {
    $tag = 'span';
    $attrs = '';
}
?>
<<?php echo $tag; ?> <?php echo $attrs; ?> class="entity country">
    <span class="flag"><img src="<?php echo $this->baseUrl('/') . 'assets/img/flags/' . $this->country->getCountryCode() . '.png'; ?>" /></span>
    <?php echo $this->country->getName(); ?>
</<?php echo $tag; ?>>
