<?php
$url = $this->gatekeeper()->filter('%url%', array('controller'=>'country', 'action'=>'view', 'id'=>$this->country->id), null, true);
$forForm = !empty($this->varname);
?>
<li class="link box country split">
    <?php if ($forForm) : ?>
	<input type="hidden" value="<?php echo $this->country->id;?>" name="<?php echo $this->varname; ?>">
    <?php endif; ?>
	<a href="<?php echo ($url ?: '#'); ?>" title="<?php echo htmlspecialchars($this->country->getName()); ?>" class="first <?php if (!$forForm) { echo 'last'; } ?>">
		<div class="sm-flag flag-<?php echo htmlspecialchars($this->country->getCountryCode()); ?>"></div>
		<?php echo htmlspecialchars($this->country->getName()); ?>
	</a><?php if ($forForm) : ?><a href="#" class="remove-item last">
		<span class="icon-remove"></span>
	</a>
    <?php endif; ?>
</li>