<div id="modal-container" style="<?php echo isset($_COOKIE['feedbackOpen']) ? '' : 'display:none;'; ?>">
    <div id="feedback-form">
        <header>
            <h2>Feedback form</h2>
            <p>Lorem ipsum dolor sit amet.</p>
        </header>
        <form>
            <label for="name">Your name</label>
            <input id="name" name="name" maxlength="64" type="text" placeholder="Enter your first and last name" required />

            <label for="from">Your email</label>
            <input id="from" name="from" maxlength="64" type="email" placeholder="Enter your email address" required />

            <label for="body">Your message</label>
            <textarea id="body" name="body" maxlength="1000" placeholder="Enter your message (max. 1000 characters)"
                      required></textarea>

            <input id="url" name="url" maxlength="64" type="hidden" value="<?php echo $this->baseUrl('/feedback') ?>"/>

            <ul class="button-group">
                <li><button id="submit" type="button" class="button-bc primary" onclick="app.modal.send()">Send form</button></li>
                <li><button id="close" type="button" class="button-bc" onclick="app.modal.hide()">Cancel</button></li>
            </ul>

        </form>
    </div>
</div>
<div id="modal-backdrop" style="display:none;"></div>