<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

$pageId = "Base.layout.feedback-modal.";
?>

<div id="modal-container" style="display:none;">
    <div id="feedback-form">
        <header>
            <h2><?php echo $translator->trans($pageId . "title")?></h2>
            <p><?php echo $translator->trans($pageId . "subtitle")?></p>
        </header>
        <form>
            <label for="name"><?php echo $translator->trans($pageId . "name-label") ?></label>
            <input id="name" name="name" maxlength="64" type="text"
                   placeholder="<?php echo $translator->trans($pageId . "name-placeholder") ?>" required />

            <label for="from"><?php echo $translator->trans($pageId . "email-label") ?></label>
            <input id="from" name="from" maxlength="64" type="email"
                   placeholder="<?php echo $translator->trans($pageId . "email-placeholder") ?>" required />

            <label for="body"><?php echo $translator->trans($pageId . "message-label") ?></label>
            <textarea id="body" name="body" maxlength="1000"
                      placeholder="<?php echo $translator->trans($pageId . "message-placeholder") ?>" required></textarea>

            <input id="url" name="url" maxlength="64" type="hidden" value="<?php echo $this->baseUrl('/feedback') ?>"/>

            <ul class="button-group">
                <li>
                    <button id="submit" type="button" class="button-bc primary" onclick="app.feedbackForm.send()">
                        <?php echo $translator->trans($pageId . "submit") ?>
                    </button>
                </li>
                <li>
                    <button id="close" type="button" class="button-bc" onclick="app.modal.hide()">
                        <?php echo $translator->trans($pageId . "close") ?>
                    </button>
                </li>
            </ul>

        </form>
    </div>
</div>
<div id="modal-backdrop" style="display:none;"></div>