<p class="navigation">

    <?php

	/** @var \Symfony\Component\Translation\Translator $translator */
	$translator = $this->translate();

    /** @var Zend_Navigation_Page_Mvc $page */
    foreach ($this->container as $page) :

        $href = $page->getHref();

        if($href) : ?>

            <?php
                $classes = isset($page->class) ? array($page->class) : array() ;

                $urlTest = $this->gatekeeper()->filter('%url%', array('controller' => $page->controller, 'action' => $page->action));

                if (!$urlTest) {
                    $href = null;
                }
                if ($page->active) {
                    $classes[] = 'active';
                }

                if ($href) : ?>
                    <a href="<?php echo $href; ?>" class="<?php echo implode(' ', $classes); ?>">
                        <span><?php echo $translator->trans('navigation-menu.' . $page->getId()); ?></span>
                    </a><?php
                else : ?>
                    <span class="<?php echo implode(' ', $classes); ?>">
                        <span><?php echo $translator->trans('navigation-menu.' . $page->getId()); ?></span>
                    </span><?php
                endif;

        endif;

    endforeach; ?>

</p>