<ul class="navigation">

    <?php

    /** @var Zend_Navigation_Page_Mvc $page */
    foreach ($this->container as $page) :

        $href = $page->getHref();

        if($href) : ?>

            <?php
            $classes = array();
            $urlTest = $this->gatekeeper()->filter('%url%', array('controller' => $page->controller, 'action' => $page->action));
            if (!$urlTest) {
	            $href = '#';
	            $classes[] = 'disabled';
            }
	        if ($page->active) {
		        $classes[] = 'active';
	        }
            ?>

            <li class="<?php echo implode(' ', $classes); ?>">
                <a href="<?php echo $href; ?>">

                    <?php
                        $icon = $page->icon;
                        if($icon) echo '<span class="'.$icon.'"></span>  ';
                        echo $page->getLabel();
                    ?>

                </a>
            </li>

        <?php endif;

    endforeach; ?>

</ul>