<ul class="navigation">

    <?php

    /** @var Zend_Navigation_Page_Mvc $page */
    foreach ($this->container as $page) :

        $href = $page->getHref();

        if($href) : ?>

            <?php
            $classes = array($page->class);
            $urlTest = $this->gatekeeper()->filter('%url%', array('controller' => $page->controller, 'action' => $page->action));
            if (!$urlTest) {
	            $href = '';
	            $classes[] = 'disabled';
            } else {
	            $classes[] = 'enabled';
            }
	        if ($page->active) {
		        $classes[] = 'active';
	        }
	        $icon = $page->icon;
            ?>

            <li class="<?php echo implode(' ', $classes); ?>">
                <a <?php if ($href) { echo 'href="' . $href . '"'; } ?>><?php
                    if($icon) : ?>
		                <span class="<?php echo $icon; ?>"></span>  <?php
                    endif; ?>
                    <span class="label"><?php echo $page->getLabel(); ?></span>
                </a><?php
                if(!empty($page->pages)) : ?>
                    <ul><?php
                        foreach($page->pages as $p) :
                            $href = $p->getHref();
                            $classes = array('child'); ?>
                            <li class="<?php echo implode(' ', $classes); ?>">
                                <a <?php if ($href) { echo 'href="' . $href . '"'; } ?>><?php
                                    echo $p->getLabel(); ?>
                                </a>
                            </li><?php
                         endforeach; ?>
                    </ul><?php
                endif; ?>

            </li>

        <?php endif;

    endforeach; ?>

</ul>