<?php
$url = $this->gatekeeper()->filter('%url%', array('controller'=>'presence', 'action'=>'view', 'id'=>$this->presence->id));
if ($url) {
    $tag = 'a';
    $attrs = 'href="' . $url . '"';
} else {
    $tag = 'span';
    $attrs = '';
}
?>
<<?php echo $tag; ?> <?php echo $attrs; ?> title="<?php echo $this->presence->getLabel(); ?>" class="entity presence <?php echo $this->presence->type; ?>">
    <span class="<?php echo $this->presence->getPresenceSign();?>"></span>
    <?php echo $this->presence->handle; ?>
</<?php echo $tag; ?>>
