<?php $url = $this->gatekeeper()->filter('%url%', array('controller'=>'presence', 'action'=>'view', 'id'=>$this->presence->id));
if ($url) : ?>
	<a href="<?php echo $url; ?>" title="<?php echo $this->presence->label; ?>" class="entity presence <?php echo $this->presence->type; ?>">
		<span class="<?php echo $this->presence->getPresenceSign();?>"></span>
		<?php echo $this->presence->handle;
        if ($this->presence->isForTwitter()) : ?>
            <span class="klout" title="Klout score: <?php echo $this->presence->klout_score; ?>">
                <?php echo round($this->presence->klout_score); ?>
            </span><?php
        else:
            $endDate = new DateTime();
            $startDate = clone $endDate;
            $startDate->sub(new DateInterval('P1M'));
            $fb = $this->presence->getFacebookEngagementScore($startDate->format('Y-m-d'),$endDate->format('Y-m-d')); ?>
            <span class="klout facebook" title="Facebook Engagement score: <?php echo $fb; ?>">
                <?php echo round($fb); ?>
            </span><?php
        endif; ?>
	</a>
<?php else : ?>
	<span title="<?php echo $this->presence->label; ?>" class="entity presence <?php echo $this->presence->type; ?>">
		<span class="<?php echo $this->presence->getPresenceSign();?>"></span>
		<?php echo $this->presence->handle; ?>
	</span>
<?php endif; ?>
