<form method="post" action="<?php echo $this->url(); ?>" class="uniForm">
	<fieldset class="inlineLabels">
        <?php foreach ($this->values as $section) : ?>
            <h2><?php echo $section->title; ?></h2>
            <?php echo $section->description; ?>
            <?php foreach ($section->kpis as $kpi) : ?>

                <h3><?php echo $kpi->title; ?></h3>
                <p><?php echo $kpi->description; ?></p>
                <?php foreach ($kpi->values as $args) : ?>

                    <div class="ctrlHolder">
                        <label for="<?php echo $args->key; ?>">
                            <?php echo $args->label; ?>
                        </label>
                        <input name="<?php echo $args->key; ?>" value="<?php echo htmlspecialchars($args->value); ?>" class="textInput <?php if ($args->error) { echo 'error'; } ?>"
                               type="text" id="<?php echo $args->key; ?>">
                        <?php if ($args->hint) : ?>
                        <p class="formHint"><?php echo $args->hint; ?></p>
                        <?php endif; ?>
                        <?php if ($args->error) : ?>
                        <p class="formError"><?php echo $args->error; ?></p>
                        <?php endif; ?>
                    </div>

                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
	</fieldset>

	<div class="buttonHolder">
        <?php $buttons = $this->gatekeeper()->filterAll(array(
            '<a class="button" href="%url%">Cancel</a>' => array('action'=>'index')
        ));
        foreach($buttons as $button) { echo $button; } ?>
		<input type="submit" value="Save" class="primaryAction">
	</div>
</form>