<h2 class="page-title">Settings</h2>

<form class="edit" method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data" id="settings">
    <?php foreach ($this->values as $section) : ?>
		<fieldset>
            <h2><?php echo $section->title; ?></h2>
            <div class="row">
                <div class="columns small-24 medium-24 large-24">
                    <?php echo $section->description; ?>
                </div>
            </div>
            <?php foreach ($section->kpis as $kpi) : ?>

                <h3><?php echo $kpi->title; ?></h3>
                <p><?php echo $kpi->description; ?></p>
                <?php foreach ($kpi->values as $args) : ?>

                    <div class="row">
                        <div class="small-24 medium-8 large-8 columns">
                            <label for="<?php echo $args->key; ?>">
                                <?php echo $args->label; ?>
                            </label>
                        </div>
                        <div class="small-24 medium-16 large-16 end columns">
                            <input name="<?php echo $args->key; ?>" value="<?php echo htmlspecialchars($args->value); ?>" class="textInput <?php if ($args->error) { echo 'error'; } ?>"
                                   type="text" id="<?php echo $args->key; ?>">
                            <?php if ($args->hint) : ?>
                                <p class="formHint"><?php echo $args->hint; ?></p>
                            <?php endif; ?>
                            <?php if ($args->error) : ?>
                                <p class="formError"><?php echo $args->error; ?></p>
                            <?php endif; ?>
                        </div>
                    </div>

                <?php endforeach; ?>
            <?php endforeach; ?>
		</fieldset>
    <?php endforeach; ?>
    <fieldset>
        <h2>Upload KPI File</h2>
        <p>Upload the KPI file that can be downloaded from the front page</p>
        <div class="row">
            <div class="small-24 medium-8 large-8 columns">
                <label  for="uploadedfile">
                    Choose a file to upload:
                </label>
            </div>
            <div class="small-24 medium-16 large-16 end columns">
                <input name="uploadedfile" id="uploadedfile" type="file" />
            </div>
        </div>
    </fieldset>

    <?php
    $buttons = $this->gatekeeper()->filterAll(array(
            '<a class="button-bc" href="%url%">Cancel</a>' => array('controller'=>'index', 'action'=>'index')
        ));
    $buttons[] = '<button type="submit" class="button-bc">Save</button>';
    echo $this->partial('partials/button-bar.phtml', array('buttons' => $buttons, 'dark' => true));
    ?>
</form>