<?php
$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'country', 'action'=>'index'), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">Save</button>';
$topBar = $bottomBar;
array_unshift($topBar, '<div id="search-table"></div>');
?>

<h2 class="page-title">Edit All Countries</h2>

<form class="edit-all" method="post" action="<?php echo $this->url(); ?>" novalidate id="edit-all-countries">

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true)); ?>

    <table class="text dtable" id="all-countries">
        <thead>
            <tr>
                <th data-name="name" data-sort="forminput">Display name</th>
                <th data-name="country" data-sort="forminput">Country</th>
                <th data-name="audience" data-sort="fuzzy-numeric">Audience Size</th>
                <th data-name="population" data-sort="fuzzy-numeric">Population</th>
                <th data-name="penetration" data-sort="fuzzy-numeric">Internet Penetration</th>
            </tr>
        </thead>
        <tbody>
        <?php /** @var $country Model_Country */ ?>
        <?php foreach ($this->countries as $country) : ?>
            <tr>
                <td>
                    <input name="<?php echo $country->id; ?>_display_name" value="<?php echo htmlspecialchars($country->display_name); ?>" class="textInput"
                           type="text" id="<?php echo $country->id; ?>_display_name">
                </td>
                <td>
                    <select name="<?php echo $country->id; ?>_country" id="<?php echo $country->id; ?>_country" class="selectInput">
                        <option value="">--Select--</option>
                        <?php foreach ($this->countryCodes as $code => $name) : ?>
                            <option value="<?php echo $code; ?>" <?php if ($country->country == $code) echo 'selected'; ?>><?php echo $name; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    <input name="<?php echo $country->id; ?>_audience" value="<?php echo htmlspecialchars($country->audience); ?>" class="textInput"
                           type="text" id="<?php echo $country->id; ?>_audience">
                </td>
                <td>
                    <input name="<?php echo $country->id; ?>_population" value="<?php echo htmlspecialchars($country->population); ?>" class="textInput"
                           type="text" id="<?php echo $country->id; ?>_population">
                </td>
                <td>
                    <input name="<?php echo $country->id; ?>_penetration" value="<?php echo htmlspecialchars($country->penetration); ?>" class="textInput"
                           type="text" id="<?php echo $country->id; ?>_penetration">
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true)); ?>

</form>

