<?php echo $this->gatekeeper()->filter('<p><a class="button add" href="%url%">Add new</a></p>', array('action'=>'new')); ?>

<table class="text hoverable dtable standard" id="all-countries">
	<thead>
		<tr>
			<th data-name="name" data-sort="auto">Name</th>
			<th data-name="country" data-sort="auto" data-width="150px">Country</th>
			<th data-name="audience" data-sort="fuzzy-numeric">Audience Size</th>
			<?php foreach ($this->tableMetrics as $key=>$label) : ?>
				<th data-name="<?php echo $key; ?>" data-width="150px" data-sort="traffic-light"><?php echo $label; ?> (average)</th>
			<?php endforeach; ?>
			<th data-name="presences">Presences</th>
			<th data-name="options" data-width="150px"></th>
		</tr>
	</thead>
	<tbody>
		<?php /** @var $country Model_Country */ ?>
		<?php foreach ($this->countries as $country) : ?>
		<tr>
			<?php $presences = $country->getPresences(); ?>
			<td><a href="<?php echo $this->url(array('action'=>'view', 'id'=>$country->id)); ?>"><?php echo $country->display_name; ?></a></td>
			<td><?php echo $country->getName() . ' (' . $country->country . ')'; ?></td>
			<td><?php echo number_format($country->audience); ?></td>
			<?php if ($presences) : ?>
			<?php $kpiData = $country->getKpiAverages(); foreach ($this->tableMetrics as $key=>$label) : $value = $kpiData[$key]; ?>
				<td>
                    <span class="icon-circle icon-large pull-left" data-value="<?php echo $value; ?>" style="color:<?php echo $this->trafficLight()->color($value, $key); ?>;"></span>
					<?php echo $this->trafficLight()->label($value, $key); ?>
				</td>
			<?php endforeach; ?>
			<td>
                <ul class="entity-list">
                <?php foreach($presences as $presence) : ?>
                    <li>
                        <?php echo $this->partial('partials/presence_inline.phtml',  array('presence' => $presence)); ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </td>
			<?php else : ?>
			<?php foreach ($this->tableMetrics as $key=>$label) : ?>
			<td>-</td>
			<?php endforeach; ?>
			<td>-</td>
			<?php endif; ?>
			<td>
				<?php
					$actions = $this->gatekeeper()->filterAll(array(
						'- <a href="%url%">Edit</a>' => array('action'=>'edit', 'id'=>$country->id),
						'- <a href="%url%">Presences</a>' => array('action'=>'manage', 'id'=>$country->id),
						'- <a href="%url%" class="autoConfirm">Delete</a>' => array('action'=>'delete', 'id'=>$country->id)
					));
					echo implode('<br />', $actions);
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
