<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

$country = $this->country;

$topBar = $this->gatekeeper()->filterAll(array(
        '<a class="button-bc button-view" href="%url%">'.$translator->trans('buttons.country.view').'</a>' => array('controller'=>'country', 'action'=>'view', 'id'=>$country->id),
        '<a class="button-bc button-edit" href="%url%">'.$translator->trans('buttons.country.edit').'</a>' => array('controller'=>'country', 'action'=>'edit', 'id'=>$country->id)
    ));

$bottomBar = array();
$cancel = $this->gatekeeper()->filter('<a href="%url%" class="button-bc">'.$translator->trans('buttons.common.cancel').'</a>', array('controller'=>'country', 'action'=>'view', 'id'=>$country->id), null, true);
if ($cancel) {
    $bottomBar[] = $cancel;
}
$bottomBar[] = '<button type="submit" class="button-bc">'.$translator->trans('buttons.common.save').'</button>';
?>

<h2 class="page-title"><?php echo $this->pageTitle; ?></h2>

<form class="management" method="post" action="<?php echo $this->url(); ?>" novalidate id="manage-country">
    <?php
    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$topBar, 'dark'=>true));

	echo $this->partial('partials/assign-presences.phtml', array(
			'owner' => $country,
			'presences' => $this->presences,
		));

    echo $this->partial('partials/button-bar.phtml', array('buttons'=>$bottomBar, 'dark'=>true));
    ?>
</form>

