<h2 class="page-title">Manage Presences</h2>

<form method="post" action="<?php echo $this->url(); ?>" class="management" novalidate id="manage-country">

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 columns">
                <ul class="button-group">
                    <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'country', 'action'=>'index'), null, true); ?></li>
                    <li><button type="submit" class="button-bc">Save</button></li>
                </ul>
            </div>
        </div>
    </div>

    <h2>Presences in <?php echo $this->country->display_name; ?></h2>

	<?php
	echo $this->partial('partials/assign-presences.phtml', array(
			'owner'=>$this->country,
			'presences'=>$this->presences,
		));
	?>

    <div class="button-bc-bar">
        <div class="row bk-dark">
            <div class="small-24 columns">
                <ul class="button-group">
                    <li><?php echo $this->gatekeeper()->filter('<a href="%url%" class="button-bc">Cancel</a>', array('controller'=>'country', 'action'=>'index'), null, true); ?></li>
                    <li><button type="submit" class="button-bc">Save</button></li>
                </ul>
            </div>
        </div>
    </div>
</form>

