<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

/** @var Model_Country $country */
$country = $this->country;
$presences = array_map(function($c) {
	/** @var Model_Presence $c */
	return $c->getName();
}, $country->getPresences());
$presenceCount = count($presences);
$region = $country->getRegion();
?>

<div class="row">
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2><?php echo $translator->trans('route.country.report.label.additional-info'); ?></h2>
            <p><?php echo $translator->trans('route.country.report.label.containing-region', ['%region%' => htmlspecialchars($region->display_name)]); ?></p>
            <p><?php echo $translator->trans('route.country.report.label.audience-size')?>: <?php $country->getTargetAudience(); ?></p>
            <p><?php echo $translator->trans('route.country.report.label.country-population')?>: <?php echo number_format($country->population); ?></p>
            <p><?php echo $translator->trans('route.country.report.label.digital-population')?>:
				<?php echo number_format(round($country->getDigitalPopulation())) . ' (' . $country->penetration . '% penetration)'; ?>
			</p>
        </section>
    </div>
    <div class="small-12 columns">
        <section class="border-section info-section">
            <h2><?php echo $translator->trans('route.country.report.label.presence-count', ['%count%' => $presenceCount])?></h2>
            <p><?php echo htmlspecialchars(implode(", ", $presences))?>.</p>
        </section>
    </div>
</div>