<?php
use Outlandish\SocialMonitor\PresenceType\PresenceType;

/** @var Model_Country $country */
$country = $this->country;
/** @var Model_Presence[] $presences */
$presences = $country->getPresences();
$countryLink = $this->gatekeeper()->filter('<a href="%url%">' . $country->display_name . '</a>', array('controller' => 'country', 'action' => 'view', 'id' => $country->id));
if (!$countryLink) {
    $countryLink = $country->display_name;
}
$presenceGroups = array();
foreach (PresenceType::getAll() as $type) {
    $typePresences = $country->getPresencesByType($type);
    $presenceGroups[] = array(
        'type' => $type,
        'presences' => $typePresences
    );
}
?>

<div class="badge-small" data-country-id="<?php echo $country->id; ?>" data-badge>
    <h3><?php echo $countryLink; ?></h3>
    <div class="badge-score bd-btm">
        <h4><span data-badge-title></span> <?php echo $this->translate('Global.score')?></h4>
        <div class="score-value" data-badge-score></div>
        <div class="score-bar">
            <div data-badge-bar></div>
        </div>
    </div>
    <div class="bd-btm">
        <h4><?php echo $this->translate('Global.presences')?></h4>
        <div class="score-value"><?php echo count($presences); ?></div>
    </div>

    <?php foreach ($presenceGroups as $group) : ?>
        <?php if($group['presences'] && count($group['presences'])): ?>
            <div class="bd-btm presence-list">
            <h4><?php
                /** @var PresenceType $type */
                $type = $group['type']; echo $type->getTitle();
                ?>
            </h4>
            <ul class="badge-presences">
                <?php foreach ($group['presences'] as $presence): ?>
                    <li>
                        <?php echo $this->partial('partials/presence-summary.phtml', array('presence'=>$presence)); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>