<?php
//$buttons = $this->gatekeeper()->filterAll(array(
//	'<a class="button" href="%url%"><span class="icon-edit icon-large"></span> Edit Country</a>' => array('action'=>'edit', 'id'=>$this->country->id),
//	'<a class="button" href="%url%"><span class="icon-tasks icon-large"></span> Manage Presences</a>' => array('action'=>'manage', 'id'=>$this->country->id)
//));

$this->campaign = $this->country;
$this->controllerName = 'country';
$this->campaignType = 'Country';
echo $this->render('partials/campaign-view.phtml');
