<?php
/** @var \Symfony\Component\Translation\Translator $translator */
$translator = $this->translate();

/** @var Model_Country $country */
$country = $this->campaign;
$presences = $country->getPresences();
$region = $country->getRegion();
?>

<h4 class="campaign-name">
    <div class="sm-flag flag-<?php echo $country->getCountryCode(); ?>"></div>
    <?php echo $country->display_name; ?>
</h4>

<?php if ($region) : ?>
    <p>
		<?php echo $translator->trans('Global.containing-region', ['%region%' => '<a href="' . $this->url(array('controller'=>'region', 'action'=>'view', 'id'=>$region->id)) . '">'.$region->display_name.'</a>']); ?>
	</p>
<?php endif; ?>

<p><?php echo $translator->trans('Global.available-audience-size')?>: <?php echo number_format($country->getTargetAudience()); ?></p>
<p><?php echo $translator->trans('Global.country-population')?>: <?php echo number_format($country->population); ?></p>
<p><?php echo $translator->trans('Global.digital-population')?>: <?php echo number_format(round($country->getDigitalPopulation())) . ' (' . $country->penetration . '% ' . $translator->trans('Global.penetration') . ')'; ?></p>

<h4>Presences: <?php echo count($presences); ?></h4>
<?php if ($presences) : ?>
    <ul class="entity-list">
        <?php foreach ($presences as $p) : ?>
            <?php echo $this->partial('partials/presence_box.phtml', array('presence'=>$p)); ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
