prod:
  db:
    adapter: Pdo_Mysql
    params:
      host: 212.13.212.66
      dbname: bcmonitor
      username: a_bcmonitor
      password:
  presence:
    cache_data_hours: 4
  twitter:
    consumer_key: ***REMOVED***
    consumer_secret: ***REMOVED***
    access_token: ***REMOVED***
    access_token_secret: ***REMOVED***
    fetch_per_page: 200
    cache_user_data: 7
  facebook:
    appId: ***REMOVED***
    secret: ***REMOVED***
    fetch_per_page: 50
    cache_user_data: 7
  klout:
    api_key: ***REMOVED***
  app:
# e.g. 7 Feb 2012 for PHP date()
    dateFormat: j M Y
    fetch_time_limit: 1140
    client_name: Outlandish
  jsConfig:
# e.g. 7 Feb 2012 for jQuery UI
    dateFormat: d M yy
    pageSize: 50

stage:
  _extends: prod
  db:
    params:
      dbname: staging

devel:
  _extends: prod

alpha:
  _extends: prod
  db:
    params:
      host: 127.0.0.1
      username: root
      password:
