prod:
  presence:
    cache_data_hours: 4
  twitter:
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
    fetch_per_page: 200
    cache_user_data: 7
  facebook:
    appId:
    secret:
    fetch_per_page: 50
    cache_user_data: 7
  klout:
    api_key:
  app:
# e.g. 7 Feb 2012 for PHP date()
    dateFormat: j M Y
    fetch_time_limit: 1140
    client_name: Outlandish
    colorscheme: britishcouncil.scss
  jsConfig:
# e.g. 7 Feb 2012 for jQuery UI
    dateFormat: d M yy
    pageSize: 50

stage:
  _extends: prod

devel:
  _extends: prod

alpha:
  _extends: prod
