live:
  db:
    adapter: Pdo_Mysql
    params:
      host: 212.13.212.68
      dbname: live
      username: 33digital
      password:
  twitter:
    consumer_key: ***REMOVED***
    consumer_secret: ***REMOVED***
    cache_user_data: 7
    network_max_size: 150
    list_fetch_per_page: 300
    search_fetch_per_page: 100
    network_max_user_connections: 100000
  openamplify:
    enabled: 1
    api_key: ***REMOVED***
    stop_words:
     - rt
     - http
     - https
     - @
     - t.co
    min_text_length: 5
    max_failures: 10
    max_duration: 550
    batch_size: 50
    daily_request_limit: 50000
  klout:
    api_key: ***REMOVED***
  peerindex:
    api_key: ***REMOVED***
  facebook:
    appId: ***REMOVED***
    secret: ***REMOVED***
    cache_user_data: 7
  app:
# e.g. 7 Feb 2012 for PHP date()
    dateFormat: j M Y
    notification_email: lpteam@33-digital.com
    fetch_time_limit: 1140
  jsConfig:
# e.g. 7 Feb 2012 for jQuery UI
    dateFormat: d M yy
    pageSize: 50

stage:
  _extends: live
  db:
    params:
      dbname: staging
  app:
    notification_email: tamlyn.rhodes@gmail.com

devel:
  _extends: live

alpha:
  _extends: live
  db:
    params:
      host: 127.0.0.1
      dbname: 33dashboard
      username: root
      password:
  app:
    notification_email: tamlyn.rhodes@gmail.com