live:
  db:
    adapter: Pdo_Mysql
    params:
      host: 212.13.212.68
      dbname: bcmonitor
      username: a_bcmonitor
      password:
  twitter:
    consumer_key: ***REMOVED***
    consumer_secret: ***REMOVED***
    cache_user_data: 7
    list_fetch_per_page: 300
    search_fetch_per_page: 100
  klout:
    api_key: ***REMOVED***
  peerindex:
    api_key: ***REMOVED***
  facebook:
    appId: ***REMOVED***
    secret: ***REMOVED***
    cache_user_data: 7
  app:
# e.g. 7 Feb 2012 for PHP date()
    dateFormat: j M Y
    notification_email: lpteam@33-digital.com
    fetch_time_limit: 1140
  jsConfig:
# e.g. 7 Feb 2012 for jQuery UI
    dateFormat: d M yy
    pageSize: 50

stage:
  _extends: live
  db:
    params:
      dbname: staging
  app:
    notification_email: tamlyn.rhodes@gmail.com

devel:
  _extends: live

alpha:
  _extends: live
  db:
    params:
      host: 127.0.0.1
      username: root
      password:
  app:
    notification_email: tamlyn.rhodes@gmail.com