home:
  label: Home
  Title: World Map
  icon: icon-home icon-large
  controller: index
  action: index
region:
  label: Regions
  Title: Index of Regions
  icon: icon-globe icon-large
  controller: region
  action: index
country:
  label: Countries
  Title: Index of Countries
  icon: icon-flag icon-large
  controller: country
  action: index
group:
  label: SBUs
  Title: Index of SBUs, Projects & Products
  icon: icon-th-large icon-large
  controller: group
  action: index
presence:
  label: Presences
  title: Index of Presences
  icon: icon-bar-chart icon-large
  controller: presence
  action: index
domain:
  label: Domains
  title: Index of Domains
  icon: icon-laptop icon-large
  controller: domain
  action: index