user:
  id: user
  controller: user
  action: edit-self
  icon: icon-user icon-large
  pages:
    account:
      id: account
      controller: user
      action: edit-self
    signout:
      id: sign-out
      controller: user
      action: logout
