home:
  id: home
  icon: icon-home icon-large
  controller: index
  action: index
region:
  id: regions
  icon: icon-globe icon-large
  controller: region
  action: index
country:
  id: countries
  icon: icon-flag icon-large
  controller: country
  action: index
group:
  id: sbus
  icon: icon-th-large icon-large
  controller: group
  action: index
presence:
  id: presences
  icon: icon-bar-chart icon-large
  controller: presence
  action: index
domain:
  id: domains
  icon: icon-laptop icon-large
  controller: domain
  action: index
statuses:
  id: statuses
  icon: icon-comment-alt icon-large
  controller: statuses
  action: index