#user:
#  label: User
#  controller: user
#  action: edit-self
#  icon: icon-user icon-large
hashtag:
  id: hashtags
  icon:
  controller: hashtag
  action: index
domain:
  id: domains
  icon: icon-laptop icon-large
  controller: domain
  action: index
users:
  id: users
  controller: user
  icon: icon-group icon-large
  class: parent
  pages:
    account:
      id: account
      controller: user
      action: edit-self
    edit-all:
      id: edit-users
      controller: user
    signout:
      id: sign-out
      controller: user
      action: logout
config:
  id: settings
  controller: config
  icon: icon-cog icon-large
