home:
  label: Home
  Title: World Map
  icon: icon-home icon-large
  controller: index
#group:
#  label: Campaigns
#  controller: group
country:
  label: Countries
  Title: Index of Countries
  icon: icon-globe icon-large
  controller: country
group:
  label: SBUs
  Title: Index of SBUs, Projects & Products
  icon: icon-th-large icon-large
  controller: group
presence:
  label: Presences
  title: Index of Presences
  icon: icon-bar-chart icon-large
  controller: presence
domain:
  label: Domains
  title: Index of Domains
  icon: icon-laptop icon-large
  controller: domain