user:
  label: User
  controller: user
  action: edit-self
  icon: icon-user icon-large
users:
  label: Users
  controller: users
  icon: icon-group icon-large
config:
  label: Settings
  controller: config
  icon: icon-cog icon-large
